### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by tj** [apex/up#1]
How it compares to other solutions, pros and cons, pricing of AWS stuff, APIGW/Lambda limitations etc.

**Comment by lukeed** [comment]
Would love a "How To: Global Distribution" as part of this. In my book, one of the most appealing features, and I'm sure others (like myself) aren't going to know how to get the most of Lambda.

**Comment by muhajirframe** [comment]
Hi @tj , i am pretty confused with this project. Does it works like zeit's now? You just type `up` and everything is up? And also i found there is no code on this repo, is is intended? And how can I install `up`?

**Comment by tj** [comment]
@muhajirframe correct, it'll be similar to Heroku / Now / Google App Engine etc in scope and user experience, but hosted in your own AWS account. I haven't pushed the code yet since I have a few things to implement first (just causes extra issue noise if people can't get it working etc).

It's also being built to abstract the provider entirely, so in the future you could `up` to Digital Ocean, Hyper.sh, Google, Azure, etc.

**Comment by muhajirframe** [comment]
Oh my god! , I have been waiting for this 😂😹 . +999 for this project.

Okay, when will this be released? I mean time estimation maybe?

**Comment by tj** [comment]
Hahaha good to hear, should be a fun little project to hack on! I'll try and get the first release out in a week or two :D

**Comment by stevelacy** [comment]
Just wondering, how different would Up be from [convox](https://convox.com) and their [rack](https://github.com/convox/rack)? (We currently use convox, and are eagerly wanting a better replacement).

**Comment by tj** [comment]
@stevelacy primarily the "serverless" aspect. Convox is sweet but ECS ends up being too expensive for people like myself, and generally the ease of managing / scaling Lambda is super trivial.

**Comment by lukeed** [comment]
I have two other suggestions:

1) Explain the differences between Up & Apex, and when it's more appropriate to use one vs the other. While this may be obvious for some, it won't be for the majority -- esp those without AWS backgrounds.

2) Add a(ny) DB integration example. Could be a dead simple API endpoint that serves from a DB query. Most likely pairs best with the "How To: Global Distribution" from above. 

    Global API responses + global DB replication = game changer.

**Comment by lukeed** [comment]
How will Pro's "In-Memory Caching" work? Is that a global & configurable cache or is it a one-size-fits-all approach for all routes? Also, I'm curious about _where_ the caching will take place & if responses served from cache will count towards my Lambda usage metrics.

Thanks! And sorry, hard to contain excitement~

**Comment by tj** [comment]
Might swap that one out, since API Gateway has a cache feature it should be a simple configuration, but caching in the lambda itself would be cost effective that's for sure, I believe it respects HTTP caching though so it should be "global", I'll double check! Hope so at least haha

**Comment by tj** [comment]
I'll be adding more info such as latency, cold start timing, etc but https://github.com/apex/up#pricing has a bit of a comparison for now

**Comment by lukeed** [comment]
Surge is also popular.

**Comment by tj** [comment]
ah! yes totally forgot about Surge
