### ISSUE TITLE
Finish stack updates and planning

### ISSUE THREAD

**Issue by tj** [apex/up#115]
Needs a general cleanup and changeset integration so changes can be previewed and applied.

- [x] create changeset
- [x] show changes
- [ ] apply changes
- [ ] fix update progress bar panic
- [ ] fix delete progress bar panic (when resources are removed, local template mismatch)
- [ ] nicer formatting
- [ ] nice error for when plan does not exist
- [ ] nicer errors

Need to decide on the commands still, likely similar to Terraform:

```
# Alias of plan or status (apply would be dangerous)
$ up stack

# Preview changes
$ up stack plan

# Apply those changes
$ up stack apply

# Show the status and resources (maybe named list or something)
$ up stack status

# Output JSON representation when !isatty
$ up stack status | cat

$ Output for use with Terraform
$ up stack status --tfvars
```

Any preferences for what `up stack` should alias?

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Plan)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Plan/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Apply)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Apply/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Status)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BQ27FVZ64CZ5M2PD7Y34RY36/Status/vote)

**Comment by tundrax** [comment]
Is there a way to list the stack (resources) created and managed by `up`?

**Comment by tj** [comment]
@tundrax `up stack` used to display it, but CloudFormation's IDs are really ugly and difficult to read so I removed it for now, might be nice to add something back though!
