### ISSUE TITLE
Default stage names

### ISSUE THREAD

**Issue by tj** [apex/up#120]
dev / prod for now, "stage" looks redundant with `--stage stage` etc haha so staying away from that.

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/dev%20and%20prod)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/dev%20and%20prod/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/development%20and%20production)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/development%20and%20production/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/stage%20and%20prod)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/stage%20and%20prod/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/stage%20and%20production)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNVAFF9YMJXVX0KRTG0JV04S/stage%20and%20production/vote)

**Comment by stevelacy** [comment]
`development` `staging` and `production` are the terms a few startups I've worked in use.

**Comment by lukeed** [comment]
If given the choice, I believe most devs would prefer to type less 😉

**Comment by tj** [comment]
Yeah for me dev is typically not an env since it's your machine, but I've been using the API Gateway term of "stage" in place of "env" so `--stage stage` is weird haha, `--stage staging` is definitely better

**Comment by tj** [comment]
@lukeed yea that's how I feel too

**Comment by tj** [comment]
case closed, dev/prod good enough for me haha

**Comment by tj** [comment]
might change `prod` to `production` later specifically because it's large and annoying to type, could prevent some mishaps

**Comment by lukeed** [comment]
I hate when I accidentally write `dev` as `prod` 😆 

JK, I don't care either way 👻
