### ISSUE TITLE
Streaming responses

### ISSUE THREAD

**Issue by matthewp** [apex/up#130]
My understanding of Lambda is that it only supports a single callback and therefore can't do streaming responses. The Node.js example uses `res.end()`: https://github.com/apex/up-examples/blob/master/community/node-basic/server#L8. Am I correct that whatever wrapper is being provided here is going to wait for `end()` to be called and send back the entire response (meaning res.write() calls will be buffered)?

**Comment by tj** [comment]
@matthewp for now they're buffered, like you mentioned it's a Lambda limitation for now, stuck with it unfortunately.

**Comment by matthewp** [comment]
OK, so I guess this should be closed since it's a bug in Lambda and not apex/up. Thanks!

**Comment by ZJONSSON** [comment]
So 2018 is over soon  and  aws lambda still does not support streaming for node.   However, streaming seems to be supported by the [java implementation](https://docs.aws.amazon.com/lambda/latest/dg/java-handler-io-type-stream.html)

@tj do you think it would be a feasible idea to replace the `_proxy.js` with a java implementation that would stream the response?

**Comment by tj** [comment]
@ZJONSSON hmm I'm not sure that the underlying Lambda calls are actually streaming in that case, it might just be buffering and responding. Just a guess though, but as far as I know any streaming wouldn't work with the `Invoke` / `InvokeAsync` calls, might be special-cased for API Gateway though!
