### ISSUE TITLE
Scheduled requests

### ISSUE THREAD

**Issue by tj** [apex/up#15]
Big maybe, this starts to enter into apex(1) / Serverless territory, not sure I really want to go there, but it would be nice to not use verbose Terraform stuff just to set up scheduled tasks.

**Comment by lukeed** [comment]
Pro feature imo, if it lands.

**Comment by tj** [comment]
Think I'll close this one for now, feature-creeping into evented stuff.

**Comment by jpillora** [comment]
Is this possible with CloudWatch > Rules > Targets > Lambda > Input > "Constant (JSON text)" ? Where the JSON text is something like `{"method":"GET","path":"/foo/bar"}`?

**Comment by tj** [comment]
@jpillora yep! I forget what the properties are off-hand but something like that should be fine

**Comment by cloudkite** [comment]
Its actually possible to "secure" the schedule request by hijacking the requestId field of requestContext.

ie if you put the following as your JSON text in your cloud watch rule

```
{"requestContext":{"requestId":"cron","stage":"staging"},"httpMethod":"POST","path":"/api/cron","body":"{}"}
```

in your code you can then do something like this:

```
if (request.headers["x-request-id"] !== "cron") return { status: 403 }
```

Since x-request-id is always overridden by UP from requestContext a malicious request cant send this as a header. Meaning that you can verify that requests legitimately from cloudwatch schedule.

@tj can you see any issues with this approach? 😅

**Comment by tj** [comment]
@cloudkite ahaha interesting yeah that sounds like it'd work! Since we'd have the target path with config—something like below—we'd potentially be able to blacklist it for the user too, but that means that path wouldn't be available externally in any case, but it removes the need to check for `== "cron"` manually

```json
{
  "cron": [
    {
      "path": "/whatever/here",
      "interval": "30m"
    }
  ]
}
```

I still question if it's even worth adding for HTTP hahah when regular Lambda + Scheduled events is already great for this. I think the better approach might be to do an Apex 2.0 which has this stuff built in for FaaS

**Comment by cloudkite** [comment]
@tj yeah totally agree regular lambda and scheduled events are probably a better fit. I just didn’t want to have to have an additional project to deploy. I’ve got this setup as above and seems to work well. More than fine with it being a manual thing and not built in to UP
