### ISSUE TITLE
Domain registration

### ISSUE THREAD

**Issue by tj** [apex/up#159]
I keep forgetting route53 lets you purchase domains.

- [ ] register with prompts for the whois info
- [ ] list command
- [ ] remove command
- [ ] add pricing
- [ ] test with CFMN (RegisterDomain creates a zone for you)

**Comment by lukeed** [comment]
Ooh nice, didn't know this. Seems to be a [bit of a markup](https://d32ze2gidvkk54.cloudfront.net/Amazon_Route_53_Domain_Registration_Pricing_20140731.pdf) though --- expected I guess.

Most everywhere, `.com` is 8.99 or 9.99 --> R53 is $12. Similarly, `.io` is generally $32 --> R53 is $39.

> Cliff-noting for others.

**Comment by tj** [comment]
crazy that they only having pricing in PDF form hahah wtf

**Comment by lukeed** [comment]
Obviously not a selling point. Then again... Amazon ≠ UI Designers

**Comment by tj** [comment]
yeaaa haha go to all the trouble to make a nice PDF, when JSON or just adding it to the API is so much easier, typical AWS

**Comment by lukeed** [comment]
10/10 would like to redesign _all_ of Amazon products at a discount rate, just for the sake of fixing it. 🤦‍♂️

**Comment by agurtovoy** [comment]
@lukeed Please don't, @tj needs room for growth :)

**Comment by lukeed** [comment]
We could tag team it ;-P

**Comment by tj** [comment]
someone will do it eventually haha, I hope that person makes like 2M/year, AWS reallllllllly needs it
