### ISSUE TITLE
Custom domain mapping

### ISSUE THREAD

**Issue by tj** [apex/up#166]
For now the only way to map custom domains is via CloudFront, which is really slow to provision. In the future there should be more options.

- [x] domain map by stage?
- [x] support for existing zone (registering via r53 does this for you)
- [x] support for custom zones
- [x] ACM wildcard so you don't have to confirm multiple...
- [x] validate .domain (and require it)
- [x] QA for subdomains only
- [x] QA new zone without records
- [x] QA new zone with records
- [x] QA existing zone without records
- [x] QA existing zone with records
- [x] dont create certs on plan?
- [ ] command to output the name servers? after stack apply?..
- [ ] document
  - [ ] DNS for registrars
  - [x] stage mapping stuff
  - [x] remove `certs` mentions
  - [x] add workflow docs... deploying to prod etc
  - [ ] add header anchors in docs... and link to sections throughout
  - [ ] mention CF provision time
  - [ ] images for docs
- [ ] finalize wording for log output
  - [ ] for email confirmation
  - [ ] for CF provisioning time

**Comment by tj** [comment]
should have this in pretty soon, QA is slowww

**Comment by holic** [comment]
I gave this a whirl and it worked great!

Are there plans to support multiple domains for a given stage? For example, I want to host an app on `example.com` and `www.example.com` (both with HTTPS support) and allow my app to redirect one to the other. I initially tried to do this via `dns` configuration using a `CNAME`, but got a CloudFront error.

**Comment by tj** [comment]
@holic awesome! Hmm the CNAME should work I think, recall what the error was? Maybe it's not happy about CNAMEs to ALIAS records. If that's the case then yea it'll definitely need support for more domains!

**Comment by holic** [comment]
Ah, I should note the CloudFront error was from accessing the domain, not while setting up the DNS records. An example set of DNS records:

```json
{
  "dns": {
    "example.com": [
      {
        "name": "www.example.com",
        "type": "CNAME",
        "ttl": 300,
        "value": ["example.com"]
      }
    ]
  }
}
```

These got set up at AWS just fine, but when I access `https://www.example.com`, I get an error like:

> ERROR
>
> The request could not be satisfied.
>
> Bad request. 
>
> Generated by cloudfront (CloudFront)

(I assume this is because CloudFront doesn't know how to map the domain to the app?)

**Comment by tj** [comment]
@holic ahh I see, yea I think you're right, sucks if we need another CF distribution for that, I'll have to double check
