### ISSUE TITLE
Chrome extension for GH logs / metrics / CI

### ISSUE THREAD

**Issue by tj** [apex/up#17]
Big maybe but it might be kind of cool to inject "Logs" and "Metrics" tabs into Github for your apps. Tying your GH org together with Up could be a nice way to leverage existing org data.

Downside of course is that you need to install the extension, but it's one less tab to leave open all day.

**Comment by tj** [comment]
Closing for now, I think a dedicated app would be better, I want to add quite a few features so GH would quickly become cluttered.

**Comment by lukeed** [comment]
I agree with the dedicated app, but would suggest that it didn't delay the release date 😉

**Comment by tj** [comment]
Definitely. The "community" edition is priority for now, I think there's one deal-breaker in API Gateway right now which may prevent it from being useful, waiting on a response from one of the project managers there. Aside from that it's just about ready

**Comment by lukeed** [comment]
Awesome, congrats 🎉 Looking forward to being a (paying) user & contributing back to the OSS parts.

**Comment by tj** [comment]
:D appreciate the support!
