### ISSUE TITLE
feature request: add lertsencrypt certificates.

### ISSUE THREAD

**Issue by komuW** [apex/up#170]
From, https://github.com/apex/up/blob/master/docs/configuration.md#ssl-certificates 
seems like `up` can help issue free AWS ssl certs. 
If `up` ever decides to target other cloud providers(azure etc), it may be a good idea to use letsencrypt for certs.

**Comment by tj** [comment]
Yep! AWS ACM uses letsencrypt behind the scenes I believe. The config may need to be reworked a bit to facilitate other providers later, but I'm focusing mostly on AWS for now

**Comment by slaskis** [comment]
@tj have you seen https://github.com/k1LoW/certman ? 

it's such a smooth process (for the user, the implementation is pretty crazy) to setup certs for aws as there's no need to respond to an email.

**Comment by tj** [comment]
Hahah yea probbbably not worth it for now, ACM works great, the email part is a small annoyance but who knows maybe that'll change that

**Comment by tj** [comment]
closing for now
