### ISSUE TITLE
Document minimum IAM permissions required

### ISSUE THREAD

**Issue by tj** [apex/up#176]

**Comment by stephenmathieson** [comment]
This (copied from apex, then added a few) seems to be working for me:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "cloudformation:CreateStack",
        "cloudformation:DeleteStack",
        "cloudformation:DescribeStackEvents",
        "cloudformation:DescribeStacks",
        "cloudwatch:GetMetricStatistics",
        "iam:AttachRolePolicy",
        "iam:CreatePolicy",
        "iam:CreateRole",
        "iam:DeleteRole",
        "iam:DeleteRolePolicy",
        "iam:PassRole",
        "iam:PutRolePolicy",
        "lambda:CreateAlias",
        "lambda:CreateFunction",
        "lambda:DeleteFunction",
        "lambda:GetAlias",
        "lambda:GetFunction",
        "lambda:GetFunctionConfiguration",
        "lambda:InvokeFunction",
        "lambda:ListAliases",
        "lambda:ListFunctions",
        "lambda:ListVersionsByFunction",
        "lambda:UpdateAlias",
        "lambda:UpdateFunctionCode",
        "lambda:UpdateFunctionConfiguration",
        "logs:FilterLogEvents"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

**Comment by tj** [comment]
@stephenmathieson ah cool thanks! That fixes #192? I haven't tried sans-root yet but that looks good to me

**Comment by ile** [comment]
Hi,

I'm just trying out Up and trying to deploy. I get this:

`Error: deploying: us-east-1: The following resource(s) failed to create: [Api, ApiFunctionAliasDevelopment, ApiFunctionAliasStaging].`

Does the policy need something extra or am I forgetting something?

**Comment by tj** [comment]
@ile looks like it's still missing a few, I'm going through now, I'll update that in a minute

**Comment by ile** [comment]
I added `execute-api:Invoke`

But then I got this:
`Error: deploying: iam: creating role: EntityAlreadyExists: Role with name testapp-api-function already exists.
	status code: 409, request id: 22fcd35c-7ca2-11e7-aa2b-afeb439e9dc1`

Then I deleted a couple of roles made by Up and ran `up` again and it worked:

`        build: 269 files, 3.6 MB (559ms)
       deploy: complete (6.318s)`

**Comment by ile** [comment]
Also this:

```
Error: fetching api: fetching apis: AccessDeniedException: User: arn:aws:iam::536645619975:user/up is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-1::/restapis
	status code: 403, request id: 7bbb5fb2-7ca3-11e7-9cc5-45ad1e19a884
```

**Comment by tj** [comment]
@ile updated here bedb88654ea80c267b122a692b2ee189dbc6cd4c

**Comment by ile** [comment]
Thanks. I noticed already and ran it, but got this:

```
$ up

        build: 269 files, 3.6 MB (639ms)
       deploy: complete (1.044s)


  Error: deploying: us-east-1: updating function config: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
	status code: 400, request id: 6dcdf907-7ca6-11e7-b195-737621b5c43e
```

**Comment by tj** [comment]
might have to delete the function due to the issue with permissions before, hopefully no one will hit that path now. The create path hits https://github.com/apex/up/blob/master/platform/lambda/lambda.go#L279-L282, which keeps retrying (eventual consistency yayyyy)

**Comment by ile** [comment]
True, I got a little forward after deleting the function:

```
$ up

        build: 269 files, 3.6 MB (615ms)
       deploy: complete (11.454s)


  Error: deploying: us-east-1: creating stack: AlreadyExistsException: Stack [testapp] already exists
	status code: 400, request id: d9a76bc0-7ca7-11e7-a4a6-51924dfd5923
```

Also I needed to delete the role first:
```
  Error: deploying: us-east-1: updating function config: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
	status code: 400, request id: 6dcdf907-7ca6-11e7-b195-737621b5c43e
```

**Comment by ile** [comment]
Ok, it seemed to be in CouldFormation, and after deleting the role, function and the stack I it deployed succesfully, it seems.

**Comment by tj** [comment]
@ile cool if you hit anything else let me know. Feel free to join on Slack too (https://apex-dev.azurewebsites.net/)

**Comment by ile** [comment]
Thanks @tj. So far, without knowing too much about Up, seems like this is a very much needed tool. I couldn't configure AWS in a million years. 

I get the feeling Amazon might be interested in this too (maybe depending on how open source-y this will be?).

So, thanks for this!
