### ISSUE TITLE
Unfriendly error when `up.json` is missing

### ISSUE THREAD

**Issue by stephenmathieson** [apex/up#191]
In an empty directory, running any `up` command yields an unhelpful error:

```
$ up --help
  Error: reading config: validating: .name: must contain only alphanumeric characters and '-'
```

Maybe error with "up.json missing" instead?

**Comment by tj** [comment]
ahh I didn't try a completely empty dir, it seems ok for me though:

```
   λ test: ll
total 0
drwxr-xr-x   2 tj    wheel    68B  8 Aug 16:07 .
drwxrwxrwt@ 36 root  wheel   1.2K  8 Aug 15:55 ..
   λ test: up --help

  Usage:

    up [<flags>] <command> [<args> ...]

  Flags:

    -h, --help           Output usage information.
...
```

**Comment by stephenmathieson** [comment]
Hmm very odd. My `up --version` just yields `master`. Also:

```
$ ls
up.json		node_modules		package.json
app.js			package-lock.json	policy.json
$ mv up.json _up.json
$ up --help

  Error: reading config: validating: .name: must contain only alphanumeric characters and '-'
$ mv _up.json up.json
$ up

        ⠙ build: ^C
```

**Comment by tj** [comment]
ah I had `const version` instead of `var version` so it didn't build properly, maybe try grabbing the latest binary, seems ok here:

```
   λ node-koa (master): up 

        build: 311 files, 3.7 MB (309ms)
       deploy: complete (3.632s)

```

**Comment by stephenmathieson** [comment]
```
$ up upgrade
  ...
$ up --version
0.1.2
$ mv up.json _up.json
$ up --version

  Error: reading config: validating: .name: must contain only alphanumeric characters and '-'
$
```

:/

**Comment by tj** [comment]
What's the dirname? Lambda/CloudFormation etc only allow certain characters, but you can define `.name`

**Comment by stephenmathieson** [comment]
The dirname must have been the problem.

A little off topic - I do think it's a bit odd that `up` will continue trying to deploy an app, even without _any_ configuration (missing `up.json`). Maybe this is what folks want, but I think it could lead to folks accidentally deploying things they weren't ready for.

**Comment by tj** [comment]
Ahh yeah #197, agreed. At very least it should probably only deploy ones that look like legit projects, or maybe _always_ warn without `up.json`
