### ISSUE TITLE
Add contributing instructions

### ISSUE THREAD

**Issue by stephenmathieson** [apex/up#196]
I've been trying to get a local version of `up` running so I can try to better debug (and get a decent understanding of the codebase). However, it's proving to be rather complicated to get my environment setup the way `up` expects it. So far, I've had to (all trial/error):

- install git-lfs
- install golang/dep
- run `dep ensure`
- install pointlander/peg
- install jteeuwen/go-bindata
- install golang/mock/mockgen

...and `make test` is still crashing. Is there any way you could add something to the README (or `./docs/`?) which documents all of these steps? I imagine it'd save several people quite a lot of time.

**Comment by tj** [comment]
FWIW you don't need peg etc unless you want to hack on the log grammar, but I'll try a fresh clone and see if I can add `make setup` or something, w/ docs
