### ISSUE TITLE
Upgrade command to update up(1)

### ISSUE THREAD

**Issue by tj** [apex/up#20]
Just like apex(1). It would be cool to check remotely maybe once per day too, and show the changelog

- [x] move apex's logic to a distinct package
- [x] add to up and test

**Comment by lukeed** [comment]
Sounds good! Sheepishly, what does the `(1)` denote? I see `apex(1)` in a bunch of places, but not sure if it's supposed to mean anything other than the `apex` binary.

**Comment by tj** [comment]
obscurity: http://www.december.com/unix/ref/mansec.html 

haha

**Comment by lukeed** [comment]
Gotcha, thanks =)
