### ISSUE TITLE
Add UP_STAGE environment variable

### ISSUE THREAD

**Issue by tj** [apex/up#200]
Technically I think it's more correct to set env vars _for_ the environment, not based on the env such as NODE_ENV. However we need it for logging anyway.

This may have to be a hack, setting the env on first request, since `stageVariables` is the only way to get at the stage (AFAIK).

**Comment by jamesramsay** [comment]
It would be handy for `UP_STAGE` to be made available to the hooks too, allowing particularly the build script to adjust it's behaviour accordingly.

I'm not sure if this issue refers to the application environment (in AWS) only, or making `UP_STAGE` available everywhere including local environment when building.

**Comment by tj** [comment]
Hmm yeah it's a little tricky, since the "ideal" way of deploying would be to stage the application, then promote the staged version to production. UP_STAGE would will be "staging" at that point

**Comment by cgarvis** [comment]
Promoting the stage build to production doesn't work for statically built files like next.js does.

**Comment by tj** [comment]
@cgarvis yea not if you differentiate config in those two stages. It depends how you structure things I suppose, since you can pass UP_STAGE to your client JS for example and choose config that way.

It would be a more ideal way to deploy since you know exactly what you're getting.

**Comment by cgarvis** [comment]
@tj I use webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to replace `process.env` in my builds.  That way I don't leak environment vars by accident.  Also makes it more difficult for someone on the team to hit the wrong endpoints.
