### ISSUE TITLE
Config for build directory

### ISSUE THREAD

**Issue by tj** [apex/up#201]
If you have build artifacts the common case will be having a `./dist` or `./build` dir, so we should add some kind of property for pointing to this instead of deploying the root.

```
.
├── build
│   ├── bundle.css
│   ├── bundle.js
│   └── index.html
├── src
│   ├── bar.css
│   ├── bar.js
│   ├── foo.css
│   ├── foo.js
│   ├── index.html
│   └── index.js
└── up.json
```

Any suggestions on a name? I've been using `.static.dir` etc, so maybe just a root level `dir`?

- [ ] add
- [ ] test
- [ ] document
- [ ] add example

**Comment by lukeed** [comment]
I think traditionally I've seen `public`, but not really fond of that tbh.

**Comment by tj** [comment]
I think you're right in the other issue, we probably don't need this for now, especially with `npm start` support etc
