### ISSUE TITLE
Log improvements

### ISSUE THREAD

**Issue by tj** [apex/up#207]
- [ ] don't strip the Lambda logs (as they contain timeouts etc)

**Comment by kaihendry** [comment]
How do I show logs from "Client Errors" in *production* stage? That has stumped me.

**Comment by tj** [comment]
Oops, I was omitting the stage field from the log output (f870ca2). They all go to the same CloudWatch group for now (later might be per-stage). 

For now filtering with something like:

```
$ up logs -s 50h 'stage = "development" status >= 400'
```
