### ISSUE TITLE
Install over homebrew

### ISSUE THREAD

**Issue by apertureless** [apex/up#209]
Would be cool if you could install it over homebrew. 👍

**Comment by lukeed** [comment]
Is just a `curl` command, so should be an easy, automated feature to add.

**Comment by tj** [comment]
once https://github.com/goreleaser/godownloader is fixed we'll have a one-liner that works on all platforms, much faster than homebrew too, but brew might be nice later just in case

**Comment by stephenmathieson** [comment]
The curl command needs to either:

- be remembered by a user (nope)
- be copied/pasted

Less than ideal imo, since we all know how to `brew install stuff`. Not a big deal either way, and maybe not worth the effort...

**Comment by tj** [comment]
@stephenmathieson I suppose, but with `up upgrade` you only need to copy/past it one time, and most people I imagine will read the repo/docs a little first

**Comment by tj** [comment]
oh I think you have to do `brew install user/repo/formula` unless your want to pull-request homebrew each time, not the best package manager hahah

**Comment by stephenmathieson** [comment]
Oh that's lame. Other people must be doing that for other projects then. Yeah not worth the effort haha

**Comment by kivlor** [comment]
I've opened a PR for this here - https://github.com/Homebrew/homebrew-core/pull/16650

The downside is my current implementation requires a new PR every time `up` gets a release 😓 I might revisit and take the terraform approach - https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb

**Comment by tj** [comment]
@kivlor ah cool thanks for doing that! It'd definitely be a bit of a pain, but on the bright side people could just do `brew install up && up upgrade`

**Comment by lukeed** [comment]
Can throw together a git hook + Up-curated Lambda function that resubmits a new PR on every release 😉

**Comment by tj** [comment]
seems insane if they manually review each PR haha

**Comment by kivlor** [comment]
Gahhh, didn't read the `terraform.rb` file closely enough, it requires a PR with each release as well 😓

**Comment by mrmark** [comment]
With Goreleaser, you can make your own tap that users use to install your binary. Goreleaser can then auto update the tap with each release, avoiding the PR to the Brew repos. Taps are very common, easy to use and under your control.

**Comment by tj** [comment]
@mrmark cool yea, might as well I suppose, even if it's basically just the install script at that point

**Comment by tj** [comment]
Closing for now since there's a one-liner and can just `up upgrade` later. Homebrew might be cool at some point if there's enough demand

**Comment by lukeed** [comment]
1.0 or near it imo... or at least post-alpha

**Comment by apertureless** [comment]
For me the advantage of brew, is that you can type `brew update && brew upgrade` and all of your tools / services will be updated. 

But I see that making manual PRs is a pain and may be not worth it, at the moment.

**Comment by tiamot** [comment]
+1 for brew installation.

**Comment by ashvinnihalani** [comment]
+1 for brew installation
