### ISSUE TITLE
Make it more obvious that you need to confirm ACM emails

### ISSUE THREAD

**Issue by tj** [apex/up#212]
Not so obvious, I also don't like the initial Stack progress bar, so we could do away with that too

**Comment by digitalsanctum** [comment]
Seems this could be automated by following the steps outlined here: https://medium.com/@sbuckpesch/setup-aws-s3-static-website-hosting-using-ssl-acm-34d41d32e394

**Comment by tj** [comment]
@digitalsanctum ahh interesting work-around, shame they require it in the first place
