### ISSUE TITLE
Allow disabling of relay retries

### ISSUE THREAD

**Issue by tj** [apex/up#213]
If the request is not idempotent this could be bad. Perhaps we're better off performing retries on GET/HEAD etc only, at least as a safe default.

**Comment by skabbes** [comment]
So, I believe the safest strategy would be to only retry requests that failed before sending ANY application data over the socket.  DNS lookups, etc are safe.  Perhaps we should just copy the retry policy from a well known reverse proxy - nginx, haproxy, or traefik (golang impl).

https://github.com/containous/traefik/blob/master/middlewares/retry.go#L36-L65
https://github.com/containous/traefik/blob/master/server/errorhandler.go#L23-L40

Another option I think would be _really_ interesting would be to have a go plugin which implements custom retry policies.
