### ISSUE TITLE
Retry relay 5xx errors

### ISSUE THREAD

**Issue by tj** [apex/up#214]
Optionally, let them specify how many attempts etc. Currently we only retry crashes.

**Comment by komuW** [comment]
nginx had this long standing bug[1] where they retried non-indempotent requests.
worth checking that up doesnt suffer same
1. https://trac.nginx.org/nginx/ticket/488

**Comment by tj** [comment]
@komuW awesome yea, mentioned that in #213, that would definitely be bad :D. I had no idea nginx had that feature!
