### ISSUE TITLE
Option to disable ansi escape sequences / color for output

### ISSUE THREAD

**Issue by shanepelletier** [apex/up#223]
Version 0.1.6 spews ANSI escape codes in the terminal. Here's just a quick excerpt from running `up` for the first time, but other subcommands also cause similar output:

```
?[38;5;102m|?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?
[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█
?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5
;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;61m█?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00
m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m░?[0;00m?[38;5;102m|?[0;00m 69
%

```

I'm using Windows 10, and have tried both `cmd` and Zeit's `hyper`, and the issue occurs in both.

**Comment by tj** [comment]
Hmm that's not good, I haven't used windows in years so I'm not much help, but seems odd that hyper has the issue, it's fine on OSX. I'll add some kind of option to disable coloring/progress bars etc

**Comment by shanepelletier** [comment]
Sounds good, if I figure out why this issue occurs I can try working on a pull request to fix it. It's weird since I don't have any issues with other projects like `yarn` that use ANSI codes 🤷.

**Comment by tj** [comment]
Ahh must not have 256 color support or something (I'm using https://github.com/aybabtme/rgbterm), still sounds a little bizarre about Hyper, I'd expect that to be the same on any platform.

**Comment by tj** [comment]
ah: https://github.com/zeit/hyper/issues/1968

**Comment by shanepelletier** [comment]
Well that explains it, leave it up to Microsoft to not even support 256 colors haha. Since `yarn` etc. work fine, it looks like standard ANSI codes would work fine but you'd have to use the "safe" colors. Just tested using Git Bash and it works fine so maybe a note about Command Prompt not supporting 256 colors would be helpful somewhere in the docs.

**Comment by tj** [comment]
closing for #422
