### ISSUE TITLE
Fix exec bit on Windows

### ISSUE THREAD

**Issue by tj** [apex/up#225]
On windows:

```
DEBU add main: size=8891243 mode=-rw-rw-rw-
```

On mac:

```
DEBU add main: size=8891243 mode=-rwxr-xr-x
```

**Comment by shanepelletier** [comment]
As a workaround, `up` works on Bash on Windows, at least for Node.js. Here's the relevant text from `up -v`:
`DEBU add main: size=8891243 mode=-rwxrwxrwx`.

**Comment by c0bra** [comment]
Hasn't worked for me with bash for windows and node.

**Comment by tj** [comment]
hopefully https://github.com/apex/up/commit/01995464db2f94ac0c82ca4d03ade9e70fe7de94#diff-b14e10f435fb3431cf5aaa5c8a643fafR20 will do the trick, I'll push a release later today

**Comment by c0bra** [comment]
thanks @tj!

**Comment by tj** [comment]
https://github.com/apex/up/releases/tag/v0.1.8
