### ISSUE TITLE
Continuous Integration examples for Circle, Travis, etc

### ISSUE THREAD

**Issue by tj** [apex/up#25]
So it's easy for people to get rolling with the existing CI services out there. What do you use?

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Circle)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Circle/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Travis)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Travis/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Semaphore)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Semaphore/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Jenkins)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Jenkins/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Other)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/Other/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/None)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C0MTYQY1NZZXNRVGJZCN3/None/vote)

If Up provided a "serverless" (via AWS CodeBuild) self-hosted CI out of the box, and it was cost effective, complete with CLI and dashboard, would you use it?

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/Yes)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/Yes/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/Maybe)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/Maybe/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/No)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM3C600TK2SD0FCC9RYRCT9E/No/vote)

**Comment by AdrienFromToulouse** [comment]
BTW, in the category `Other`, I would recommend [Wercker](http://www.wercker.com). It is really neat (recently bought by Oracle tho). For microservices deployment it is def very nice. The free offer is already covering a lot of use cases.

**Comment by tj** [comment]
@AdrienFromToulouse awesome thanks! Yeah with everything having pretty generous free tiers it makes me wonder if it's worth it, though I imagine larger commercial companies prefer keeping things locked down in AWS where possible.

**Comment by arikfr** [comment]
OMG, I accidentally clicked on Jenkins instead of Semaphore 😢

**Comment by edasque** [comment]
Whatever you end up with, please make sure it is one of the tsdb supported by Grafana which is head and shoulders above any open source or commmercial solutions
