### ISSUE TITLE
Strange behavior: API Gateway is serving a binary

### ISSUE THREAD

**Issue by franciscocpg** [apex/up#256]
## Up version
0.1.10

## Description
I'm trying to run this project (https://github.com/franciscocpg/react-semantic.ui-starter/tree/up-deploy, **important to use branch `up-deploy` here**) with up, but it's generating a strange binary at https://gdwoyj0la9.execute-api.us-east-1.amazonaws.com/development/.

I've tried to reproduce this problem locally in two ways but I couldn't.
### First way
- I've cloned `up` and checkout it to tag `v0.1.10` and cloned the project that I mentioned above. 
- I `cd` to the project `react-semantic.ui-starter` folder and checkout the branch `up-deploy`.
- Then I ran `go run $GOPATH/src/github.com/apex/up/cmd/up-proxy/main.go` inside the project `react-semantic.ui-starter` folder and accessed http://localhost:${PORT} in a browser successfully.

### Second way
- I've cloned `up` and checkout it to tag `v0.1.10` and cloned the project that I mentioned above. 
- I've changed `zip.go` and added a line after `zip.Close()` to write the zip file to a temp folder (`ioutil.WriteFile("/tmp/test.zip", buf.Bytes(), 0644)`)
- I `cd` to the project `react-semantic.ui-starter` folder and checkout the branch `up-deploy`.
- I ran `go run $GOPATH/src/github.com/apex/up/cmd/up/main.go` to generate `/tmp/test.zip` (After generating the file I've cancelled the deploy). 
- Then I unzip the generated file, ran `./main` and accessed http://localhost:${PORT} in a browser successfully.

By sucessfully I mean this [page](https://semantic-ui-test-chico.wedeploy.io/) is loading correctly in the browser (I was expecting https://gdwoyj0la9.execute-api.us-east-1.amazonaws.com/development/ to load this page too).

So it looks like `up-proxy` is working and I have no idea why API gateway is serving this binary.
Any thoughts on that?

**Comment by tj** [comment]
hmm I'll take a look!

**Comment by tj** [comment]
hmm it's been building for ~6m hahaha, if we can reproduce it with something smaller that'd be aweome

**Comment by franciscocpg** [comment]
> hmm it's been building for ~6m hahaha

A loooottt of dependencies. First time build is slow.  :turtle: 
Here is my hack. I ran `npm i && DIST_PATH=./dist/client/en npm run build && rm -rf node_modules && npm i --production` just once and then I change `up.json` like this:
```json
{
  "name": "react-semantic-ui-starter",
  "hooks": {
    "build": "exit 0"
  }
}
```

>  I wonder if Node is compressing AND my proxy is compressing

But if this is happening, shouldn't my second approach reproduce the problem? :thinking: 

Now that you mentioned, I'm going to try to reproduce using node v6.10.

**Comment by tj** [comment]
closing for now, can't spend too much time with huge codebases but if you can reproduce let me know, using 8.x might help https://github.com/apex/up-examples/tree/master/oss/node-8
