### ISSUE TITLE
Add env var to save .zip build to /tmp for debugging

### ISSUE THREAD

**Issue by tj** [apex/up#257]
I don't really want an `up build > out.zip` command since zips are very Lambda specific, but having something would be nice.

**Comment by stephenmathieson** [comment]
I spent a bit and tried to solve this in a somewhat clean way, but ended up adding an arg to `platform.Build()`, which also resulted in touching `internal/cli/run`. Touching two packages to do `io.Copy(p.zip, tmpZip)` seems wrong, so I'm assuming someone has a better idea in mind.

Any suggestions as to how you expected this to be handled would be appreciated, as I'd be happy to contribute (this is a feature which would help me quite a bit!!)

**Comment by tj** [comment]
hmm I suppose it's really not ideal to deploy just to inspect a zip, maybe having platform specific commands like `up lambda build > out.zip` (or `up lambda build` == out.zip when !isatty()) would be a better option? 

We could always do a type assertion instead of making assumptions about builds in the `Platform` interface. Maybe `Zip() (io.Reader, error)` has most of the current logic, and `Build() error` writes that into `p.zip`?

**Comment by tj** [comment]
Actually passing a var down to `Build()` could be ok, and `up --debug`? or maybe `up -v` automatically triggers it to produce the zip. hmmm

**Comment by franciscocpg** [comment]
I think `up --debug` would be a better option. Using a verbose flag to generate a zip file looks a little odd.

**Comment by tj** [comment]
@franciscocpg cool thanks yeah I'm down with a --debug flag. I'll add something today and get that in the next release with your region config stuff as well
