### ISSUE TITLE
mruby support

### ISSUE THREAD

**Issue by luisbebop** [apex/up#258]
First of all, this is really an awesome project. Congratulations.

I'd like to add support to mruby. Afaik I need to change `config.go` to add support for a new platform and create a docker container to generate the binary runtime for lambda.

Could you open the `tjholowaychuk/up-crystal` docker file in a way the community could implement new languages?

Thanks in advance.

**Comment by tj** [comment]
Thanks! I'm actually not sure where I put that Dockerfile, but so long as we can output a binary the implementation isn't too important.

I briefly looked at adding regular Ruby support, but I had some trouble getting the gems to be placed in such a way that it could find them. That might be the more awkward part, but happy to help if I can!

**Comment by stephenmathieson** [comment]
Leaving this here in the extremely unlikely chance you haven't seen it: https://aws.amazon.com/blogs/compute/scripting-languages-for-aws-lambda-running-php-ruby-and-go/

With it, I was able to setup a (mostly) functional fn for testing analytics-ruby, so I assume Up could do the same

**Comment by luisbebop** [comment]
@tj what is the spec of the binary? I mean the input/output, binary name, exit codes and so on. Would be great if you can give me a brief guidance about how to implement a new runtime from scratch.

I'm thinking about two approaches. 

The first one is using `mruby` that can output a binary with embedded gems like crystal lang: https://github.com/mruby/mruby

The second is using full `ruby` with `Sinatra` gem, for example: https://github.com/sheakelly/serverless-ruby-sinatra-example

For full `ruby`, the easiest approach would be `traveling ruby`: http://phusion.github.io/traveling-ruby

As you already did the tooling and lambda/gateway management runtime agnostic, I think couldn't be that hard to implement `mruby` and `ruby`.

**Comment by tj** [comment]
@luisbebop I'll try and doc soon, but basically by default it expects an executable named `./server` to run on `PORT`, that's about it. Currently it's not very modular, they're just little [config tweaks](https://github.com/apex/up/blob/master/config.go#L302) inferred from the files present.

Outputting a single binary with the gems would be awesome! If there's no real downside to that performance-wise that sounds great to me. 

We could later have `"runtime": "mruby"` if both end up being supported.

**Comment by sudhirj** [comment]
Won't this work just fine if there's a bash script called ./server that just started a regular server? Doesn't up already zip up the folder and deploy the whole thing? If yes, then the only thing left would be to vendor the gems during a bundle install.

**Comment by tj** [comment]
@sudhirj yep that sounds like it should be fine, if the gems can be safely symlinked that should be plenty fast enough too I hope

**Comment by sudhirj** [comment]
Yeah, just doing `bundle install --deployment` prepares the current folder to run a deployed zip without any further ado. Think that's what Heroku does as well, when they make the slug zips that they deploy. 

Put another way, `up` could theoretically support deploying the output of any Heroku buildpack, assuming it was built in the [correct environment](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) and had the `web` section of the Procfile running as just `./server`

**Comment by sudhirj** [comment]
If up were to parse procfiles and use the `web` section command, then it's actually possible to just assert that up can run the output of any Heroku buildpack and piggyback on that ecosystem. The PORT requirement is already in play there.

**Comment by tj** [comment]
sweet yea that would be great, I'll have to read up more on what they're doing I'm vaguely familiar with the buildpacks but I don't know if it'd be hard to run them in Lambda or not

**Comment by luisbebop** [comment]
Using `Traveling ruby` is possible to deploy `ruby` applications without changing anything on `Up`.

Check it out:
https://github.com/luisbebop/sinatra-up-demo

**Comment by luisbebop** [comment]
`Mruby` up and running on `Up`

 https://github.com/luisbebop/mruby-app-up

Got 22k req/s with this little app :)

AWESOME

**Comment by tj** [comment]
Niceeee :D
