### ISSUE TITLE
Error when stage name is incorrect

### ISSUE THREAD

**Issue by lukeed** [apex/up#261]
Running `up url copy` results in `https://..../copy/`

I know the command is a mistake, but probably should be disregarded instead of appended to the output.

Version: `v0.1.10`

**Comment by stephenmathieson** [comment]
Friendly errors make for the best UX, no matter how much of a weird edge case the user has found

**Comment by tj** [comment]
hahah oops yeah I should probably fetch the list of stages instead of blindly adding it

**Comment by lukeed** [comment]
Another instance: `up build` is treated as a staging name, ergo runs ~~> `up deploy build`

**Comment by tj** [comment]
```
  Error: deploying: us-west-2: "build" is invalid, must be one of:

  • development
  • staging
  • production
```
