### ISSUE TITLE
Expose execution time remaining to invocations

### ISSUE THREAD

**Issue by mojodna** [apex/up#262]
I have a Python server / function that doesn't behave well when thawed after timing out (it's an underlying C library problem and processing continues after the Lambda function is resumed). As a workaround for that, I set a timeout to kill the process just before Lambda would have timed it out (so that Lambda will restart it automatically).

Within `up`, I see 2 ways of achieving the same thing: 1) pass `get_remaining_time_in_millis()` (its equivalent, really) as an `X-header`; 2) expand the proxy retry behavior to kill the target server after a timeout (vs. the server knowing to stop itself).

**Comment by tj** [comment]
oOo weird, I'm not sure that's something Up should be concerned about, I haven't hit any issues like that. What does the C lib do which interacts poorly?

**Comment by mojodna** [comment]
It's [GDAL](http://gdal.org), which I'm using to reproject imagery. I give GDAL a URL and information about what to do with the image(s) and it goes off and does its own thing (using its own thread pool). There's no way to cancel pending operations (node-mapnik has the same problem), so when Lambda times the function out and freezes the process, it resumes execution when thawed, using up some of the available CPU for something that will never be used.

(1) seems like the cleanest option for Up; I can see a benefit to knowing how much time is left on the clock (similar to the amount of available memory) and leave the app to do what it will with that information.

**Comment by tj** [comment]
Interesting thanks for the details. If we pass `X-*` that wouldn't be any different really than your app just starting the timer to kill no? Since the Go reverse proxy itself really only introduces say 1-5ms at worst, I guess I'm not sure it's worth passing a field.

**Comment by mojodna** [comment]
The app doesn't know what the timeout in the Lambda configuration is, so the timer needs to be separately configured; the Node shim does (in the form of `context`).

(Oddly, needing to work around this and take Lambda implementation details into account is making me wish for Apex's function deployment (w/o the proxy) combined with Up's CloudFormation, etc. management (which are fantastic, thank you!).)

**Comment by tj** [comment]
Haha yeah I'm tempted to combine them at some point, especially if Up can be sustainable, probably won't worry about it otherwise. Sounds like passing `X-Lambda-{Timeout,Memory}` (or maybe JSON etc) would do the trick?

**Comment by mojodna** [comment]
Yup, that'd definitely work.

**Comment by tj** [comment]
closing this one for now, fargate will mitigate this issue for longer running requests
