### ISSUE TITLE
Default profile to "default"

### ISSUE THREAD

**Issue by tj** [apex/up#265]
Really not a fan of "default" in ~/.aws, it has no meaning (what is the project? is it production or dev account?) but some people may expect this. At very least document setting up your aws config.

**Comment by stephenmathieson** [comment]
My work machine came provisioned with my "default" AWS profile having admin writes over just about everything (not good, I know)... accidentally using this profile for some personal project could potentially cost me my job, which to say the least, wouldn't be great.

TLDR I'm 👎 with defaulting to "default"

**Comment by tj** [comment]
oh shit hahaha, that settles it :D
