### ISSUE TITLE
CORS headers are not added to Error Responses 

### ISSUE THREAD

**Issue by hhsnopek** [apex/up#274]
CORS headers are not added to `Status 502, { "message": "Endpoint timed out" }`/`Status 504, {  "message": "Internal server error" }` when explicitly enabled in `up.json`.

**Comment by tj** [comment]
oh damn, didn't think of that case, maybe we'll have to use the API GW CORS support instead of in-proxy

**Comment by tj** [comment]
closing this one, I think if we can nail down the http proxy timeouts then we'll have full control over the responses (and CORS here) so it's a different issue
