### ISSUE TITLE
Support for eu-west-2 region

### ISSUE THREAD

**Issue by colinf** [apex/up#280]
Docs say eu-west-2 region (London) is supported but it is not accepted as a valid region when using Up

**Comment by hawkrives** [comment]
Is it as simple as adding `"eu-west-2"` to this list?

https://github.com/apex/up/blob/dd304018e28bb4462fe9acf1f6cff63813429d80/platform/lambda/regions/regions.go#L5-L20

**Comment by tj** [comment]
Hmm eu-west-2 may not support Lambda yet, but if it does we can add it to the list!

**Comment by colinf** [comment]
Thanks both. I have used Lambda in eu-west-2 - so I think it's safe to add to the list
