### ISSUE TITLE
add env vars to `up start`

### ISSUE THREAD

**Issue by colinf** [apex/up#290]
I am using JavaScript and finding that custom environment variables in the up.json "environment" property are not being made available. I have tried the [node-env](https://github.com/apex/up-examples/tree/master/oss/node-env) example app "node-env" but it doesn't seem to populate the environment variables either.

Cheers,
  Colin

**Comment by tj** [comment]
hmm the example seems ok, I just deployed with v0.2.1 and got:

```
{
"UP_BAR": "bar",
"UP_FOO": "foo",
"UP_RESTARTS": "0"
}
```

keep in mind that example only displays env vars with `UP_*`, I'll tweak that a bit

**Comment by tj** [comment]
tweaked to be more explicit about which are included in the response. Let me know if it's still an issue and I'll re-open! 

cheers

**Comment by colinf** [comment]
Thanks for investigating.

I was having a problem around an environment variable and used the node-env example as a reference - but I ran the example locally using the **up start** command rather than deploying. Now that I think about it it kind of makes sense that the environment variables are not available when running locally.

Maybe it would be good to add a clarification comment in the docs about environment variables and up start to avoid other time wasters like me! I can add something to the docs and submit as a pull request if you want. Just let me know by reply if you want me to.

**Comment by tj** [comment]
ahhh I'll reopen, I forgot about `up start`
