### ISSUE TITLE
404 For Error Message Link

### ISSUE THREAD

**Issue by ianrtracey** [apex/up#297]
`Error: Cannot find credentials, visit https://github.com/apex/up/blob/master/docs/aws-credentials.md for help.`

When navigating to https://github.com/apex/up/blob/master/docs/aws-credentials.md I get a 404.

**Comment by orteth01** [comment]
@ianrtracey there's an open PR to fix that error message https://github.com/apex/up/pull/295

 anyway, here's that section of the docs. https://apex.github.io/up/#aws_credentials

**Comment by tj** [comment]
fixed!

**Comment by ianrtracey** [comment]
👍
