### ISSUE TITLE
Apex vs. Up difference

### ISSUE THREAD

**Issue by anonrig** [apex/up#298]
Hello,

As I was investigating on using the right framework/library for serverless architecture on top of AWS, I was curious about the difference between github.com/apex/apex and Up.

Can anybody enlighten me on this manner?

Best,
Y

**Comment by tj** [comment]
check out the [FAQ](https://apex.github.io/up/#faq) but if you have more questions feel free to ask here!

TL;DR is Up is for applications & APIs (not coupled to Lambda), while apex is for functions (more traditional Lambda).
