### ISSUE TITLE
Error when using an array for `hooks.build` in `up.json`

### ISSUE THREAD

**Issue by orteth01** [apex/up#302]
In the configuration docs it says that you can use an array for `hooks.build` in `up.json` like so
```
"hooks": {
    "build": [
         "mkdir -p build",
         "cp -fr static build",
         "browserify --node index.js > build/client.js"
    ]
}
```

However, when i try this i get the following error:
```
Error: initializing: reading config: parsing json: json: cannot unmarshal array into Go struct field Hooks.build of type string
```

my up version is 0.2.1

**Comment by tj** [comment]
ahh sorry I think it's in the next release, got a little ahead of myself updating the docs. I'll do a minor release in the next day or two with the new stuff
