### ISSUE TITLE
redirects command and single page apps

### ISSUE THREAD

**Issue by colinf** [apex/up#304]
I'm using the redirects command as per the node-spa example and the docs, to try to serve the index.html file regardless of the path. But the redirects command seems to change to Content-Type to text/plain.

To reproduce, deploy the node-spa example and then navigate to a different path e.g. /hello and I get HTML markup displayed in the browser.

**Comment by tj** [comment]
thanks for the report! I'll check this out today

**Comment by tj** [comment]
v0.2.3 fixes this with a hack for now. Turns out that Go doesn't use the file's extension or magic number to determine the content-type, for some reason it relies on the request path including `.html`

**Comment by colinf** [comment]
Thanks for your quick response!
