### ISSUE TITLE
Add `stages` config with higher prededence

### ISSUE THREAD

**Issue by tj** [apex/up#314]
Basically a mirror of `Config`, so you can override anything at the stage level. Particularly useful for `regions`, `hooks`, and potentially even `profile` if you'd like a separate account for staging.

**Comment by kaihendry** [comment]
Oh, I need this since https://static.spuul.com/devops/2017-11-14/up.json doesn't work. :cry: 

Guess the workaround is to symlink in my up.json, `ln -s up.stage.json up.json`?

**Comment by tj** [comment]
Ahh yea I definitely want what you have there to work. In the meantime maybe a `--config up.stage.json` or similar would be a reasonable option

**Comment by kaihendry** [comment]
Oh, just realised `Error: unknown long flag '--config'`. But serious what you proposed here in https://github.com/apex/up/issues/484#issuecomment-352944698 is what I desperately need.

**Comment by tj** [comment]
Sounds good, I'll try and get this in soon, should be pretty straight-forward

**Comment by kaihendry** [comment]
Argh, I should have moved my CI to use `--config` sooner.

Had a breakage and the error was `FATA error reading config: open up.json: no such file or directory`. Guess up didn't like my symlink!

**Comment by tj** [comment]
Yeah I'd rather keep it in one file I think, I'll look into the per-stage config today, needs a bit of a refactor to prevent cyclic references

**Comment by tj** [comment]
Hmm just realized it doens't make much sense to swap out `profile` since `up plan / apply` do not take a stage, that gets a bit awkward without a cross-account cloudformation setup.
