### ISSUE TITLE
Using Up on Windows makes unusable deployments because of file permissions

### ISSUE THREAD

**Issue by hyperparsa** [apex/up#316]
I spent 5 hours trying to find the issue T_T

Building on windows creates a .zip file which has a restricted file permission for modules inside node_modules. This results in `Error: Cannot find module` when deployed on Lambda. 
I found a simple workaround which is to install Up in [WSL](https://blogs.msdn.microsoft.com/wsl) and then running up from there.
This issue isn't really for Up but it is possible to fix it by adding some check for windows [here](https://github.com/apex/up/tree/master/internal/zip) 

Here's the built zips from both Up on windows and Up on WSL, check the attributes:
![image](https://user-images.githubusercontent.com/5086419/30247628-45917296-964b-11e7-923e-edabea599e52.png)

Up version : `0.2.3`

**Comment by hyperparsa** [comment]
FML I just found this issue:   #225

It's not fixed though so not gonna close

**Comment by tj** [comment]
Ahh damn, I guess we might as well apply that permission change to all the files, strange that Windows decides to leave out exec, must have a different meaning for dirs

**Comment by hyperparsa** [comment]
That'd be good , Thanks!

**Comment by tj** [comment]
actually maybe it's only the index.js hmm, that error is a little vague

**Comment by tj** [comment]
Haven't heard any issues after the last fix, re-open if you hit any issues on Windows

**Comment by rixrix** [comment]
Hi,

I'm getting this error "Cannot find module", I was previously running the deployment on WSL. Switched to `Git Bash` today and my deployment started crapping out. let me know if you need more details. thanks

My config:
- up version: 0.3.0
- windows 10 insider preview
- deploy status is complete

up logs -f
```
10:39:34pm ERRO module.js:471                                                                                                  
  throw err;                                                                                                                   
  ^                                                                                                                            
10:39:35pm ERRO Error: Cannot find module '/var/task/app.js'                                                                   
  at Function.Module._resolveFilename (module.js:469:15)                                                                       
  at Function.Module._load (module.js:417:25)                                                                                  
  at Module.runMain (module.js:604:10)                                                                                         
  at run (bootstrap_node.js:390:7)                                                                                             
  at startup (bootstrap_node.js:150:9)                                                                                         
  at bootstrap_node.js:505:3                                                                                                   
10:39:59pm FATA error: initializing relay: waiting for http://127.0.0.1:34231 to be in listening state: timed out after 25s    
12:00:00pm INFO 2017-10-22T09:39:59.669Z      e956a6ea-b70c-11e7-9ba4-81bb0a5aace5    Error: read ECONNRESET                   
  at exports._errnoException (util.js:1018:11)                                                                                 
  at Pipe.onread (net.js:568:26)                                                                                               
```

**Comment by rixrix** [comment]
quick update:
re-deployed the app via WSL, on up v0.3.0 and it worked fine. FYI

**Comment by mulyoved** [comment]
Still, has this problem with up v0.3.0 and git-bash, please consider reopen issue

**Comment by tj** [comment]
Damn, was hoping that would fix it.

**Comment by tj** [comment]
https://github.com/apex/up/releases/tag/v0.3.3

**Comment by codebravotech** [comment]
@tj Hey buddy- I'm getting the same issue `Error: Cannot find module '/var/task/app.js'` building and deploying on Mohave 10.14.6. Seems to be something broken on the zip file
