### ISSUE TITLE
Delete older versions of AWS lambdas & S3 objects

### ISSUE THREAD

**Issue by a-golovanov** [apex/up#322]
AWS lambda service has limit: "Total size of all the deployment packages that can be uploaded per region | 75 GB" (http://docs.aws.amazon.com/lambda/latest/dg/limits.html)
Since lambdas are managed by `up` it would be nice if `up` would have an option (or maybe default behavior) to remove obsolete versions.

**Comment by tj** [comment]
👍 agreed. Up may switch to S3 for multi-part uploads, but in either case we'd need to have some kind of cleanup
