### ISSUE TITLE
Stack refactoring

### ISSUE THREAD

**Issue by tj** [apex/up#325]
Quite a few small things but some notable ones:

- [x] remove `certs`, it's implied now via `.stages`
- [x] base path mapping
- [ ] refactor to remove more params, changes in params makes it difficult to work with existing stacks
- [ ] nicer log messages when email confirmation etc
- [ ] error output for stack failures (currently you have to `up stack` to see the state)
- [ ] ^ doesn't show events from rollbacks
- [ ] display as table? better coloring etc
- [ ] make it obvious that CF takes a while to distribute the cert(s)

**Comment by holic** [comment]
When fiddling with the new domain stuff, I noticed that `up stack plan` errored out if I didn't call `up` at least once before:
```
Error: fetching production alias: ResourceNotFoundException: Cannot find alias arn: ...
```
Seems like `up` does some bootstrapping that `up stack` expects?

**Comment by tj** [comment]
Ahh yep you do definitely need to `up` first, but I'll add a nicer error for that, thanks for pointing it out!

**Comment by rixrix** [comment]
thanks for building this tool. tried this scenario today, doing `up` does the fixed the issue. looking forward for the fix. thanks

**Comment by tj** [comment]
closing, will make granular issues as needed
