### ISSUE TITLE
Custom stages

### ISSUE THREAD

**Issue by mgoodings** [apex/up#326]
Could we have overrides for the definitions of stages?

We have much more loosely defined stages in each of our accounts than just development, staging, production.

I'd like to have a list of definable stage names.

**Comment by tj** [comment]
Yep definitely at some point, it's a bit more tricky to support arbitrary ones so I'm working with the main three for now but I'd definitely like to have this.

**Comment by komuw** [comment]
feedback: This would be awesome. We have a staging environment per every feature that is been worked on.

**Comment by tj** [comment]
@komuw noted! I'll check this out soon

**Comment by kaihendry** [comment]
Would be good to override *development* as the primary stage when running `up` to be production say.

At work we toggle stages via AWS account numbers via AWS_PROFILEs.
