### ISSUE TITLE
Installation fails outright on macOS

### ISSUE THREAD

**Issue by yunyu** [apex/up#330]
## Prerequisites

* [N/A] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [N/A] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

Installing from npm or curl|bash the script fails with a 404.

![](https://i.imgur.com/9QEQEC6.png)
![](https://i.imgur.com/JwU80c1.png)

From the looks of it, the file downloads successfully but the checksum fails.

## Steps to Reproduce

Try installing up if it isn't already  installed with any method involving that script. It ends up 404ing.

## Love Up?

Please consider donating https://opencollective.com/apex-up/donate to help the project.

Just have a general question? Join us on Slack https://apex-dev.azurewebsites.net/

**Comment by quocnguyen** [comment]
This is a workaround in case you can't wait.

```
curl -sfL https://gist.githubusercontent.com/quocnguyen/4fdb93be6049f2311c7be6d2eaf90238/raw/7b85022f0ac5ff5fa72b7a0b8d21e955396ff4c7/install.sh | sh
```
