### ISSUE TITLE
`up logs -f` just waits

### ISSUE THREAD

**Issue by kaihendry** [apex/up#333]
## Description

`up logs -f` just gets stuck

## Steps to Reproduce

Run `up logs -f` on a deployed project.

`up logs` works fine. With the `-v` switch is just exits?

```
~/go/src/github.com/kaihendry/count$ up logs -v -f
     8ms     DEBU up version 0.2.4
     0s      DEBU region from aws shared config "ap-southeast-1"
   ⠋ 0s      DEBU track "Logs" map[version:0.2.4 query:false query_leng     0s      DEBU track "Logs" map[version:0.2.4 query:false query_length:0 follow:true
since:0s os:linux arch:amd64]
     0s      DEBU query ""
     0s      DEBU follow
     0s      DEBU enter group=/aws/lambda/count
     170ms   DEBU request group=/aws/lambda/count start=1505699770182
~/go/src/github.com/kaihendry/count$
```

**Comment by kaihendry** [comment]
Weird thing is that sometimes it works, but often it doesn't I guess it's a CloudWatch problem, since the query look right. *sigh*

**Comment by tj** [comment]
hmm CloudWatch logs does have a pretty bad delay (~5s) but LMK if there's anything you think is busted or confusing with the query language and I can check it out!
