### ISSUE TITLE
[Node] filter out dev-dependencies from build archive

### ISSUE THREAD

**Issue by louisremi** [apex/up#336]
I've been trying to use up as a replacement for Claudia.js, but I'm unable to deploy my project as my node_modules directory is huge, and up is trying to include all of it in the build archive. So I always get the error `exceeding Lambda's limit of 52 MB`.

I believe Claudia replaces the node_modules directory with the result of `npm install --only=prod` to remove unnecessary dev dependencies.

I wish up would do the same :-)

**Comment by stephenmathieson** [comment]
I use a bundler (usually `browserify --node`) to avoid adding unnecessary stuff to the deployed .zip. This not only avoids development dependencies, but things like README.md, unused files, pictures of Guy Fieri, etc.

**Comment by louisremi** [comment]
I use Webpack, but I have many dependencies which include binaries or use `require` dynamically, and cannot be bundled with my files.

**Comment by tj** [comment]
I think re-installing is too slow for a default personally, but a "build" hook with `npm install --only=prod` should do the trick!

**Comment by louisremi** [comment]
Re-installing dev-dependencies after that is waaaaay slower. So that means I shouldn't `up` locally, only on CI, and only as the very last step of my CI script...
This isn't ideal I would say. The fact that Claudia.js solved that for me out of the box and that I never even had to think about it was very convenient :-)

**Comment by louisremi** [comment]
I found a solution:
```js
// in up.json
"hooks": {
    "build": [
      "webpack --config webpack.config.js",
      "mv node_modules .node_modules",
      "npm install --only=prod"
    ],
    "clean": "[ -d .node_modules ] && rm -rf node_modules && mv .node_modules node_modules"
  }
```
```
# in .upignore
.node_modules
```
Would a PR adding this config to https://github.com/apex/up-examples/tree/master/oss/node-express-browserify be acceptable? I'd also like to add a `node-express-webpack` example.

**Comment by tj** [comment]
Closing for now. I'm open to suggestions, but it's a little tricky when there isn't a one-size-fits-all solution for Node stuff. It's definitely faster to avoid `npm install`ing each time if you can
