### ISSUE TITLE
Dangerous suggestion in documentation

### ISSUE THREAD

**Issue by nickgrim** [apex/up#337]
(Disclaimer: I haven't actually installed `up`)

`up/docs/01-installation.md` suggests:

> If you hit permission issues, you may need to run the following, as `up` is installed to `/usr/local/bin/up` by default.
> ```
> $ sudo chown -R $(whoami) /usr/local/

This is **not** safe in the general case.

There could well be SUID-binaries under `/usr/local` (some versions of Solaris keep `sudo` under that hierarchy!), or binaries deliberately owned by other users. MySQL by default installs some files under `/usr/local`. Changing everything under that directory to be owned by the current user will likely make other-users and/or your package manager quite angry.

At the *very* least, that above line should end `/usr/local/bin` (thus avoiding `/usr/local/sbin` and other subdirectories of `/usr/local`), but ideally some proper way should be found to solve that without changing the permissions of a lot of unrelated files/directories.

**Comment by tj** [comment]
Switching to /usr/local/bin at least sounds good to me! On a Mac this is pretty common, I've never had issues with existing programs, but I guess I don't install Postgres/mysql etc either, just via Docker these days. Thanks!
