### ISSUE TITLE
Proxy request timeouts

### ISSUE THREAD

**Issue by tj** [apex/up#338]
- [x] remove `.lambda.timeout` option (use below, lambda's can be implied)
- [ ] document `.proxy.timeout` option 
- [ ] apply timeout to in-flight requests
- [ ] test for in-flight timeout
- [ ] test for retry timeout

If there's a previous 5xx response and an in-flight times, just respond with that.

**Comment by berryhill** [comment]
Cool if I hop on this one?

**Comment by tj** [comment]
@berryhill sure!

**Comment by berryhill** [comment]
@tj Hell yeah dope! Stoked to contribute.

I believe I sent a request to get into the slack (matthewberryhill@gmail.com). Running into a couple issues upping the project but am able to build with the make file.. tests hang on the relay stuff so gonna need to sort that out as well. Figure slack would a good place for guidance on the above if I seem to not be able to crack it here.

**Comment by tj** [comment]
LMK if you have an issues there, I can tweak the contrib markdown if I missed anything

**Comment by berryhill** [comment]
Ok dope, gonna bring up some findings here in slack and then we can get it dialed from there.

**Comment by jpillora** [comment]
Should have checked here sooner >.< I had `.lambda.timeout` set but not `.proxy.timeout`, was puzzling about this for way too long.

**Comment by tj** [comment]
921e818
