### ISSUE TITLE
AWS ECS platform integration

### ISSUE THREAD

**Issue by tj** [apex/up#339]
Probably a post-1.0, but this will likely be the next combo, since we can re-use most of the Lambda stuff for querying the logs, cloudformation etc. Should be pretty trivial.

**Comment by skabbes** [comment]
This will probably require a concurrency refactor in the proxy, and I presume you'll just ditch the shim for this one?

**Comment by tj** [comment]
Yep no need for a shim there, but yea that lock will have to ... Go :D

**Comment by sudhirj** [comment]
Need to make sure the Go proxy features being offered are also viable in ALB+ECS, otherwise it's going to be confusing if we need different up.json files for different deployment stacks. Or maybe that's okay, I'd be happy with up.lambda.json and up.ecs.json

**Comment by luisbebop** [comment]
You can use docker even without `ECS`:

https://github.com/grycap/scar

**Comment by kaihendry** [comment]
imo ECS & docker is a rabbit hole of complexity. I'd rather have you focused on the lambda/container platform.

**Comment by tj** [comment]
I didn't find ECS too bad, we used it heavily in production at Segment with hundreds of nodes. For high through-put it's muchhhh more cost effective, but it's definitely not a priority for now. I prefer the Lambda stuff too for most cases.

**Comment by tj** [comment]
closing since Fargate is a nicer option now, though it should be super trivial to support both
