### ISSUE TITLE
Slack website is down

### ISSUE THREAD

**Issue by aknuds1** [apex/up#344]
I'm trying to join the [Apex Slack workspace](https://apex-dev.azurewebsites.net/), but I get the message that the website is down ("403 - This web app is stopped").

**Comment by tj** [comment]
Ah bummer I'll fix that soon. I heard something about Slack having official invite page support or something too, need to look into it :D

**Comment by aknuds1** [comment]
Great!! 🙂

**Comment by aknuds1** [comment]
Up seems great so far btw, just started using it!

**Comment by tj** [comment]
https://apex-slackin.herokuapp.com/ should work!

**Comment by aknuds1** [comment]
Great, works perfectly! Thank you!

**Comment by stephenmathieson** [comment]
i figured you'd dogfood up and host slackin with it :P

**Comment by tj** [comment]
too lazy to chance it with node apps haha, who knows it if it builds correctly

**Comment by yunyu** [comment]
This is also down:

![](https://i.imgur.com/29DYftN.png)
