### ISSUE TITLE
Installation issue (404) - with potential fix

### ISSUE THREAD

**Issue by remy** [apex/up#345]
## Prerequisites

* [na] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [na] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

Trying to install on Yosemite (yes, I know it's old!), up fails to install due to corrupted download URL.

## Steps to Reproduce

 I get this with both the `npm i -g up` and the `curl` command:

```bash
❯ curl -sfL https://raw.githubusercontent.com/apex/up/master/install.sh | sh
apex/up: checking GitHub for latest version
apex/up: found version https://api.github.com/repos/apex/up/releases/7833449 for darwin/amd64
apex/up: downloading https://github.com/apex/up/releases/download/vhttps://api.github.com/repos/apex/up/releases/7833449/up_https://api.github.com/repos/apex/up/releases/7833449_darwin_amd64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
```

I managed to fix this myself by downloading the `install.sh` script and adding `tr` to ensure the JSON was multi-lined:

```bash
github_last_release() {
  owner_repo=$1
  giturl="https://api.github.com/repos/${owner_repo}/releases/latest"
  html=$(github_api - "$giturl")
  version=$(echo "$html" | tr ',' '\n' | grep -m 1 "\"tag_name\":" | cut -f4 -d'"')
  test -z "$version" && return 1
  echo "$version"
}
```

I'd be happy to post a PR for the fix, but I wasn't sure what the impact would be on newer machines (I doubt if anything, but I wanted to check first).

**Comment by tj** [comment]
ahh interesting hmm maybe open an issue in https://github.com/goreleaser/godownloader. It would be fine to patch it here for now as well, but I don't want to deviate too much from godownloader in case we generate install.sh again
