### ISSUE TITLE
Add Java support to README

### ISSUE THREAD

**Issue by franciscocpg** [apex/up#346]
## Prerequisites

* [n/a] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [n/a] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

I have a Java service that I want to migrate to `up` but README states the following:
`Up currently supports Node.js, Golang, Python, Crystal, and static sites out of the box`.

I thought: "that's strange because AWS Lambda supports Java natively" then I have decided to take a look at [OSS examples](https://github.com/apex/up-examples/tree/master/oss). After that I realized that Java is supported too because there is some java examples.

I think it's very important to update this language supports information because if one is considering using `up` with Java and take a quick look at README he's going to have the false impression that `up` does not support Java. And I don't think that everyone is going to have an insight: "Oh, let me take a look at examples" :smiley: 

If you think that makes sense I can propose a PR for that.

**Comment by tj** [comment]
agreed!
