### ISSUE TITLE
Up type: "static" builds current dir

### ISSUE THREAD

**Issue by AbeEstrada** [apex/up#347]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

When building a static site `up` doesn't read `dir` from the config file and builds de current directory.

## Steps to Reproduce

- Clone https://github.com/apex/up-examples/tree/master/oss/static-dir
- `up build`
- Inspect `out.zip` and the `super-secret.txt` file is there

**Comment by tj** [comment]
ahh yea it just tells where to serve from, but doesn't omit other files. I'll add a note about that (may change)

**Comment by AbeEstrada** [comment]
I resolved this issues using `.upignore`

```
*
!public/**
```
