### ISSUE TITLE
Structured Logging info for Golang

### ISSUE THREAD

**Issue by kaihendry** [apex/up#348]
## Description

https://github.com/apex/up/blob/master/docs/07-guides.md#json

I'm assuming with a [construct like](https://github.com/apex/up-examples/blob/master/oss/golang-form/main.go#L43):

    log.WithFields(log.Fields{"name": name}).Info("heyy")

I can filter for info of that event like so:

     up logs 'message = "heyy"'

But it doesn't appear to work. In the CloudWatch logs themselves, I see it logged like so:

```
{
    "fields": {
        "app": true
    },
    "level": "info",
    "timestamp": "2017-09-27T05:20:40.381079932Z",
    "message": "timestamp=2017-09-27T05:20:30.97406088Z level=info message=heyy name=test"
}
```

## Steps to Reproduce

1. curl -O https://s.natalian.org/2017-09-27/main.go
2. up
2. curl -X POST --data-urlencode "name=yay" $(up url)

**Comment by kaihendry** [comment]
Just discovered using the JSON handler seems to fix it `log.SetHandler(json.New(os.Stderr))`!

Shouldn't:

* https://github.com/apex/up-examples/blob/master/oss/golang-form/main.go
* https://github.com/apex/up-examples/blob/master/oss/golang-uploads/main.go#L22

Be updated?

**Comment by kaihendry** [comment]
I was half expecting to be able to also query by path / ip /status etc. But I noticed such queries don't work, since they are logged independently?

e.g. `up logs 'message = "heyy" ip="202.*"'`

**Comment by kaihendry** [comment]
Be good to have some examples for how to log internally. For example I can see an error 400 like in the logs:

     http.Error(w, "Empty body", 400)
     return

But how do I also log extra context like the "Empty body", so I can see that was the cause of the error?

**Comment by tj** [comment]
For the ` http.Error(w, "Empty body", 400)` case you'd usually have a `log.WithError(err).Error(...)` above that since (typically) the "real" error isn't exposed to the client.

I'll update those older examples that use the logfmt handler, forgot about that. Adding the other contextual fields sounds good to me too, I think that should be doable

**Comment by tj** [comment]
opening a new issue for the context

**Comment by kaihendry** [comment]
Thanks for updating the examples https://github.com/apex/up-examples/commit/c5ee891525ed518a286cc20b030def9eb10336b5

However debug level doesn't appear to work.

```
diff --git a/oss/golang-api/main.go b/oss/golang-api/main.go
index edab49f..2e07077 100644
--- a/oss/golang-api/main.go
+++ b/oss/golang-api/main.go
@@ -26,6 +26,7 @@ func init() {
 
 // setup.
 func main() {
+	log.SetLevel(log.DebugLevel)
 	addr := ":" + os.Getenv("PORT")
 	app := pat.New()
 	app.Get("/", get)
@@ -39,6 +40,7 @@ func main() {
 // curl http://localhost:3000/
 func get(w http.ResponseWriter, r *http.Request) {
 	log.Info("list pets")
+	log.Debug("listing pets")
 
 	if len(pets) == 0 {
 		fmt.Fprintf(w, "no pets")

```

No results for `up logs | grep listing` or `up logs 'debug'` and furthermore:

```
$ up logs 'not info'
panic: log "/aws/lambda/golang-api-test": InvalidParameterException: Invalid character(s) in term '!('
        status code: 400, request id: a0e933c3-a417-11e7-8bbf-01211dc529aa

goroutine 52 [running]:
github.com/apex/up/platform/lambda.(*Logs).start(0xc42025acb0)
        /Users/tj/dev/src/github.com/apex/up/platform/lambda/logs.go:122 +0x798
created by github.com/apex/up/platform/lambda.NewLogs
        /Users/tj/dev/src/github.com/apex/up/platform/lambda/logs.go:57 +0x2a7

```

**Comment by tj** [comment]
@kaihendry ahhh my bad, I have the internal Up logger set to INFO so the DEBUG messages weren't showing. I'll look into why that has a syntax error too, that seems odd, pretty sure I have a test case for that scenario.

**Comment by tj** [comment]
damn that's messed up, I'm positive I tested negation but it seems like they only support `!=` now, wtf
