### ISSUE TITLE
Different environment variables per stage?

### ISSUE THREAD

**Issue by huangbong** [apex/up#353]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

Is there any way we can add environment variables per staging environment? For example, if I have something like `POSTGRES_URI` for my API lambda function, this environment variable will differ from `staging` to `production`. Right now the only way I can think of getting around this is duplicating variables to `POSTGRES_URI_STAGING` and `POSTGRES_URI_PROD` and then having my application logic check `UP_STAGE` to load the proper environment variable.

Not sure if this is a lambda limitation as well because it looks like you can only set environment variables for all stages in the AWS Lambda configuration page for a Lambda function.

Also, ETA on when secret support is coming out TJ? Take my money!

**Comment by huangbong** [comment]
Oh, I guess once secrets comes out it should be no problem.

`"GRAPHQL_URI": "@dash-staging-graphql-uri"`
`"GRAPHQL_URI": "@dash-prod-graphql-uri"`

**Comment by tj** [comment]
Yep it's coming! Just about finished, I'm on a little vacation but I should be able to set up billing and the Pro plan in the next few weeks. Once I get the env stuff in I'd be happy to provide "early access" for free as well, never hurts to battle test!

**Comment by mikenikles** [comment]
Great news! I was about to ask the same question. I'd be happy to provide feedback.

**Comment by kevinsimper** [comment]
I was looking for the same thing, maybe a solution would be to load different config files?

**Comment by huangbong** [comment]
For those that are still waiting for secrets, etc, I made a `preup.js` script to run before an up deploy to substitute variables in `up.json` (empty environment strings are substituted). For any production variables that you want to be different from staging, add the `_PROD` suffix.

up.json

```json
  "name": "react",
  "environment": {
    "NODE_ENV": "production",
    "API_URI": ""
  }
```

preup.js
```javascript
require('dotenv').config();
const fs = require('fs');
const upJson = require('./up.json');

const { environment } = upJson;

Object.keys(environment).forEach((key) => {
  if (!environment[key]) {
    environment[key] = process.env[key];
    if (process.env[`${key}_PROD`]) {
      environment[`${key}_PROD`] = process.env[`${key}_PROD`];
    }
  }
});

const result = JSON.stringify(upJson, null, 2);

fs.writeFileSync('./up.json', `${result}\n`);
```

loadEnv.js

```javascript
const loadEnv = (env) => {
  if (process.env.UP_STAGE === 'production') {
    if (process.env[`${env}_PROD`]) {
      return process.env[`${env}_PROD`];
    }
  }
  return process.env[env];
};

module.exports = loadEnv;
```

Then use `loadEnv` to load your env variables in your application code. For example: `uri: loadEnv('API_URI')`.

**Comment by tj** [comment]
forgot to close
