### ISSUE TITLE
r.RemoteAddr access

### ISSUE THREAD

**Issue by kaihendry** [apex/up#354]
I noticed from my Golang function that appears something like: 127.0.0.1:45560

Is there an easier way to get the real value? I know it's also in the first value of `X-Forwarded-For` header, but is that reliable?

**Comment by tj** [comment]
Yep `X-Forwarded-For` is the way to go. Sometimes frameworks ([Koa & Express for example](https://github.com/koajs/koa/blob/master/lib/request.js#L420-L439)) provide X-Forwarded-For's value as `req.ip`, I'm not sure if Go has something similar out of the box, I don't think so

**Comment by kaihendry** [comment]
As you can see from https://count.webconverger.com/ `e.g. X-Forwarded-For
: [202.83.104.44, 54.240.148.197]` I'm going to have to assume the client remote IP is the first I see. Seems kinda gnarly.

**Comment by tj** [comment]
It's normal with reverse proxies, basically just a trail of hops between them

**Comment by tj** [comment]
closing this one for now since it's pretty standard, little silly how these non-standard `x-` things always become standard slowly but hey hahah
