### ISSUE TITLE
up don't log full error in CloudWatch

### ISSUE THREAD

**Issue by hellorachid** [apex/up#357]
When i try to execute my function i get an error, and when i check CloudWatch logs i find this :  
```
{
    "fields": {
        "app": true
    },
    "level": "error",
    "timestamp": "2017-10-06T16:28:26.333197551Z",
    "message": "module.js:471\n    throw err;\n    ^"
}
```
which does not help in any way.
Please can  you include the full log in CloudWatch ?

**Comment by tj** [comment]
Seems ok to me in the [node-logging](https://github.com/apex/up-examples/tree/master/oss/node-logging) example. Could you provide some code for reproducing? Or does it seem random?

**Comment by tj** [comment]
re-open if you hit this issue with v0.2.10, made some logging improvements there, but the indented line stuff should have worked fine previously (hasn't changed)
