### ISSUE TITLE
Best approach to keep the container warm

### ISSUE THREAD

**Issue by hellorachid** [apex/up#361]
@tj what do you think of the best approach to keep the container warm, the cold start in my case took 8s to serve the first request.

i thought of a scheduler that run a request every x minutes, the problem is that i don't know how much time the container is kept before aws destroy it.

thank you.

**Comment by kaihendry** [comment]
AWS peep mentioned to me just pinging it on a cheap route. Every minute should be cheap/good enough.

**Comment by tj** [comment]
Increasing the `.lambda.memory` can dramatically reduce the cold start for Node apps, all the `require()`s are pretty slow with 128mb.

Other than that you could use Cloudwatch Events to request every few minutes. Might bake that into Up at some point too if it's useful, Go app cold start seems negligible (~5000-800ms), no require()s though.

You could also try a JS bundler to mitigate that if you're not already.

**Comment by hellorachid** [comment]
@kaihendry i agree about using a cheap route, in my case, the route return a simple json.

@tj  i agree with you, in fact i tested but i observed that when the container is up my app use max 118mb, so it will help just in cold start but not in normal case plus it will increase the bills.
i will use Cloudwatch Events and see how it will behave

Thank you

**Comment by huangbong** [comment]
+1 for more documentation on the cold start issue. Never new this was even an architectural issue with lambda until I started using up.

I ended up bumping my lambda functions memory to 1024mb and creating a cloudwatch event to trigger my functions every minute.

Everything is running very fast now.

**Comment by tj** [comment]
@huangbong yea I'll add some more docs soon! It's typucally only really an issue for Java, and Node with tons of require()s. When creating the next.js example in up-examples I noticed it was significantly slower than the others as well, but I don't know the guts so I can't comment on why.

**Comment by tj** [comment]
thought I had an issue already, but nope! Opened #361

**Comment by komuw** [comment]
should be https://github.com/apex/up/issues/577 not https://github.com/apex/up/issues/361 ? @tj

**Comment by tj** [comment]
oops :D hahahah yes
