### ISSUE TITLE
Install via npm

### ISSUE THREAD

**Issue by tj** [apex/up#37]
Not a big deal since it'll be a single copy/paste command anyway, but the install script could be published to npm to make that a little smoother for Node people.

https://github.com/Automattic/cloudup-cli is using the "up" package currently, but it's basically a dead project.

**Comment by lukeed** [comment]
Much appreciated 🙏

**Comment by tj** [comment]
Opened an issue, if they don't get back to me in a month I'll take that as a yes haha..

**Comment by tj** [comment]
No response from them yet so I think it's fine to take `up` in NPM, they seem to have no interest in it

**Comment by tj** [comment]
boom you can `npm install -g up` now as well

**Comment by nunofgs** [comment]
@tj version 1.0.2 [in npm](https://www.npmjs.com/package/up/v/1.0.2) seems like it doesn't include a postinstall script any more.

**Comment by tj** [comment]
hmm odd, I haven't touched anything, I wonder if NPM disabled those due to potential security issues or something
