### ISSUE TITLE
Client/server architecture?

### ISSUE THREAD

**Issue by jpillora** [apex/up#376]
One of the main reasons I struggle to use `up` is the fact that the complete application `.zip` must be uploaded on each deploy. If this `.zip` weighs >30MB and my connection is flakey that day, my deploy often times out. And in Australia where most people have a 1-2 Mbps uplink, this is quite often. This might also be an issue on mobile.

To resolve this, `up` could be architected like docker, where the client is a cli application which speaks an http server and by default, the client and server reside on the same machine. In the case of `up`, the "server" could optionally be a lambda function, which uses S3 for project file caching and the client is a thin cli wrapper around the server API.

On deploy, the client could ask the server what it currently has cached in S3, compute the diff, and just send what's missing. And then `up` works as normal except it's run from a lambda function. In addition to much smaller uploads, this has the added benefit of reduced RTTs to all AWS endpoints.

The current mode would be supported by the running the up server on localhost/localsock, with it as the default server. Of course, S3 caching and file diffs would be skipped.

This would need to be opt-in as it'd be deploying an unknown function, though `up` is already managing functions, API gateway, etc so I don't think it's much of a stretch.

I was thinking of doing this myself though I thought I'd throw out the idea here first.

**Comment by tj** [comment]
Canada is pretty bad too (maybe 3-5mbps), but my ~30mb zips are still a second or two.  Honestly though this would be an issue with any deployment system aside from CI or EC2 with better networks. Even pushing Docker layers is going to be very slow if you have to rebuild the layer with your app constantly.

It could be interesting to explore a diff-based approach, but Up will be able to support Docker platforms too, so I'm not sure I'd want to overkill Lambda specifically. For example Up could still push to ECS, Azure's ACI etc.

Deploying from a local machine is a bit gimmicky, it's great for getting started or small teams, but I think a CI or GIT-hook based system is necessary for teams to utilize better networks, and enforce tests etc of course.

**Comment by jpillora** [comment]
Hey @tj sorry completely forgot about this one. Yeah I agree Docker pushes are quite slow. I think the client/server architecture would be a good fit for up, whereas the diff against image layers would not - since a single layer is hashed and then re-uploaded on any change. A diff with `up` could be against each individual file, and you could take this a step further with a binary diff against large files (e.g. [rdiff](https://gist.github.com/jpillora/edb83dc2d511c410cf46485e53569fdf)) though this only makes sense with a server at the other end doing the packaging.

RE: support Docker platforms directly: Like having an `up-server` image? which runs a different version of up? or do you mean make it more like a CI server, which pulls up projects and then runs up deploy?

Which brings me to my semi-solution to this, at the moment, I'm using circleci. I add some `AWS` env vars and:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install npm
          command: 'npm install'
      - run:
          name: Download up
          command: 'curl https://i.jpillora.com/apex/up | bash'
      - run:
          name: Deploy
          command: './up deploy production'
```

For real apps, you'd want to have a CI/CD workflow, with tests, where up could slot in easily at the end. My use case is personal apps which I just want to deploy as fast as possible. Understandably, this isn't a priority, so all good. Just food for thought 👍
