### ISSUE TITLE
Domain Name integration (Hangs when applying new stack)

### ISSUE THREAD

**Issue by cassiozen** [apex/up#378]
## Description

I bought a domain name using up's command line. After confirmation, I'm trying to apply the domain configuration, but it hangs and quits before finishing.

Here are the verbose output:

```
     4ms     DEBU up version 0.2.10
     0s      DEBU region defaulted to "us-west-2"
     0s      DEBU track "Apply Stack" map[arch:amd64 version:0.2.10 os:darwin]
     171ms   DEBU event stack.apply map[region:us-west-2]
     0s      DEBU looking up cert for httparty.cc
     388ms   DEBU found cert for httparty.cc: arn:aws:acm:us-east-1:2(...)4:certificate/17(...)3e
     694ms   DEBU event platform.stack.apply map[changes:3]
     18.136s DEBU event platform.stack.report map[total:3 complete:0]
     0s      DEBU event platform.stack.report.complete map[total:3 complete:0 duration:18.13613782s]
     0s      DEBU event platform.stack.apply.complete map[changes:3 duration:18.83026873s]
   ⠸ 0s      DEBU event stack.apply.complete map[region:us-west-2 duration:19.389876842s]%
```

## Steps to Reproduce

1 - Buy a domain using UP command line.
2 - Wait for confirmation
3 - `up stack plan`
4 - `up stack apply`

**Comment by tj** [comment]
The CloudFront distribution can take a long time to create, are you sure it wasn't that? (can be as long as 30-40 minutes, no away around it for now :( ).

**Comment by cassiozen** [comment]
I believe it was a configuration error - I didn't know I was required to specify a subdomain.

After I switched from:
 
```json
"domain": "domain.com"
```

to

```json
"domain": "www.domain.com"
```

it worked.

**Comment by tj** [comment]
Hmm yeah you shouldn't have to use a subdomain, I've used an "apex" domain for gh-polls.com for example.

**Comment by tj** [comment]
Not sure why I was thinking about purchased domains only, this will be great for sub-domains when you're already rolling with a zone. I'll definitely add this.

**Comment by tj** [comment]
oops I'm editing the wrong issue, I think this is fine now
