### ISSUE TITLE
Can't load static images in next.js app

### ISSUE THREAD

**Issue by tamagokun** [apex/up#384]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

Files in `/static/` of a next.js app don't load. Getting a 502 error.

![screen shot 2017-10-19 at 8 56 14 am](https://user-images.githubusercontent.com/487333/31771809-73f0de82-b4ab-11e7-89d4-8bf3bf1f6829.png)

## Steps to Reproduce

Create a next.js app (example here https://github.com/apex/up-examples/tree/master/oss/node-next) and drop an image into the static folder, then create a page to load that file in the webpage. Also, this doesn't seem to work at all under a typical `up deploy` situation because the stage is append to the url path. I think to truly reproduce, the deployment needs a proper url.

example page:

```js
export default () =>
  <div>
    <img src='/static/test.png' />
  </div>
```

I thought perhaps I needed a `static` option in `up.json`, but that seemed to just break everything. Digging into the next.js source a bit, I do see that there is a route handler for `/static/*`, so it seems like the node app should be able to handle loading assets.

If this is the wrong issue tracker to post this, just say so, and I can move it elsewhere.

EDIT: Updated to use an image rather than any file.

**Comment by tj** [comment]
Hmm I just tried uploading to my dummy test site and it seems ok:

```
$ curl https://up-example.com/static/test.text
hello
```

You're right that `static` will break in this case, Next should be serving its own files but it seems to work fine for me.

**Comment by tj** [comment]
Seems to be doing something weird now, taking a look! Noticed that the first request is really slow with Next, something to do with the on-demand compiling or something? I see some timeouts, but I'll try and figure out what's up with the image.

**Comment by lukeed** [comment]
If you're using `/static/foo.jpg` for your image source, it will definitely fail because the leading `/` requests from root when you need it to request from the stage path.

**Comment by tamagokun** [comment]
I assumed everything was pre-compiled from next's build step. I'm not sure what makes it so slow to spin up.

Another thing i've noticed is that if I am not running the app behind a custom domain, I actually get a 200 response, but no content:

```
HTTP/2 200
content-type: image/png
content-length: 0
date: Thu, 19 Oct 2017 17:28:56 GMT
x-amzn-requestid: fc3fbc19-b4f2-11e7-8e93-31eca7610c57
last-modified: Tue, 17 Oct 2017 13:19:52 GMT
x-amzn-remapped-content-length: 5944
vary: Accept-Encoding
cache-control: public, max-age=0
x-powered-by: up
etag: W/"1738-15f2a7d8cc0"
x-amzn-trace-id: sampled=0;root=1-59e8e0d8-71650626d9a1f528de30d941
accept-ranges: bytes
x-amzn-remapped-date: Thu, 19 Oct 2017 17:28:56 GMT
x-cache: Miss from cloudfront
via: 1.1 d37af2bc3006c9b1dcc35cb8e8366d95.cloudfront.net (CloudFront)
x-amz-cf-id: jpwrQVnUgOb32OrSOZJmfzzCNHwfMKotPUuI1qs1BeKcLNZLV7uo3w==
```

**Comment by tj** [comment]
Looks like it was a permission issue. I did `chmod 0755 static/*` and now it's fine, Next doesn't log any issue though haha

**Comment by tamagokun** [comment]
holy crap, how I did not check the permissions on the files was beyond me, but yep, that did it!

It may or may not be worth making note of this in the docs, that permissions are carried over in the deployment. I don't think other platforms such as `now` do that.

**Comment by tamagokun** [comment]
Also, thank you for debunking!!! 🙌

**Comment by tj** [comment]
Yeah agreed, I need to add a troubleshooting section :D – might be able to improve that situation as well I'll take a look.

**Comment by tj** [comment]
Looks like the owner in Lambda is "slicer", and the proc user is some random thing like "sbx_user1094", so that's why there was a disconnection there. I'll open an issue and get that fixed!

**Comment by tj** [comment]
I think the slowness is just all the `require()s` actually – looking at the deps, there are a lot, even for a "hello world", but I'm not familiar with the pre-compile step so maybe that should mitigate all the deps.

**Comment by lukeed** [comment]
The application itself is large & requires more boot time than you'd expect. Still working on my alternative, when I can 😞

**Comment by tj** [comment]
#174 would help mitigate things a bit, since delegating to Next.js (or other large Node apps) for static file serving is slower with the cost start it imposes.
