### ISSUE TITLE
static server cannot resolve absolute paths

### ISSUE THREAD

**Issue by cullophid** [apex/up#392]
When running the static server assets have to be referenced by relative path.
This is an issue when writing a single page app.

## Steps to Reproduce

```
{
  "name": "gain-web",
  "profile": "apex",
  "type": "static",
  "static": {
    "dir": "public"
  },
  "regions": ["eu-central-1"],
  "build": "npm run build",
  "redirects": {
    "/*": {
      "location": "/"
    }
  }
}
```

when the app is running locally everything works fine, but when running on aws `/development`  is added to the path thereby changing the url of the assets

**Comment by tj** [comment]
Opened #394 for reference (common question). TL;DR: we're stuck with it for now :(
