### ISSUE TITLE
Ssl certificates gets added to us-east-1

### ISSUE THREAD

**Issue by cullophid** [apex/up#393]
## Description
When setting up custom domains with up the ACM certificate get added to us-east-1 (in aws acm) even though the stack is set to eu-west-1

## Steps to Reproduce
setup an app with a custom domain (external domain provider) on a region that is not us-east-1

**Comment by slaskis** [comment]
I believe it's required for CloudFront to have their ACM certificates in us-east-1 for now:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html

**Comment by tj** [comment]
Yep, it has to be in us-east-1 at the moment. Awkward even from a coding point of view, wish that wasn't the case but we're stuck with it for now!

**Comment by cullophid** [comment]
ah fair enough... :)
Maybe you could add it in the docs... i spent a long time trying to figure out what had happened :)

**Comment by einkoro** [comment]
@tj Is us-east-1 still required for CloudFront and ACM certificates?

**Comment by tj** [comment]
@einkoro yep, I think us-east-1 was the original AWS region so some stuff has to be there
