### ISSUE TITLE
docker runtime

### ISSUE THREAD

**Issue by thewillhuang** [apex/up#405]
not an issue, but a wild idea

https://hackernoon.com/how-did-i-hack-aws-lambda-to-run-docker-containers-7184dc47c09b

https://github.com/grycap/scar

then you can support pretty much every runtime 🚀 

## Love Up?
💯 🥇

**Comment by tj** [comment]
saw that! Haven't looked into it yet. I'll be supporting other providers as well, some which support Docker out of the box, so I might not beat Lambda to death with that stuff, there will be plenty of good alternatives to Lambda I think

**Comment by tj** [comment]
closing this one for now, I think it'll be better suited for non-Lambda platforms
