### ISSUE TITLE
Path aliases

### ISSUE THREAD

**Issue by sumanion** [apex/up#406]
If I have several independent microservices is it somehow possible to alias them to different paths on a domain?

**Example:**

`first-microservice` => `https://example.com/v1/first-microservice`
`second-microservice` => `https://example.com/v1/second-microservice`

**I've tried:**

```json
{
  "name": "first-microservice",
  "stages": {
    "production": {
      "domain": "example.com",
      "path": "/v1/first-microservice"
    }
  }
}
```
_and_

```json
{
  "name": "second-microservice",
  "stages": {
    "production": {
      "domain": "example.com",
      "path": "/v1/second-microservice"
    }
  }
}
```

but, it does not seem to work.

**Comment by tj** [comment]
Multiple on a domain don't work quite yet, but it's on the list. Dup of #106
