### ISSUE TITLE
Multi-region service only prints 1 URL

### ISSUE THREAD

**Issue by lukeed** [apex/up#407]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

When deploying to multiple regions, subsequent `up url` commands will only print 1 URL to the console.

I expected all regions' URLs to be printed under the current `stage`.

## Steps to Reproduce

1. Deploy any service to multiple regions; eg `us-*`
2. Wait for completions
3. Run `up url`

## Love Up?

Yes :tada:

**Comment by tj** [comment]
Ahh yea the multi-region stuff is missing quite a bit right now.

Closing for now since I'll do all of the multi-region stuff as one pass: #134, it's just lower priority than regular functionality at the moment.

**Comment by lukeed** [comment]
Yup, all good! Debated whether or not to open an issue since Multi-Region is not officially in yet, but can't hurt to know more :P

**Comment by tj** [comment]
totally :D pretty half-baked at the moment, but after I get this billing stuff all integrated I should be able to focus more on that soonish
