### ISSUE TITLE
replace jteeuwen/go-bindata with shuLhan/go-bindata

### ISSUE THREAD

**Issue by komuW** [apex/up#409]
## Prerequisites
N/A

## Description

Replace github.com/jteeuwen/go-bindata/ with https://github.com/shuLhan/go-bindata                             
As per the discussion in this issue; https://github.com/jteeuwen/go-bindata/issues/165 /jteeuwen/go-bindata appears like an abandoned project.                                     
And also from that discussion, it seems like the community is coalescing around https://github.com/shuLhan/go-bindata which is also actively maintained.                     
Of course jteeuwen/go-bindata still works!

## Steps to Reproduce

Describe the steps required to reproduce the issue if applicable.

## Love Up?

Please consider donating https://opencollective.com/apex-up/donate to help the project.

Just have a general question? Join us on Slack https://apex-slackin.herokuapp.com/

**Comment by tj** [comment]
hmm seems to work fine, any benefit to switching? not worried about the maintenance part since it's already functional, but if it does a better job with something LMK!

**Comment by komuW** [comment]
I dont think there's any benefit to switching apart from the maintenance part.
