### ISSUE TITLE
Team CRUD

### ISSUE THREAD

**Issue by tj** [apex/up#410]
API stuff is in place, but not yet in the CLI. Currently you'll just have your personal default team.

- [x] add stripe cust description as the `team.id`
- [x] add listing of members and invites
- [x] add team creation
- [x] removal of members
- [ ] maybe remove `--email` and just use `--team` w/ prompt?
- [ ] deploy api changes
- [ ] unify interactive portions
- [x] update docs
- [ ] update examples
- [ ] update blog posts so commands match
- [ ] update emails so commands match
- [x] port changes to team client back to hub

**Comment by lukeed** [comment]
`profile` instead of `team` might make most sense? The term accommodates single & group accounts

**Comment by jonotron** [comment]
Would we be able to rename a personal team to a named team (or whatever they will be called)?

**Comment by tj** [comment]
@jonotron probably not via the CLI unless it becomes a common case, but I can do it manually for anyone who is utilizing the invites for their personal team once this part is done
