### ISSUE TITLE
Account Creation Flow

### ISSUE THREAD

**Issue by lukeed** [apex/up#413]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

I don't read instructions, and instead just went thru the CLI as a (true) dumb user. Documenting the issues I ran into:

1. Canceling `account login` without entering any text will still print:

    ```
   ⠸ verify: Check your email for a confirmation link

     Error: login: Bad Request
    ```

2. Running `up account subscribe` without adding a card first will:
    A) Run through the prompts anyway
    B) Throw `Error: subscribing: Internal Server Error`

3. _Thought:_ Is it possible to show all (empty) fields when adding a card?

4. _Thought:_ It'd make more sense (imo) to rearrange the fields.

    Current:
    ```
     Name: 
     Number: 
     CVC: 
     Expiration month: 
     Expiration year: 
     Country: 
     City: 
     State: 
     Address: 
     Zip: 
    ```

    Better?
    ```
     Name: 
     Number: 
     CVC: 
     Expiration month: 
     Expiration year: 
     Address: 
     City: 
     State: 
     Country: 
     Zip: 
    ```

5. Running `up account` will show the non-discount price.

    I'd either add a line that prints the applied `discount` or factor it into `amount` directly.

**Comment by tj** [comment]
users that don't read instructions are the best :D haha ideally it's easy enough to use without docs. The account stuff is still in a pretty rough WIP state (#404). 

Definitely need to do a better job walking through each step a bit more seamlessly. Appreciate the feedback! I'll close this one and add those to #404

**Comment by lukeed** [comment]
Sounds great! I bludgeoned my way thru~!
