### ISSUE TITLE
SSL certificates created in the wrong region

### ISSUE THREAD

**Issue by pgmmpk** [apex/up#416]
I am trying to use my own domains to configure SSL.

Using `us-east-2` as `region` in my `up.json`.

Judging by AWS console, certificates are being created in `us-east-1`.

Lambda is properly created in `us-east-2`.

I worked this around by approving certificates in both regions...

**Comment by tj** [comment]
AWS previously had a requirement that ACM certs had to be in us-east-1 for APIG at least, unless that recently changed

**Comment by pgmmpk** [comment]
Yep, from https://aws.amazon.com/certificate-manager/faqs/
> To use an ACM certificate with Amazon CloudFront, you must request the certificate in the US East (N. Virginia) region. ACM certificates in this region that are associated with a CloudFront distribution are distributed to all the geographic locations configured for that distribution.

Closing as non-issue
