### ISSUE TITLE
CI friendly output

### ISSUE THREAD

**Issue by tj** [apex/up#422]
spinners etc are not great hahah... and detect UP_CONFIG to toggle this as well

**Comment by stephenmathieson** [comment]
👍  this is pretty bad haha:

![image](https://user-images.githubusercontent.com/571265/33389530-c58dfc9e-d4f8-11e7-99f3-19c70a72040c.png)

**Comment by tj** [comment]
hahahaha hey, it's beautiful come on

**Comment by hhsnopek** [comment]
Any objection to use `--format=plain` by default when env var `CI == "true"`?

**Comment by tj** [comment]
yea something like that might be nice, especially if there's something they all set by default, otherwise maybe `UP_FORMAT=plain`?

I was going to do an isatty check but I'm not positive if they pretend to be terminals to that extent or not, but that'd make it automatic at least

**Comment by hhsnopek** [comment]
I got the idead from create-react-app/jest which will run in interactive mode unless `CI` is set to true

**Comment by tj** [comment]
darn `if [ -t 0 ]` is true, so no magical isatty check I guess (in semaphore at least)

**Comment by tj** [comment]
oh nice but it does set `CI=true` so that sounds good to me, didn't think that was "standardized"

**Comment by hhsnopek** [comment]
🚀
