### ISSUE TITLE
Cert verification email domain is wrong for sub-domains

### ISSUE THREAD

**Issue by tj** [apex/up#425]
If you use sub-domains AWS tries to email those, so we should add `DomainValidationOption`, and optionally allow the user to specify which email to send these to (cannot assume sub-domain because of .co.uk et al).

![](https://pbs.twimg.com/media/DPCpyxaUQAENsV8.jpg:large)

**Comment by BurntCaramel** [comment]
Looks like there is a package here for finding the root domain: https://godoc.org/golang.org/x/net/publicsuffix

Also `EffectiveTLDPlusOne()` might help as well to find say `collected.design` from the `latest.1.slice.collected.design`

**Comment by tj** [comment]
oh nice! that'll definitely help :D

**Comment by tamagokun** [comment]
I believe AWS will walk up the domain until it finds a domain with an MX record or reaches the root.

http://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-email.html#troubleshooting-email-subdomains

**Comment by tj** [comment]
@tamagokun interesting thanks, maybe it is broken after all, a lot of people (and me) have been reporting emails never being sent

**Comment by tamagokun** [comment]
@tj oh yeah, it's totally "broken" seeming. Lots of having to "re-send" the email because I would never get it.

**Comment by tj** [comment]
hahah great 😄 , hopefully v0.3.4 will help for Up at least
