### ISSUE TITLE
docs typo in aws_credentials

### ISSUE THREAD

**Issue by cloudkite** [apex/up#428]
Was going to send a PR but the version on https://up.docs.apex.sh/#aws_credentials doesn't seem to match whats in https://github.com/apex/up/blob/master/docs/02-aws-credentials.md

```
"Action": [
  "ssm:*"
  "sns:CreateTopic",
  "sns:ListTopics",
  "sns:sns:SetTopicAttributes",
  "sns:sns:DeleteTopic"
],
```

should be

```
"Action": [
  "ssm:*",
  "sns:CreateTopic",
  "sns:ListTopics",
  "sns:SetTopicAttributes",
  "sns:DeleteTopic"
],
```

**Comment by tj** [comment]
bad merge I think, fixed now!
