### ISSUE TITLE
up pro account subscribe problem

### ISSUE THREAD

**Issue by luisbebop** [apex/up#431]
I'm using `up` version `0.3.4`
Trying to upgrade to Up pro, but facing 2 problems:

When I use the command: `up account subscribe` it asks me, `Coupon (optional):`
As I don't have a coupon code I just type enter getting the message:

```
     Coupon (optional):


     Error: fetching coupon: Unauthorized
```

If I type a space on the coupon, it asks me which plan I want to subscribe, getting `internal server error` after that.

```
     Coupon (optional):
     Subscribe to Up Pro for $20.00/mo USD? Yes


     Error: subscribing: Internal Server Error
```
Any help?! Or coupon code 😎💸

**Comment by tj** [comment]
fixed :D

**Comment by luisbebop** [comment]
🎉
