### ISSUE TITLE
Regional endpoints

### ISSUE THREAD

**Issue by tj** [apex/up#432]
Lower latency for local and gets CF out of the way for custom CF etc.

- [ ] default for OSS only?
- [ ] dns validation
- [ ] option in Pro, or `edge` option? (likely have to leave it due to backwards compatibility)
- [ ] adjust documentation (notes about speed / certs)

**Comment by lukeed** [comment]
Awesome!

**Comment by sudhirj** [comment]
Can I request a bump in this,  maybe as a Pro feature? I’m setting up an app with custom CF.

**Comment by tj** [comment]
@sudhirj I'll take another look today, I have a branch going but I forget what I was stuck on haha

**Comment by tj** [comment]
Should have this in a release tomorrow, it's just a bit slow to QA with how long it takes to test the various settings / deploys

**Comment by tj** [comment]
v1.0.0 Pro has `lambda.type: "regional"` now 🎉 

https://up.docs.apex.sh/#configuration.lambda_settings

**Comment by sudhirj** [comment]
Thanks a ton :)
