### ISSUE TITLE
Slack link busted

### ISSUE THREAD

**Issue by tj** [apex/up#435]
Damn Heroku hahahah... they booted me off the free plan for too much traffic.

- [ ] fix
- [ ] move to chat.apex.sh
- [ ] cancel Heroku

**Comment by stephenmathieson** [comment]
Should deploy it with up to avoid that problem 😉

**Comment by tj** [comment]
will move it later at some point, the overkilled socket.io stuff would probably break

**Comment by tj** [comment]
seems buggy, can't get it to work but Heroku is about to screw me again hahaha, if anyone knows Slackin alternatives LMK :D don't need all this overkill socket.io stuff

**Comment by hhsnopek** [comment]
IRC 😉

**Comment by tj** [comment]
It's too late hahah stuck with Slack now
