### ISSUE TITLE
up.json type directive is not respected

### ISSUE THREAD

**Issue by h2non** [apex/up#436]
Not sure if the current behavior is the legit one, but it was confusing to me. When deploying a static app type and declaring at up.json level type=static, if the source tree contains a file assosiated to an specific language runtime, such as package.json, the explitic type is ignored and the app deployment assumes it’s an node.js app, instead of static app.

I think explicitness here should have preference, always.

Thanks for creating Up :)

**Comment by tj** [comment]
ahhh agreed, just an oversight, I'll get that fixed!
