### ISSUE TITLE
up start - hot reload

### ISSUE THREAD

**Issue by pctj101** [apex/up#438]
Would be great to get some hot reload ability during local development/running.  Is this the realm of "up" or outside of scope?

**Comment by tj** [comment]
Could be nice I think! We still have to add support for custom local `up start` commands to run, so that it can build Go without cross-compiling etc.

**Comment by pctj101** [comment]
Oh yeah... that sure makes it more complicated.

**Comment by pctj101** [comment]
https://github.com/apex/up/issues/147

**Comment by tj** [comment]
I'll close and we can follow in there, but I'd love to get that in soon for Go et al, I've been using `up start` more just for the logging alone locally
