### ISSUE TITLE
Clarify HTTPS Wildcard Issuance in docs

### ISSUE THREAD

**Issue by pctj101** [apex/up#440]
In https://up.docs.apex.sh/#configuration.stages_custom_domains

It mentions:
```
Stages & Custom Domains
...
Here’s another example mapping each stage to a domain, note that Up will create a wildcard certificate, so sub-domains are fine.
{
  "stages": {
    "production": {
      "domain": "api.gh-polls.com"
    },
    "staging": {
      "domain": "stage.gh-polls.com"
    },
    "development": {
      "domain": "dev.gh-polls.com"
    }
  }
}
```

However, in reality, 3 certificates are created. That's fine (and arguably better) too... just different from the docs.

**Comment by tj** [comment]
Ah! Sorry about that, that was from an older implementation. I had to change it (may change it back soonish) but I'll fix the docs
