### ISSUE TITLE
Problem with hosted zones

### ISSUE THREAD

**Issue by hosmelq** [apex/up#447]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

At the moment with the following config two hosted zone are created and i think i can only add one name servers group.

<img width="347" alt="screen shot 2017-11-29 at 8 41 48 am" src="https://user-images.githubusercontent.com/1166143/33380579-3059f07c-d4e1-11e7-8ad3-71892693599d.png">

## Steps to Reproduce

```json
{
	"name": "balance-saldotuc-com",
	"profile": "saldotuc",
	"dns": {
    "saldotuc.com": [
      {
        "name": "saldotuc.com",
        "type": "MX",
        "value": [
          "1 ASPMX.L.GOOGLE.COM",
          "5 ALT1.ASPMX.L.GOOGLE.COM",
          "5 ALT2.ASPMX.L.GOOGLE.COM",
          "10 ALT3.ASPMX.L.GOOGLE.COM",
          "10 ALT4.ASPMX.L.GOOGLE.COM"
        ]
      }
    ]
  },
  "environment": {
    "NODE_ENV": "production"
  },
  "hooks": {
    "build": "make"
  },
	"lambda": {
		"memory": 128
  },
  "proxy": {
    "command": "./node-v8.9.1-linux-x64/bin/node index.js"
  },
  "stages": {
    "production": {
      "domain": "balance.saldotuc.com"
    }
  }
}
```

**Comment by tj** [comment]
hmm yea looks like a bug, thanks for reporting I'll check this out today hopefully

**Comment by tj** [comment]
I'll do some more QA before the next release but this should be fine now

**Comment by hosmelq** [comment]
Thank you. This release is included in the pro version ?

**Comment by tj** [comment]
yep! I just pushed 0.1.11 pro with the fix
