### ISSUE TITLE
Remove Node.js shim in favour of native Go support

### ISSUE THREAD

**Issue by tj** [apex/up#450]
Native Gooooo.

- [x] remove shim
- [x] add `UP_RUNTIME`
- [x] refactor runtime inference
- [x] utilize `UP_RUNTIME` to switch to native Go
- [ ] test / blog about latency improvements
- [ ] QA
- [ ] release

**Comment by jadbox** [comment]
ROFL, I just came here to file this issue as soon as I found out too xD

**Comment by jadbox** [comment]
Question is: what is the Lambda native interface to Go? Since module hot loading is not supported afaik, will Lambda support vanilla Go webservers?

**Comment by tj** [comment]
Go has plugin support actually, but only on Linux, so maybe they're taking advantage of that

**Comment by brunoksato** [comment]
Finally: https://aws.amazon.com/about-aws/whats-new/2018/01/aws-lambda-supports-go/

**Comment by appleboy** [comment]
Another blog post: https://aws.amazon.com/blogs/compute/announcing-go-support-for-aws-lambda/

**Comment by tamagokun** [comment]
![screenshot from 2018-01-15 22 11 07](https://user-images.githubusercontent.com/487333/34970237-2e7ad20a-fa41-11e7-877d-113ff23c7e5d.png)

:open_mouth:

**Comment by appleboy** [comment]
https://github.com/aws/aws-lambda-go some example for golang.

**Comment by tj** [comment]
Should have this in tomorrow!

**Comment by tj** [comment]
Still hunting, but it looks like they don't have a more recent Node binary on there at all (0.10.x) so it may be borderline useless for this use-case :( yay Amazon..

**Comment by lukeed** [comment]
0.10????? Wtf

**Comment by vishal8492** [comment]
Golang runtime for Go it is... . Option b) sounds lot better. Haven't run any benchmark but will probably try out Vanilla Go today.

**Comment by tj** [comment]
@vishal8492 yeah decided to do take that route, definitely not ideal maintaining two shims but oh well. 

I'll do more QA today and get this released tomorrow hopefully, I want to make sure we actually see some latency benefits otherwise it's pointless.

**Comment by tj** [comment]
Yeah closing this in favour of #543. Go and Node are very comparable when used as a shim, however the "true" zero overhead native Go is great. I don't see a reason to maintain two shims.
