### ISSUE TITLE
Config autocomplete via jsonschema

### ISSUE THREAD

**Issue by tj** [apex/up#451]
- https://github.com/SchemaStore/schemastore
- https://github.com/bali182/autocomplete-json
- handy tool https://jsonschema.net/#/
- example http://json.schemastore.org/package
- [ ] write schema
- [ ] document
- [ ] document list of tools
- [ ] blog post because IMO this is sweet, even I don't want to look up my own docs for config haha

**Comment by lukeed** [comment]
gasp, javascript? 😆

**Comment by tj** [comment]
need mechanical turk for engineering tasks, this is going to give me RSI :D

**Comment by tj** [comment]
should probably generate docs from this too, duplicate effort
