### ISSUE TITLE
Add wildcard ACM certs back

### ISSUE THREAD

**Issue by tj** [apex/up#452]
- It's less annoying for sub-domains (only need to verify one)
- It's easy to hit the (default) ACM cert limit for your account 
- Still required for sub-sub domains, so we need some logic here to determine when a new cert is necessary
- Make sure deleting the stack won't take other services with it... 
- [x] confirm they are not removed upon stack deletion

**Comment by cederigo** [comment]
This would be awesome. Now I'm finding myself not specifying stages at all to setup them later on api gateway manually. I thought about the problem and came up with the following idea how this could be implemented:
```
{
  "stages": {
    "production": {
      "domain": "api.gh-polls.com",
      "cert": "*.gh-polls.com"
    },
    // Or maybe specify the certificate arn?
    "staging": {
      "domain": "stage.gh-polls.com"
      "cert": "arn:aws:acm:us-east-1..."
    }
  }
}
```
This could be added without breaking changes and your requirements above could be met. What do you think?

**Comment by tj** [comment]
I'd like to avoid specifying the cert, I think we can pretty easily determine when to use a wildcard programmatically. Stack deletion may be an issue though I have to double check that.

**Comment by cederigo** [comment]
Would you accept a PR? Im pretty new to Golang but I want to do more with it. For the programmatic part. Would you do something like:

1. List certs and use existing wildcard cert that matches if possible.
2. If not 1., create wildcard cert

or something fancier? For the deletion I would need some hints

**Comment by tj** [comment]
I'm not sure off-hand what AWS' behaviour is for the deletion. I believe it will refuse to delete certs used by other apps. If that's the case this might not be worth adding

**Comment by cederigo** [comment]
I also think thats the case. I will double check it and if it refuses to delete used certs, just log it accordingly. Ok?

**Comment by tj** [comment]
oh right, I forgot that we have certs outside of CloudFormation. Go for it :D. [util.Domain](https://github.com/apex/up/blob/master/internal/util/util.go#L339)  may be useful there.

**Comment by tj** [comment]
Should have this in soon, waiting on more certs from AWS for testing
