### ISSUE TITLE
`up env add` not exposing environment variables to Node's `process.env`

### ISSUE THREAD

**Issue by holic** [apex/up#455]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I've set up some environment variables with `up env add` and have a route on my Node.js app that outputs the keys from the environment (`Object.keys(process.env)`) that I deployed with `up`. However, the keys from `up env` are not showing up. I've tried this:
- with and without stage option
- before and after deploying
- destroying and recreating the stack

None of these combinations seem to get the environment variables to appear within the app.

## Steps to Reproduce

```
$ up env set MAILGUN_DOMAIN example.com -cv
     5ms     DEBU up version 0.1.11-pro
     1ms     DEBU infer name from current working directory "inquiries"
     0s      DEBU region from aws shared config "us-west-1"
   ⠹ 297ms   DEBU track "Add Secret" map[arch:amd64 version:0.1.11-pro plan:pro cleartext:true stage: has_desc:false os:darwin]
     Added MAILGUN_DOMAIN

$ up -v
     4ms     DEBU up version 0.1.11-pro
     0s      DEBU infer name from current working directory "inquiries"
     0s      DEBU region from aws shared config "us-west-1"
   ⠋ 0s      DEBU track "Deploy" map[has_logs:true has_profile:false arch:amd64 dns_zone_count:0 stage_domain_count:0 redirect_rules_count:0 environment_count:0 stage_count:0 has_cors:false has_error_pages:false app_name_hash:86a54c7f2b27c02acf9fcb16a31c4b57 stage:development proxy_timeout:15 version:0.1.11-pro regions:[us-west-1] header_rules_count:0 inject_rules_count:0 plan:pro os:darwin duration:0 type:server]
     0s      DEBU track "Deploy" map[has_logs:true has_profile:false arch:amd64 dns_zone_count:0 stage_domain_count:0 redirect_rules_count:0 environment_count:0 stage_count:0 has_cors:false has_error_pages:false app_name_hash:86a54c7f2b27c02acf9fcb16a31c4b57 stage:development proxy_timeout:15 version:0.1.11-pro regions:[us-west-1] header_rules_count:0 inject_rules_count:0 plan:pro os:darwin duration:0 type:server]
     0s      DEBU event deploy map[]
     0s      DEBU event platform.build map[]
     0s      DEBU hook prebuild is not defined
     0s      DEBU event hook map[name:build hook:[]]
     14ms    DEBU hook "build" command ""
     0s      DEBU event hook.complete map[name:build hook:[] duration:13.539616ms]
     202ms   DEBU injecting proxy
     0s      DEBU open
     0s      DEBU filtered .env – 87
     0s      DEBU filtered .git – 442
     0s      DEBU filtered .gitignore – 45
     ...
     0s      DEBU add package.json: size=213 mode=-rwxr-xr-x
     0s      DEBU stats dirs_filtered=1 files_added=498 files_filtered=2 size_uncompressed=17 MB
     6ms     DEBU close
     0s      DEBU event platform.build.zip map[duration:876.454178ms files:498 size_uncompressed:16875918 size_compressed:5437600]
     2ms     DEBU removing proxy
     0s      DEBU hook postbuild is not defined
     0s      DEBU event platform.build.complete map[duration:892.107904ms]
     0s      DEBU hook predeploy is not defined
     1ms     DEBU hook deploy is not defined
     415ms   DEBU checking for role
     2ms     DEBU using existing role arn:aws:iam::366467957144:role/inquiries-function
     1ms     DEBU event platform.deploy map[stage:development region:us-west-1]
     4.726s  DEBU fetching function config region=us-west-1
     0s      DEBU event platform.function.update map[stage:development region:us-west-1]
     0s      DEBU event platform.deploy.complete map[stage:development region:us-west-1 duration:4.729586776s version:]
     0s      DEBU hook postdeploy is not defined
   ⠋ 0s      DEBU hook clean is not defined
     0s      DEBU hook clean is not defined
   ⠋ 0s      DEBU event deploy.complete map[duration:6.037209366s]
```

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://apex-slackin.herokuapp.com/

**Comment by tj** [comment]
hmm I'm not able to reproduce with 0.1.11-pro. Using https://github.com/apex/up-examples/tree/master/pro/secrets:

```
$ up env add MSG hello

     Added MSG

$ up env add NAME Tobi

     Added NAME

$ up

     build: 7 files, 4.4 MB (383ms)
     deploy: complete (6.687s)

$ curl `up url`
hello Tobi from development
```

You see them in the `up env` output? Maybe double check in the AWS console as well:

- https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#Parameters:sort=Name

**Comment by tj** [comment]
Oh actually, worth noting that `process.env` is a magical object with getters, so maybe `Object.keys()` does not work

**Comment by holic** [comment]
Ah, I forgot to mention that I also tried outputting them manually with e.g. `process.env.MAILGUN_DOMAIN` with no luck.

I do see them in the `up env` output and in the AWS console as well.

Anything else I can try?

**Comment by holic** [comment]
I just figured it out. It looks like the lack of `up.json` with a `name` key is the culprit. I can deploy fine without an `up.json`, which falls back on `package.json`'s `name` I believe, so I was under the impression that I didn't need it. But it seems like the app doesn't know how to load the environment variables without a `name` set up in `up.json`.

**Comment by tj** [comment]
ahhh Up falls back on the directory name, I have an issue open to make up.json required (and .name), it's more or less required for any real app anyway. Thanks for letting me know! One more argument for #386
