### ISSUE TITLE
email verification treated like spam

### ISSUE THREAD

**Issue by dominicbarnes** [apex/up#457]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber? _(working on it, that's what got me this far)_

## Description

When I went to create my apex account, I waited around for the verification email but it seemed to take longer than expected. After a while, I discovered that the email had been flagged as spam by Google and it even went so far as to block the verification link entirely. (Google Inbox _really_ thought this was a phishing scam)

Hopefully this is isolated to me and not widespread, but figured it was a good idea to report just in case.

## Steps to Reproduce

Not sure if it's unique to me, but I only used `up account login` and got this behavior.

**Comment by tj** [comment]
yikes good to know haha, I don't know much about spam heuristics but I hope it's not wide-spread! I'll read up on it, maybe I need to do this DKIM authorization thing

**Comment by sloansparger** [comment]
Same thing happened to me. Gmail wouldn't let me click the link until I clicked "Not spam". Even after it moved to my inbox Google prompted me to make sure I wanted to follow the link.

**Comment by tj** [comment]
@sloansparger I saw that today as well :( I'll look into it tomorrow, I think this DKIM thing is about all I can do to improve that (no idea why it's happening).

**Comment by tj** [comment]
Oh actually, maybe it's because I use the term "identity" in a link hahaha... let me change this

**Comment by tj** [comment]
seems ok now, tried a few of my other addresses. Closing for now but if anyone hits this please let me know :D

**Comment by tj** [comment]
It's back :(

**Comment by tj** [comment]
k, set up DKIM, feels much more immediate now, hopefully that did the trick!
