### ISSUE TITLE
Changelog for PRO version

### ISSUE THREAD

**Issue by cloudkite** [apex/up#460]
Would be nice to have more visibility of what’s changed in PRO, probably good marketing as well for the FOMO factor ;)

**Comment by tj** [comment]
I'll blog about each major release (https://medium.com/@tjholowaychuk) but I agree, needs to have a concise view on the site or something

**Comment by tj** [comment]
Will continue merging to [History.md](https://github.com/apex/up/blob/master/History.md) for now, until I can add a mailing list / RSS feed
