### ISSUE TITLE
up env add doesn't seem to be working

### ISSUE THREAD

**Issue by matthewmueller** [apex/up#465]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`) (version: 0.3.0-pro)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Trying to get environment variables working.

## Steps to Reproduce

First tried: 

```bash
up env add TEST ok
up deploy && up url
```

Then tried it with cleartext as well:

```bash
up env add -c TEST ok
up deploy && up url
```

Here's the verbose output of the encrypted envvars:

```bash
$ fn : up env add TEST ok -v
     4ms     DEBU up version 0.3.0-pro
     0s      DEBU infer name from current working directory "fn"
     0s      DEBU region from aws shared config "ap-southeast-1"
   ⠋ 0s      DEBU track "Add Secret" map[stage: has_desc:false os:darwin arch:amd64 version:   ⠋ 100ms   DEBU track "Add Secret" map[stage: has_desc:false os:darwin arch:amd64 version:   ⠙ 198ms   DEBU track "Add Secret" map[stage: has_desc:false os:darwin arch:amd64 version:0.3.0-pro plan:pro cleartext:false]
     Added TEST

$ fn : up env

     all

     TEST  -  -  Modified 3 seconds ago by itty
```

Here's the server:

```go
package main

import (
	"log"
	"net/http"
	"os"
)

func main() {
	addr := ":" + os.Getenv("PORT")
	http.HandleFunc("/", hello)
	log.Fatal(http.ListenAndServe(addr, nil))
}

func hello(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte(os.Getenv("TEST")))
}
```

**Comment by tj** [comment]
oh I bet this is https://github.com/apex/up/issues/455, does it work if you add `up.json` with an app name? I should make that mandatory ASAP

**Comment by tj** [comment]
```
   λ golang-basic (master): up env set NAME TJ

     Added NAME

   λ golang-basic (master): up

     build: 8 files, 6.7 MB (499ms)
     deploy: complete (6.29s)

   λ golang-basic (master): curl `up url`
Hello TJ
```

**Comment by tj** [comment]
oh I know why, duh, because up.json isn't present in the Lambda it doesn't know what name to fetch

**Comment by matthewmueller** [comment]
Ahhh okay – thanks for looking into this!

You're right I hadn't added an up.json yet. Yah, it might be nice to just pre-populate one when you first run $ up

**Comment by tj** [comment]
I justttt added that earlier today actually! Behaves like an `up init` would now https://github.com/apex/up/commit/d2ed86b562a7bd80b2bd15224458e169d6a2ae1b
