### ISSUE TITLE
up start enters crash loop if you abort a request

### ISSUE THREAD

**Issue by dominicbarnes** [apex/up#472]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

If a client aborts a request to the `up start` proxy, some underlying context get's cancelled, causing the proxy to enter a crash loop. (because the context seems to be re-used so it's always going to error because it's cancelled)

## Steps to Reproduce

**server.js**
```js
const http = require('http')

http.createServer(function (req, res) {
  setTimeout(function () {
    res.writeHead(200, { 'content-type': 'text/plain' })
    res.end('Hello, World!')
  }, 10000)
}).listen(process.env.PORT)
```

**client.js**
```js
const http = require('http')

const req = http.get('http://localhost:8080')
setTimeout(function () {
  req.abort()
}, 1000)
```

**up.json**
```json
{
  "proxy": {
    "command": "node server.js"
  }
}
```

1. `up start -v --address :8080`
2. `node client.js`

The client script will have an uncaught error event and crash. If you watch the server output, you'll notice the following logs:

```
INFO proxy exited code: -1 pid: 24713
DEBU up version 0.3.0-pro  10:38:48pm INFO server is listening duration: 100ms
WARN restarted restarts: 1
INFO retrying idempotent request
ERRO network error: context canceled
WARN restarting
INFO found free port port: 36679
INFO executing command: node server.js
INFO proxy started pid: 24914
INFO waiting for server to listen url: http://127.0.0.1:36679
INFO proxy exited code: -1 pid: 24868
(line 2+ starts repeating here)
```

After this, the server is basically unresponsive, usually serving 502 after a considerable delay.

**Comment by tj** [comment]
hmm I'll check this out today! Tempted to remove the retry logic all-together, I usually forget it's even there. Thanks for the details!

**Comment by tj** [comment]
Seems ok to me with those scripts. I get the cancelled request etc but the two repeated attempts are from [Proxy crash recovery](https://up.docs.apex.sh/#configuration.reverse_proxy.crash_recovery).

Tempted to make that disabled by default since it's surprising, or just remove it entirely for that reason haha. I like the idea of retrying for intermittent database failures etc but that could be handled within app logic if you wanted, so maybe it's worth removing.

**Comment by tj** [comment]
If you set

```
  "proxy": {
    "retry": false
  },
```

and refresh quickly in the browser it'll show those disconnects as well, maybe just the error needs improving "proxy error: context canceled" is pretty obscure

**Comment by dominicbarnes** [comment]
It feels a little _too_ magical for up to handle retries like this. But, if the feature sticks around, should a cancelled client request cause the proxy to error at all?

**Comment by tj** [comment]
Yeah it's pretty magical for a default. I'll think about it some more, I think if it's disabled no one will use it, so might as well get rid of it at that point haha. Hmm I think maybe just a warning would be ok, silent might not be great if you're trying to debug weird client behaviour, but the error Go provides is lame

**Comment by tj** [comment]
closing in favour of #485
