### ISSUE TITLE
up account login throws Error: Bad Request if already logged in

### ISSUE THREAD

**Issue by hhsnopek** [apex/up#474]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I expected to see that I was already logged in when running `up account login` not `Error: Bad Request`

## Steps to Reproduce

- Be logged in to `up` already
- Run `up account login`
- See `Error: Bad Request`

**Comment by tj** [comment]
ahhh I noticed this too, and a few other combinations of `login` for teams etc was funky, I'll check that out

**Comment by tj** [comment]
8fb2917

might add a prompt later, but for now it just dumps:

```
$ up team login

     Already signed in as tj@apex.sh on team tj@apex.sh.
     Use `up team login --team <id>` to join a team
     if you have received an invite.
```
