### ISSUE TITLE
Improve up.json-less directory workflow

### ISSUE THREAD

**Issue by tj** [apex/up#482]
- [x] detect up.json
- [x] validate .name
- [ ] output url? copy? both?
- [x] move logic into deploy cmd (not relevant to the others)
- [x] make sure others error correctly
- [x] add deploy time tracking stat
- [ ] add app type tracking stat
- [x] test for AWS credentials and guide them through that a bit better
- [x] show some helpful error message if they have no AWS_PROFILE, ~/.aws/credentials, or `AWS_*`
- [x] maybe parse ~/.aws/credentials and display those
  - [x] survey alignment

**Comment by lukeed** [comment]
You probably meant this, but I'd display the _profile name_ of the credentials used, not the credentials themselves.

**Comment by tj** [comment]
haha yep, I had it already in a branch but I think I deleted it :(

**Comment by tj** [comment]
Might be worth moving this to `up init` later and implying it, though it really doesn't do that much haha..
