### ISSUE TITLE
InvalidBucketName: The specified bucket is not valid

### ISSUE THREAD

**Issue by kaihendry** [apex/up#498]
Hi! I copied `~/go/src/github.com/apex/up-examples/oss/static-photos` and adjusted `up.json`, but when I try deploy, it says invalid bucket name. I'm unsure how this bucket name (or am I blind?!) is derived in order to fix the issue.

```
~/tmp/video-thumbnail$ up

     build: 19 files, 6.0 MB (427ms)
     deploy: complete (883ms)


     Error: deploying: deploying: ap-southeast-1: creating s3 bucket: InvalidBucketName: The specified bucket is not valid.
        status code: 400, request id: F60CF0168C35DFC0, host id: EU3r4zIXEyihnafqGsSW0ORjIUNfMwDOODZF4GnWkxQoolQJmRdU5YFNR8f13FHNnLXtqCxU6Kw=

~/tmp/video-thumbnail$ up stack plan


     Error: fetching production alias: ResourceNotFoundException: Cannot find alias arn: arn:aws:lambda:ap-southeast-1:407461997746:function:VTHUMB:production
        status code: 404, request id: 204ac6ac-e499-11e7-909d-e1c243e097ba

~/tmp/video-thumbnail$ cat up.json
{
  "name": "VTHUMB",
  "profile": "mine",
  "type": "static",
  "description": "Video tests"
}
~/tmp/video-thumbnail$ up version
0.4.1

```

**Comment by tj** [comment]
hmm mind posting the `up -v` logs? it should create a bucket even if that app name has been used before.

**Comment by tj** [comment]
seems like capitalization isn't allowed in the bucket names, it's probably best to keep them lowercase for the app name as well, I'll add some validation

**Comment by tiago-peres** [comment]
Right, according to [Amazon S3 Bucket Naming Requirements](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html);

- The bucket name can be between 3 and 63 characters long, and can contain only lower-case characters, numbers, periods, and dashes.

- Each label in the bucket name must start with a lowercase letter or number.

- The bucket name cannot contain underscores, end with a dash, have consecutive periods, or use dashes adjacent to periods.

- The bucket name cannot be formatted as an IP address (198.51.100.24).
