### ISSUE TITLE
CREATE_FAILED state

### ISSUE THREAD

**Issue by kaihendry** [apex/up#501]
Hi, what is my tact when I get into this sort of stack? Delete and start again?

```
~/go/src/github.com/kaihendry/lk$ up stack plan


     Error: creating changeset: ValidationError: Stack:arn:aws:cloudformation:ap-southeast-1:407461997746:stack/lk/e1450860-e533-11e7-826d-500c336f38ba is in CREATE_FAILED state and can not be updated.
        status code: 400, request id: 4249ef4b-e552-11e7-875c-7b8994e5d48c

~/go/src/github.com/kaihendry/lk$ up version
0.4.3-pro
```

For example, say you do something manually like leave some stale entries in Route53 & you correct them manually. How do I get out of CREATE_FAILED?

Delete the DNS, delete the stack and `up` from a scratch again ?

```
~/go/src/github.com/kaihendry/lk$ up stack status

     status: Failed to create
     reason: The following resource(s) failed to create: [DnsZoneBrowserinaboxComRecordLkDevBrowserinaboxCom, DnsZoneBrowserinaboxComRecordLkStagingBrowserinaboxCom].

     Development

     domain: lk-dev.browserinabox.com
     endpoint: dexdnwpwsjyf.cloudfront.net

     Staging

     domain: lk-staging.browserinabox.com
     endpoint: d13wuvlxx0yavb.cloudfront.net

     Production

     domain: lk.browserinabox.com
     endpoint: d31ibed38yz3ro.cloudfront.net

     Events

     DnsZoneBrowserinaboxComRecordLkStagingBrowserinaboxCom: Tried to create resource record set [name='lk-staging.browserinabox.com.', type='A'] but it already exists
     DnsZoneBrowserinaboxComRecordLkDevBrowserinaboxCom: Tried to create resource record set [name='lk-dev.browserinabox.com.', type='A'] but it already exists

~/go/src/github.com/kaihendry/lk$ up stack plan


     Error: creating changeset: ValidationError: Stack:arn:aws:cloudformation:ap-southeast-1:407461997746:stack/lk/f4a40eb0-e556-11e7-a9c0-500c336f388e is in CREATE_FAILED state and can not be updated.
        status code: 400, request id: 1d3c8708-e55b-11e7-86ac-85fda9a7687f
```

**Comment by tj** [comment]
when I spoke to AWS they said they were working on better support for "conflicts" with existing o manually tuned resources, that part is out of Up's hands, but to avoid this case you'd have to remove the `"domain"` from the stages

**Comment by kaihendry** [comment]
Thanks for the answer!

**Comment by dpritchett** [comment]
I've had some crazy trouble getting custom domains to work with my route53-managed domain this week - best I can tell right now is that somehow all of my SSL certs are on US-East-1 and all of my cloudfront stuff is happening on US-East-2 and it's all going sideways. I'm happy to provide whatever debug info or access you think might help, @tj. I really dig the experience of taking a little web app to a lambda, I wish I could get this part to work as well 😅

**Comment by dpritchett** [comment]
Edit:  It all looks vaguely like this.  I've only recently learned about verbose mode in `up` let alone the endless reams of CloudFront logs I've been generating, so forgive me if my process doubles back and undermines itself somehow. I'm happy to start from scratch with a new changeset or subdomain or app name if it helps.

![image](https://user-images.githubusercontent.com/147981/35487059-05a4cb50-043d-11e8-9b03-ca74fb1bbb46.png)

**Comment by tj** [comment]
@dpritchett the certs have to be in us-east-1 for API Gateway currently, just some weird AWS requirement. I know one other person had that error, but I couldn't reproduce it, I think it was because the certificate was not verified.

AWS tries to send the verification email to the emails listed [at the bottom here](https://up.docs.apex.sh/#guides.development_to_production_workflow.mapping_custom_domains_to_stages).

I reallllllly wish they would remove this requirement, it's probably the worst thing right now but there's no clean/easy way around it. If you visit the ACM page in us-east-1 you can re-send the emails.

It's really annoying though, I reached out to one of the API Gateway team members to ask about that, if they can remove verification it would be a massive help.

**Comment by dpritchett** [comment]
I've noticed they send me the verification email three times in a row every
time. I finally pulled this off about the 10th try, not sure what happened
honestly. I think pre-filling the domain validations by hand might save me
from some CloudFormation ricketiness.  Thanks again.

**Comment by tj** [comment]
Yeah it just spams a bunch of them haha, but you only have to verify one. Unfortunately I can't really do much to automate that part more, only for domains purchased via up/Route53. I'll have to check my metrics and see how common that is
