### ISSUE TITLE
Question: Provisioning additional resources

### ISSUE THREAD

**Issue by reflog** [apex/up#502]
Hi!
First of all - kudos on an amazing resource! Up is truly an achievement!
I have a question: in my project, I have several services running on AWS utilizing SQS, SNS and RDS.
When I deploy a service with UP I have an option to specify staging/production environment which is awesome, but in order for two environments to use different queues, topics and databases I will have to provision manually a different set of resources per environment - is that correct?

Are there any plans on automate this?

It would be amazing to be able to deploy a staging version of a project together with a different set of AWS resources applicable to it.
Right now I am using Terraform for this, but looking at Up as a future possible solution.

Thanks in advance!

**Comment by tj** [comment]
Thanks :D!

Terraform is definitely the way to go for now, but I'd like to add #453 and/or some way to utilize user-defined CloudFormation templates. Nothing is nailed down so I'm totally open to ideas about how it would be implemented.

More common things like SQS / DynamoDB might be nice to just bake support right into Up

**Comment by reflog** [comment]
Yup. The idea in #453 sounds like it would cover my scenarios! 
I'll subscribe to that thread, very interested to see how this develops!

**Comment by tj** [comment]
awesome I'll close this one :D
