### ISSUE TITLE
Allow overriding NODE_ENV

### ISSUE THREAD

**Issue by tj** [apex/up#505]
Right now it's forced to the stage you're deploying to. I think this is best practice personally, as you could treat "staging" as "production", however React and others have rallied around using `NODE_ENV=production` to strip out development code, so it's pretty much required to allow overriding.

**Comment by yhjor** [comment]
Agree. Since there is lib like `envalid` to validate NODE_ENV to whitelist to `development, test, production`, using `staging` as NODE_ENV will throw error during runtime.

**Comment by matsilva** [comment]
Thanks for this!

**Comment by tj** [comment]
stuff like `NODE_ENV=production up start` will work now as well
