### ISSUE TITLE
Alerts ability to filter out certain status codes

### ISSUE THREAD

**Issue by cloudkite** [apex/up#513]
I'm just in the process of setting up alerts,

I can see the `"metric": "http.4xx"` being great for keeping on top of 404s and 400s however would be nice to be able to exclude certain status codes that you dont care about such as 401s otherwise its going to get very noisy

Otherwise nice work on the alerting ❤️

**Comment by tj** [comment]
Agreed! The granularity CloudWatch provides out of the box it's not great, but I'd like to add #59 which would handle this scenario too
