### ISSUE TITLE
up stack apply seems to put lambda into unhealthly state

### ISSUE THREAD

**Issue by cloudkite** [apex/up#514]
Im deploying with UP from CI and so far its working great.

However when I go `up stack plan` from my local machine it wants to `Modify lambda alias` even though I haven't made any configuration changes. When I executed `up stack apply` it seemed to put the lambda function in a weird state, the endpoint was returning 500 but nothing was appearing in the logs or in cloudwatch events after that point in time.

```
Modify lambda alias
    id: ApiFunctionAliasProduction
    replace: False
```

with -v

```
     6ms     DEBU up version 0.4.4-pro
     0s      DEBU 1 regions from config
     0s      DEBU track "Plan Stack" map[os:darwin arch:amd64 version:0.4.4-pro ci:false plan:pro]
     3.385s  DEBU event stack.plan map[region:us-west-2]
     4.385s  DEBU fetching hosted zones
     2.118s  DEBU deleting changeset
     2.175s  DEBU creating changeset
     295ms   DEBU describing changeset
     751ms   DEBU waiting for completion
     281ms   DEBU describing changeset
     755ms   DEBU waiting for completion
     378ms   DEBU describing changeset
     755ms   DEBU waiting for completion
     2.14s   DEBU describing changeset
     754ms   DEBU waiting for completion
     298ms   DEBU describing changeset
   ⠼ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Modify",
    Details: [{
        CausingEntity: "FunctionVersionProduction",
        ChangeSource: "ParameterReference",
        Evaluation: "Static",
        Target: {
          Attribute: "Properties",
          Name: "FunctionVersion",
          RequiresRecreation: "Never"
        }
      },{
        ChangeSource: "DirectModification",
        Evaluation: "Dynamic",
        Target: {
          Attribute: "Properties",
          Name: "FunctionVersion",
          RequiresRecreation: "Never"
        }
      }],
    LogicalResourceId: "ApiFunctionAliasProduction",
    PhysicalResourceId: "arn:aws:lambda:us-west-2 something something",
    Replacement: "False",
    ResourceType: "AWS::Lambda::Alias",
    Scope: ["Properties"]
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Modify",
    Details: [{
        CausingEntity: "FunctionVersionProduction",
        ChangeSource: "ParameterReference",
        Evaluation: "Static",
        Target: {
          Attribute: "Properties",
          Name: "FunctionVersion",
          RequiresRecreation: "Never"
        }
      },{
        ChangeSource: "DirectModification",
        Evaluation: "Dynamic",
        Target: {
          Attribute: "Properties",
          Name: "FunctionVersion",
          RequiresRecreation: "Never"
        }
      }],
    LogicalResourceId: "ApiFunctionAliasProduction",
    PhysicalResourceId: "arn:aws:lambda:us-west-2 something something",
    Replacement: "False",
    ResourceType: "AWS::Lambda::Alias",
    Scope: ["Properties"]
  },
  Type: "Resource"
}]
     0s      DEBU event platform.stack.plan map[]
   ⠼ 0s      DEBU event stack.plan.complete map[region:us-west-2 duration:18.471749729s]%  
```

**Comment by tj** [comment]
Hmmm interesting, I have seen this once or twice (the missing logs etc) but I thought it was related to deleting and re-creating a stack. I'll see if I can figure out why it wants to change the aliases, thanks for the report!

**Comment by tj** [comment]
Reproduced with one of my demo apps, strange thing is that it wants to set `ApiFunctionAliasProduction` and `ApiFunctionAliasStaging` to the correct versions – which are already aliased – so I'm thinking maybe that's a CloudFormation bug. Even in the event that CloudFormation replaces these aliases, I can't imagine why it would blackhole the data.

**Comment by cloudkite** [comment]
@tj would it be possible to UP to output the version and function name that it wants to alias to? I think this would help with debugging

**Comment by cloudkite** [comment]
I'm thinking possibly it wants to set production alias to LATEST? however latest in my case was not production version since I've more recently deployed to the development stage

**Comment by tj** [comment]
Any time you deploy to non-dev it will show the `Modify` for the aliases, but I can `apply` and requests are ok, likewise after deploying again.

I'm not sure it's related to this 500 issue – I can't reproduce so far – but I think CloudFormation just isn't resilient to outside changes, so it thinks it needs to update again. Might be something AWS should look at, I'd send them mine if I could break it haha.. I'll keep trying

I looked around on the AWS forums for similar issues, seems like there are a few reports but I'm not seeing any solutions.

**Comment by cloudkite** [comment]
@tj I think you are right the 500 is probably coincidental I try reapply again and see how it goes. Thanks for looking into it

**Comment by cloudkite** [comment]
@tj tried to replicate again but didn't get the logs disappearing or the 500 error so maybe just some kinda weird one off error

**Comment by tj** [comment]
Oh man weird, thanks for letting me know! Next time I see it I'll get in touch with AWS, seems super random
