### ISSUE TITLE
`up team status` shows full price rather than the discount-adjusted price

### ISSUE THREAD

**Issue by ElliotChong** [apex/up#516]
## Prerequisites

* [y] I am running the latest version. (`up upgrade`)
* [y] I searched to see if the issue already exists.
* [n] I inspected the verbose debug output with the `-v, --verbose` flag.
* [y] Are you an Up Pro subscriber?

## Description

After signing up for Up Pro with the coupon code `up-early-adopter-57AAA8693354` I executed an `up team status` and see the following output:
```
➜  ~ up team status


     team: foo@gmail.com
     subscription: Up Pro
     card: Visa ending with XXXX
     amount: $20.00/mo USD
     created: December 24, 2017
```

I expected to see the post-coupon amount of $10 rather than $20.

## Steps to Reproduce

1. Sign up for Up Pro with the coupon code `up-early-adopter-57AAA8693354`
2. `up upgrade`
3. `up team status`

---

Thanks for the awesome tooling @tj.

**Comment by tj** [comment]
ahh yep definitely should fix that soon :D – thanks for signing up!
