### ISSUE TITLE
Add proxy default querystring/headers support

### ISSUE THREAD

**Issue by Kikobeats** [apex/up#520]
AWS API Gateway doesn't support default values for querystring/headers values.

Could be a good approach add this support in the proxy layer provided by Up?

It would be easy to implement/usage, Just declaring a configuration field. For example:

```json
"proxy" {
  "headers": {
    "X-API-Key": "MyDefaultApiToken"
  }
}
```

**Comment by tj** [comment]
There's [header injection](https://up.docs.apex.sh/#configuration.header_injection) for the response headers (primarily for static sites). Might be nice to do something for request headers but that's usually pretty easy in-app

**Comment by Kikobeats** [comment]
My problem is more related with using a default usage plan on AWS Gateway and because is not possible I was thinking in add a header by default before execute my lambda function, but I think I can mitigate the problem using separate stages 👍
