### ISSUE TITLE
S3 transfer acceleration

### ISSUE THREAD

**Issue by tj** [apex/up#523]
Doesn't cost that much for this kind of use-case.

http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html

Curious how the results are for other people, most of them say only ~5-10% for me, and 30% for a few, though I would have expected ~30% for a lot which were closer to 5%.

**Comment by nanoxd** [comment]
On a FiOS gigabit connection, I'm seeing significant upload speed gains using transfer acceleration.
My closest node is us-east-1.


| Region         | Accelerated Transfer Percentage Faster |
|----------------|----------------------------------------|
| us-east-1      |                                     4% |
| us-east-2      |                                    42% |
| us-west-1      |                                   383% |
| us-west-2      |                                   235% |
| eu-west-1      |                                   436% |
| eu-west-2      |                                   309% |
| eu-central-1   |                                   648% |
| ap-northeast-1 |                                  1088% |
| ap-northeast-2 |                                  1005% |
| ap-southeast-1 |                                   987% |
| ap-southeast-2 |                                  1052% |
| sa-east-1      |                                   388% |
| ap-south-1     |                                  2807% |
| ca-central-1   |                                    20% |

**Comment by tj** [comment]
@nanoxd damn, not bad haha, thanks!

**Comment by tj** [comment]
Tried a real-world app from western canada to EU.

Before:

```
     build: 24,366 files, 33 MB (3.875s)
     deploy: complete (12.046s)
```

After:

```
     build: 24,366 files, 33 MB (3.757s)
     deploy: complete (7.683s)
```

**Comment by tj** [comment]
next release will have it 👍
