### ISSUE TITLE
App failing to deploy due to Permission erorrs

### ISSUE THREAD

**Issue by samjbmason** [apex/up#526]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description
I have just been migrating some apps and all of them have worked flawlessly apart from one which keeps failing with the following error:
```
 Error: deploying: deploying: us-west-2: The following resource(s) failed to create: [ApiLambdaPermissionProduction, ApiLambdaPermissionDevelopment, ApiDomainProduction, ApiLambdaPermissionStaging].
```
I have checked the `up.json` and can confirm the config is the same as my other apps which have all worked fine. The app itself is just a type of `static` and is a folder of images. The only thing I can think that is causing it is that the overall size might be too big, currently 54MB. 

## Steps to Reproduce

Create a folder of images
Run `up` 
At the final step get the above error

**Comment by tj** [comment]
closing in favour of #551 since they seem really similar.
