### ISSUE TITLE
SSL certificate will be distrusted in M70

### ISSUE THREAD

**Issue by angleman** [apex/up#528]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Getting Chrome error with the default hello world node example. 

`The SSL certificate used to load resources from https://08qss1uxik.execute-api.us-east-1.amazonaws.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`

## Steps to Reproduce

Follow the normal [https://up.docs.apex.sh/#getting_started](https://up.docs.apex.sh/#getting_started) steps for a Node. When you browse with Chrome 63 you will see the error in the browser console.

**Comment by tj** [comment]
I don't think there's anything I can do about this, but I noticed it for cloudfront endpoints as well, sounds like AWS has some work to do

**Comment by tj** [comment]
Closing this one for now, as far as I know there's nothing I can do for their stuff.

**Comment by tech-mindable** [comment]
I think changing the SSLCipher preference list can give better results.

**Comment by apoorvkapil** [comment]
https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

 

"Information For Site Operators

Starting with Chrome 66, Chrome will remove trust in Symantec-issued certificates issued prior to June 1, 2016. Chrome 66 is currently scheduled to be released to Chrome Beta users on March 15, 2018 and to Chrome Stable users around April 17, 2018.

If you are a site operator with a certificate issued by a Symantec CA prior to June 1, 2016, then prior to the release of Chrome 66, you will need to replace the existing certificate with a new certificate from any Certificate Authority trusted by Chrome."

 

As the Symantec certificate for login.salesforce.com dated back to 03/03/2016, the current Chrome Canary (V66) not accepting it.

**Comment by yanlee26** [comment]
SO....，This is normal warn？？/

**Comment by stevoisiak** [comment]
I'm on Chrome 66.0.3359.139, but I still see this warning on some sites.
