### ISSUE TITLE
up breaks on posting to segment while deployed over VPN

### ISSUE THREAD

**Issue by srt32** [apex/up#532]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber? not yet!

## Description

When I run `up` after writing an application similar to https://github.com/apex/up-examples/tree/master/oss/golang-slack I get an error like this one:

```
$ up

     build: 8 files, 6.2 MB (871ms)
     deploy: version 1 (14.956s)
     stack: complete (1m3.149s)
            segment 2018/01/09 14:46:23 error sending request: Post https://api.segment.io/v1/batch: dial tcp 1.1.1.1:443: getsockopt: connection refused
```

with `verbose` the last line looks like

```
   ⠦ 43.272s DEBU flushing analyticssegment 2018/01/09 14:49:16 error sending request: Post https://api.segment.io/v1/batch: dial tcp 1.1.1.1:443: getsockopt: connection refused
```

## Steps to Reproduce

* create an `up` app.
* run `up`
* wait for the build, deploy, and stack steps to complete

I am deploying from my local machine and using a VPN, which is blocking `segment`. Turning off the VPN makes things work just fine (yay) but I'm curious if it's possible to disable writing to Segment. Thanks!

**Comment by tj** [comment]
ahhh sorry about that, if you do `touch ~/.up/disable` it should disable the analytics

**Comment by srt32** [comment]
Fantastic. Thank you!

**Comment by andrewgleave** [comment]
Had the same problem but no VPN.

However DNSCrypt also triggers this – maybe just with certain name servers but certainly with some of the DNSCrypt-provided ones.

Maybe a doc change to help would be enough.

Thanks for an amazing tool!
