### ISSUE TITLE
How to uninstall up if used install.sh

### ISSUE THREAD

**Issue by zhenyulin** [apex/up#533]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [ ] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

found out I can actually install up via npm, so was wondering what's the best way to remove up if installed via install.sh, and haven't found anything in the docs yet.

**Comment by tj** [comment]
```
$ rm `which up`
```

Should do the trick! It’s just a single binary

**Comment by zhenyulin** [comment]
thanks!
