### ISSUE TITLE
Allow customization of IAM func role

### ISSUE THREAD

**Issue by tj** [apex/up#539]
Pretty common to add dynamo/kinesis/s3 access etc, probably time to add this to up.json so people don't have to use the AWS console to manipulate the permissions.

- [ ] add support for defining perms
- [ ] add docs and examples
- [ ] add to json schema

**Comment by kaihendry** [comment]
Is it acceptable just to add the permissions to the up role in the AWS IAM console, after deploying? Though persist IIRC.

**Comment by tj** [comment]
Yep! That's what I've been doing too

**Comment by mgoodings** [comment]
Would save a lot of additional work on our end if we could override the IAM role pragmatically. Currently have to deploy a whole CloudFormation stack to create the role and somehow wire it into Up.

**Comment by tj** [comment]
I'll prioritize this some more, shouldn't take long to add at all, I always end up manually tweaking mine in the console but yeah that's not ideal haha

**Comment by mgoodings** [comment]
Any expected ETA on this one? Sorry to pressure.

**Comment by tj** [comment]
@mgoodings I'm not sure yet how to best handle this since it's not part of the CloudFormation stack, it wouldn't be part of the `up stack plan/apply` workflow because of that which makes it a little awkward :'(

**Comment by kaihendry** [comment]
Just a note that https://github.com/apex/up/commit/9f4facaf37138f1eb6640bbbda91cf0ac7873973 seems to overwrite my edits to the function's inline policy. Didn't expect that. :sweat_smile:
