### ISSUE TITLE
Service latency comparisons

### ISSUE THREAD

**Issue by tj** [apex/up#54]
So people have an idea what to expect latency-wise.

- locally (one region)
- globally (N regions)

**Comment by tj** [comment]
will blog about this later

**Comment by pontusab** [comment]
I have a simple service in (eu-central-1) - Frankfurt and the latency in Europe is great, but what i thought was that with API-gateway the latency outside Europe would be good too. I wired up ping and can see request take up to 2s from Ohio and using your other tool `latency` I got a big difference from outside Europe.

Is there something I can do currently to get better response time?

Thanks

<img width="830" alt="screen shot 2018-09-18 at 23 55 33" src="https://user-images.githubusercontent.com/655158/45719053-6bf1c100-bb9f-11e8-969b-4278779e50cc.png">

**Comment by tj** [comment]
@pontusab at the moment only a single region at a time is supported. I'd like to support deploying to all 15 or so regions, but it would need to have some kind of fan-out system so deploys are still fast. If your data isn't globally distributed as well it may not really help much

I think if AWS is smart they'll do this part for us, deploy to one region and have it apply to all, like Lambda@edge, I'm not sure it's worth implementing all of that in Up itself right now but maybe!

**Comment by pontusab** [comment]
@tj thanks for the explanation, so there is not much I can do to get my API to response faster globally currently?

**Comment by tj** [comment]
Not easily at the moment, once global database are more prevalent I'll prioritize that some more if AWS hasn't beat me to it

**Comment by pontusab** [comment]
@tj Cool, thanks. We will start using Aurora Serverless and that are available in 5 regions. Looking forward to multi region then 🥇
