### ISSUE TITLE
Add development alias

### ISSUE THREAD

**Issue by tj** [apex/up#542]
Currently dev points to $LATEST

- [x] tweak
- [x] docs
- [x] QA

**Comment by cloudkite** [comment]
👍  The old behaviour was really confusing. As whenever I deployed to production that would now be the LATEST version and development would be pointing to the production version with production env vars baked in. I assume this problem goes away with this change?

**Comment by tj** [comment]
hahah yeah agreed, that's definitely not desirable, and yep! 

The case used to be that $LATEST helped due to the version limit you could have in Lambda, but I don't even see mention of a limit anymore in the docs.
