### ISSUE TITLE
`up team login` never sends a confirmation email

### ISSUE THREAD

**Issue by iamclaytonray** [apex/up#544]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

After running `up team login`, a confirmation email is never sent, thus, I get `verify: Check your email for a confirmation link` until `Error: getting access token: context deadline exceeded` from iTerm. I waited for about 5 minutes and tried 3 times.

## Steps to Reproduce

High Sierra - 10.13.2 (17C88)

`up team login`

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
Hmm did it end up in spam? Sometimes AWS is a bit slow with delivery but I haven't seen it take longer than maybe a minute, I just tried and got mine in a few seconds.

**Comment by iamclaytonray** [comment]
I feel pretty stupid... 😂

**Comment by iamclaytonray** [comment]
Thanks @tj
