### ISSUE TITLE
Better error for insufficient permissions

### ISSUE THREAD

**Issue by tj** [apex/up#546]
Some people are hitting this if you don't have sufficient permissions. Pretty obscure looking error, so ideally we spit out a description of the problem and point to the IAM policy in the docs.

```
Error: deploying: deploying: iam: fetching role: InvalidClientTokenId: The security token included in the request is invalid.
```

- [ ] reproduce
- [ ] add nicer error

**Comment by tj** [comment]
hmm not sure exactly what that error is actually, I can't reproduce it easily. I'll reopen if more people hit this.

**Comment by maticrivo** [comment]
hey @tj i just hit this error..
i have no idea why

**Comment by tj** [comment]
@maticrivo the error message seems really vague and confusing but from [Stackoverflow](https://stackoverflow.com/questions/34582318/how-can-i-resolve-the-error-the-security-token-included-in-the-request-is-inval) I'm seeing that maybe it's the wrong credentials? Worth double checking `~/.aws/credentials` or maybe generate a new pair in the console.

Let me know if that helps at all!

**Comment by benbonnet** [comment]
just hit that one, turned out that I had olds credentials set as env vars (see: https://stackoverflow.com/a/41850256)
