### ISSUE TITLE
Error: deploying ... The following resource(s) failed to create:

### ISSUE THREAD

**Issue by kaihendry** [apex/up#548]
0.4.6-pro

## Description

Unable to deploy an app I previously failed to deploy.

     Error: deploying: deploying: ap-southeast-1: The following resource(s) failed to create: [ApiDomainDevelopment, ApiLambdaPermissionProduction, ApiLambdaPermissionDevelopment, ApiLambdaPermissionStaging].

## Steps to Reproduce

Not sure I can. Tried deploying this before and it failed on the cert step. 

I've since run `up stack delete`, but now it fails to re-deploy. I'm not where to begin debugging this. 

My workaround is to remove

        "stages": {
                "development": {
                        "domain": "blah.example.com"
                }
        },

up deploy, and then try to hook it it up in API gateway. But the trouble is there is no Path option. All I see is [Define in Path], which becomes a * in the mapping. And it doesn't appear to work at all, unless CloudFront is taking forever.

I feel at this stage my only choice is to choose another App name I guess there is some CloudFormation residue somewhere in some region blocking this? Is that a fair assumption ?

**Comment by tj** [comment]
Hmm does `up stack` show any errors? Or maybe `/cloudformation` in the AWS console? 

I did hit a case twice I think where I had to rename my app due to some strange left-over API Gateway state (guessing, could be somewhere else), but this looks a bit different.

**Comment by kaihendry** [comment]
Ah, didn't know about the extra info of `up stack`.

I see when I delete in CloudFormation there is some problem deleting all base path mappings. Ah, going through API gateway and deleting APIs has got me further. I think I have proper `up stack delete` now... 

But now I have an issue deploying: [creating s3 bucket: creating bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.](https://s.natalian.org/2018-01-18/1516257507_2548x1398.png)

Ok, solved by rb --force that bucket.

Argh, still have an issue with it not being able to find a previously (unapproved ... took forever) cert. I'm going to change app name and subdomain now and move on.

**Comment by tj** [comment]
Almost sounds like CloudFormation is refusing to delete some things if they were tweaked manually (base path mappings?)
