### ISSUE TITLE
Account level S3 bucket

### ISSUE THREAD

**Issue by tj** [apex/up#550]
Right now we create one per func, but in an account shared with other types of applications it's maybe a bit ugly. We could probably change this to just use one bucket with a prefix, unless anyone has objections there haha. Personally I'm not worried about since all my stuff is serverless/automated, I don't even look at my list of buckets.

**Comment by kaihendry** [comment]
Can I safely delete the buckets? It's just for staging isn't it?

**Comment by tj** [comment]
Any which are actively used would need to stick around since cold start will pull the zips from S3, but if the function isn't in use anymore it should be fine

**Comment by kaihendry** [comment]
Sorry, how does one migrate (or clean up) from lots of up buckets on my S3 to one?

**Comment by tj** [comment]
If you don't think you'll need the old versions it should be ok to delete buckets after the app has been deployed at least once with the new bucket. Should have done a single bucket in the first place 😢
