### ISSUE TITLE
S3 with cloud-front for static sites and apps

### ISSUE THREAD

**Issue by vespertilian** [apex/up#553]
Would you be open to having a deployment option which used the s3 bucket with Cloudfront as a static site, instead of using API gateway? This is how I have deployed static site previously. 

I assume this is cheaper than deploying to API gateway, and paying per request. 

Are there benefits of API gateway regarding static sites that I am missing?

**Comment by tj** [comment]
I have #62, which in front of API Gateway would be pretty much the same effect (and cost)—while also letting you also generate dynamic content with HTTP caching, say per user or based on their location etc. 

I want to explore Lambda@Edge some more for static stuff too.

**Comment by vespertilian** [comment]
Ok thanks, I will follow that issue.

**Comment by tj** [comment]
closing for the other one
