### ISSUE TITLE
Instruction in invitation email wrong

### ISSUE THREAD

**Issue by timsuchanek** [apex/up#554]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

When being invited to a team per email, the instruction states
```sh
up account login --email my@mail.com --team team-name
```
Instead it should say
```sh
up team login --email my@mail.com --team team-name
```

## Steps to Reproduce

Invite someone per mail.

**Comment by tj** [comment]
yikes I must have never deployed that, thanks for letting me know! fixed
