### ISSUE TITLE
Stuck on the first login of a newly invited team member

### ISSUE THREAD

**Issue by agurtovoy** [apex/up#560]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

`up` is stuck on the first login of a newly invited team member:

<img width="1130" alt="screen shot 2018-01-26 at 11 05 54 pm" src="https://user-images.githubusercontent.com/3394202/35468866-8942f82a-02ed-11e8-81ec-4a726943a4b2.png">

The email never arrives. We tried running the command multiple times, checked Spam, etc.

**Comment by agurtovoy** [comment]
In case it's not clear from the context, the original email invite that is sent out when you *invite* a new team member arrived with no issues.

**Comment by tj** [comment]
Hmm I don't see any error logs, makes me wonder how reliable AWS' SES email stuff actually is. Not sure what to suggest off-hand, I'll dig around and see if there's a way to improve SES deliverability

**Comment by agurtovoy** [comment]
The weird thing is that this appears to be an issue with this particular email address only, and this particular email notification. I removed the address from the team and re-added it again, and the team invitation email shows up reliably and in seconds, so it's just the sign in one. Hmm, let me check one more thing...

**Comment by agurtovoy** [comment]
So this particular email is actually a Google group. I checked and re-checked the spam folder in my inbox, but each Google group also has its own "moderation queue" for suspicious emails, and that's where the sign in emails were stuck. I guess the invites are not "suspicious".

Sorry for the false alarm! I guess you can view this as a reassurance that SES does work, and when someone reports a delivery issue again, it's more likely than not that it's something on their side :)
