### ISSUE TITLE
Error Pages responses for non text/html requests

### ISSUE THREAD

**Issue by naartjie** [apex/up#561]
Hi,

## Description

I got tripped up by the [Error Pages](https://up.docs.apex.sh/#configuration.error_pages) default behaviour [changing](https://github.com/apex/up/commit/f47c5c7f88442ba25397f7ce7d31117f736cae13) when I upgraded from `0.4.4` to `0.4.10`.

I'm not sure if this is a bug, or if it's intentional, but when my client is requesting JSON, and my server is sending JSON, should error pages kick in at all, regardless of `error_pages` setting in `up.json`?

## Steps to Reproduce

`app.js`:

```js
const http = require('http')
const { PORT = 3000 } = process.env

http.createServer((req, res) => {
  res.statusCode = 400
  res.setHeader('Content-Type', 'application/json')
  res.send(JSON.stringify({ error: 'message' }))
}).listen(PORT)
```

Run:
```sh
up start
```

In another terminal:
```sh
curl -H "Content-Type: application/json" -H "Accept: application/json" -d '{"key1":"value1"}' localhost:3000
```

Expected: 
```
{"error":"message"}
```

Actual: 
HTML page rendered by `up`.

**Comment by tj** [comment]
hmm I'll check this out today, I thought I had that case covered with tests!

**Comment by tj** [comment]
weird I get `res.send is not a function` and a 502, however if I fix that to `res.end()` I get `{"error":"message"}` as expected

**Comment by naartjie** [comment]
@tj doh, sorry about the inaccurate repro, here it is corrected:

`up.json`
```json
{
  "name": "myapp"
}

```

`app.js`
```js
const http = require('http')
const { PORT = 3000 } = process.env

http.createServer((req, res) => {
  res.statusCode = 400
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ error: 'message' }))
}).listen(PORT)
```

This works:
```sh
$ curl -H "Accept: application/json" localhost:3000
{"error":"message"}
```

While this renders the error page:
```sh
$ curl -H "Accept: application/json, */*" localhost:3000
```

So it's todo with the `*/*` in the Accept header. It's super minor, so feel free to close this, I just thought it should prefer the `application/json` response if we're being picky.

**Comment by tj** [comment]
Ahhh hmm yeah I think you're right. Right now it doesn't take into account that the response is already one of the accepted types, but 👍  from me

**Comment by naartjie** [comment]
Yeah, actually thinking about it now, prolly best to close this. It's such a small thing. I doubt many people will hit this `*/*` case when making requests from a client.

**Comment by tj** [comment]
Sounds good, yea I think curl does `*/*` by default which makes it a little awkward when testing hahah, but I think otherwise the behaviour is correct
