### ISSUE TITLE
An option to treat writes to stderr as INFO-level logs

### ISSUE THREAD

**Issue by agurtovoy** [apex/up#565]
["Currently writes to stderr are considered ERROR-level logs"](https://up.docs.apex.sh/#guides.mastering_logging.plain_text) doesn't play nice with [debug](https://www.npmjs.com/package/debug)'s default logging to stderr. 

A specific use case where this causes issues is enabling DEBUG logging in production using `up env` to troubleshoot something. It works awesomely (after a re-deploy), except that  `up` logs get filled with "error" rather than "info" entries.

It'd be nice to have an option in `up` config to treat all plain text writes as "info" entries regardless of whether they are written to stderr or stdout.

A workaround on the user side is to wrap `debug` to override the default output (and replace all the imports).

**Comment by tj** [comment]
Any ideas for config option names? I can't think of anything great, but we have `"logs": { "disable": true }` already so we can shove it in there

```json
{
  "name": "app",
  "environment": {
    "DEBUG": "myapp"
  },
  "logs": {
    "stderr_as_error": false
  }
}
```

**Comment by tj** [comment]
oh I know. I'll have this in a few minutes

**Comment by agurtovoy** [comment]
Awesome, thanks so much!
