### ISSUE TITLE
Default error_pages.dir to static.dir

### ISSUE THREAD

**Issue by chrismalek** [apex/up#570]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I can't get the error.html page to be served. I am using a Hugo Static site. I have tried to disable the error page and it still does not find it.  I am wondering if it is because I am serving the static site from a different directory.

I have the file here: /public/error.html

```
  "type": "static",
    "static": {
        "dir": "public"
    },

```

I don't have any config around error pages. From the docs, I thought just the existence of error.html that it should serve that file instead of the Up built in one.

## Steps to Reproduce

* Create a static site with the dir set to a subdirectory.
* Create error.html page
* deploy and go to a non-valid page to generate 404

**Comment by tj** [comment]
Ahh you're right, for now I have error pages and static files as separate middleware so they're unaware of each other. If you add `"error_pages": { "dir": "public" }` it should pick it up from the right spot.

Let's leave this open though, I could have it default to `static.dir` to avoid confusion there!

**Comment by chrismalek** [comment]
That is working working by using error_pages.dir.  When you get a second can you update the docs to show that dir is an option on error_pages?  https://up.docs.apex.sh/#configuration.error_pages.

**Comment by tj** [comment]
Oh wow thought I had it documented, will do!

**Comment by tj** [comment]
decided against mixing defaults across settings for now, might get too magical, improving the docs is definitely the way to go for now I think
