### ISSUE TITLE
Cleanup rollbacks?

### ISSUE THREAD

**Issue by robinvdvleuten** [apex/up#573]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Cleanup old rollbacks or configure a maximum of rollbacks to keep. Maybe a property in `up.json`?

**Comment by tj** [comment]
not at the moment but it definitely needs to eventually be added, are you hitting any limits? I'll close this for #322 and rename that a bit

**Comment by robinvdvleuten** [comment]
I do not run into any limits yet, but I can imagine you will run into a lot of versions when using continuous deployment.

**Comment by tj** [comment]
true yeah, probably makes sense to build it in to the deployment cycle like in [apex](https://github.com/apex/apex) or maybe `up prune` or similar

**Comment by robinvdvleuten** [comment]
Maybe add it as a property to `up.json`? Something like `https://www.npmjs.com/package/serverless-prune-plugin` did.
