### ISSUE TITLE
up start with go on osx sierra: ./server: No such file or directory

### ISSUE THREAD

**Issue by davidjnelson** [apex/up#580]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?  -- would like to be, but local development is a must have first

## Description

up start fails with error `./server: No such file or directory`

## Steps to Reproduce

running osx 10.12.6 and bash
Installed up.
Installed go.
Configured gopath and goroot to:

`export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin`

created iam user
Ran `up` fine, created and deployed to staging and prod environments
ran `up start` for local dev, got `ERRO sh: ./server: No such file or directory -`
ran `up build`, created server binary
ran up start, got `./server: cannot execute binary file`
ran `file server`, got `server: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped`
searched the docs, github issues, and google.  new to go.  maybe  missing something obvious but this is the only way I can see to sort it out at this point, thanks.

## Love Up?

There are some great features.  Local dev is super annoying using node with aws sam, so I'm looking into something more solid.  I could love up if I got it working!

**Comment by tj** [comment]
Hey hey!

You can specify the command to run via [up start -c](https://up.docs.apex.sh/#commands.start.examples), or [stage overrides](https://up.docs.apex.sh/#configuration.stage_overrides), for example:

```json
{
  "name": "app",
  "stages": {
    "development": {
      "proxy": {
        "command": "go run main.go"
      }
    }
  }
}
```

I should make that the default for Go, sometimes having `gin` in there as shown in the docs is nice too for hot reloading. Hope that helps! I'll open an issue for making that the default

**Comment by davidjnelson** [comment]
oh sweet that fixed it!  thanks @tj !!!  It would be cool if gin was the default somehow, hot reloading is super useful.  thanks :-D
