### ISSUE TITLE
is active warming working?

### ISSUE THREAD

**Issue by davidjnelson** [apex/up#591]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Active warming doesn't appear to be working.

## Steps to Reproduce

I've done what I can to make sure things are fast, I'm not emitting source maps at build, as well as concatenating all non external requires, and running that bundle with NODE_ENV=production.

I am using cloudflare for dns with the cdn currently turned off.

Running `up start` locally with the same command I use for prod/staging, I see 2000ms for express to start, with 1ms-50ms after that.

I have active warming turned on in my up.json and subscribed to pro.  Originally I had it at 15m, but for the sake of testing I set it to 1m temporarily.

`
"lambda": {
    "warm": true,
    "warm_count": 1000,
    "warm_rate": "1m"
}
`

I then did `stack plan` and saw output, then `stack apply`.

It seemed to work as `stack apply` showed a progress bar.  Oddly though, it moved down the console before it got to 100%, I've seen 80% and 62%.

I did an `up deploy staging` and an `up deploy production` next.

I waited 2 minutes to ensure the warmers had time to execute.

I poked around in my cloudwatch events as I imagine that's where this would be configured, since that's how I had done single concurrency warming manually before.  Didn't see anything there.

Tailed the logs for anything longer than 1500ms with `up logs 'production duration > 1500' -f`

Opened chrome network tools, and the first request takes 4-5 seconds.  Subsequent requests are between 100ms and 350ms, which also seems a little slow, perhaps it's express overhead vs the barebones setup I had before.

The logs show it's standard lambda cold start of 1.2s to 1.9s + express starting:

`12:25:22pm INFO started server - duration: 4.218s stage: production version: 22`

Ran wrk against it to throw some load at it:

`wrk -d 5s -t 4 -c 1000 -d 1m --latency https://<mysitehere>`

wrk apparently has issues, as it logs max latency as 1.98s, but in the tailed logs I see:

`

12:25:24pm INFO started server - duration: 4.157s stage: production version: 22
  12:25:24pm INFO started server - duration: 4.132s stage: production version: 22
  12:25:27pm INFO started server - duration: 4.105s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.145s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.124s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.199s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.115s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.215s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.118s stage: production version: 22
  12:25:28pm INFO started server - duration: 4.121s stage: production version: 22
  12:25:33pm INFO started server - duration: 4.113s stage: production version: 22
  12:25:33pm INFO started server - duration: 4.169s stage: production version: 22
  12:25:34pm INFO started server - duration: 4.156s stage: production version: 22
  12:25:34pm INFO started server - duration: 4.134s stage: production version: 22
  12:25:35pm INFO started server - duration: 4.167s stage: production version: 22
  12:25:37pm INFO started server - duration: 4.122s stage: production version: 22
  12:25:39pm INFO started server - duration: 4.242s stage: production version: 22
  12:25:40pm INFO started server - duration: 4.146s stage: production version: 22
  12:25:41pm INFO started server - duration: 4.291s stage: production version: 22
  12:25:41pm INFO started server - duration: 4.161s stage: production version: 22
  12:25:43pm INFO started server - duration: 4.134s stage: production version: 22
  12:25:46pm INFO started server - duration: 4.258s stage: production version: 22
  12:25:46pm INFO started server - duration: 4.173s stage: production version: 22
  12:25:47pm INFO started server - duration: 4.129s stage: production version: 22
  12:25:47pm INFO started server - duration: 4.13s stage: production version: 22
  12:25:52pm INFO started server - duration: 4.212s stage: production version: 22
  12:25:53pm INFO started server - duration: 4.118s stage: production version: 22
  12:25:53pm INFO started server - duration: 4.13s stage: production version: 22
  12:25:54pm INFO started server - duration: 4.199s stage: production version: 22
  12:25:58pm INFO started server - duration: 4.12s stage: production version: 22
  12:26:00pm INFO started server - duration: 4.14s stage: production version: 22
  12:26:06pm INFO started server - duration: 4.117s stage: production version: 22
  12:26:08pm INFO started server - duration: 4.155s stage: production version: 22
  12:26:17pm INFO started server - duration: 4.138s stage: production version: 22
  12:26:21pm INFO started server - duration: 4.119s stage: production version: 22

`

Output from wrk:

`

Running 1m test @ <mysitehere>
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   214.84ms  112.09ms   1.98s    89.75%
    Req/Sec   127.71     48.33   300.00     71.12%
  Latency Distribution
     50%  181.01ms
     75%  222.83ms
     90%  329.38ms
     99%  695.69ms
  28430 requests in 1.00m, 0.91GB read
  Socket errors: connect 754, read 0, write 0, timeout 1303
  Non-2xx or 3xx responses: 1146
Requests/sec:    473.41
Transfer/sec:     15.52MB

`

Ran work a second time, far less cold starts:

`

  12:57:40pm INFO started server - duration: 3.117s stage: production version: 25
  12:57:45pm INFO started server - duration: 4.132s stage: production version: 25
  12:57:45pm INFO started server - duration: 4.159s stage: production version: 25
  12:57:45pm INFO started server - duration: 4.176s stage: production version: 25
  12:57:46pm INFO started server - duration: 4.102s stage: production version: 25
  12:57:47pm INFO started server - duration: 4.111s stage: production version: 25
  12:57:51pm INFO started server - duration: 4.139s stage: production version: 25
  12:57:57pm INFO started server - duration: 4.212s stage: production version: 25
  12:58:05pm INFO started server - duration: 4.142s stage: production version: 25

`

Second wrk output:

`

4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   320.42ms  178.35ms   2.00s    91.59%
    Req/Sec   147.22     45.32   310.00     68.09%
  Latency Distribution
     50%  268.75ms
     75%  337.54ms
     90%  470.96ms
     99%    1.13s 
  35065 requests in 1.00m, 1.15GB read
  Socket errors: connect 754, read 0, write 0, timeout 575
  Non-2xx or 3xx responses: 387
Requests/sec:    584.04
Transfer/sec:     19.64MB

`

On the third run, I only got 3 cold start log entries:

`

  01:03:09pm INFO started server - duration: 4.175s stage: production version: 25
  01:03:10pm INFO started server - duration: 4.151s stage: production version: 25
  01:03:10pm INFO started server - duration: 4.111s stage: production version: 25

`

Third run work output:

`

4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   334.40ms  169.54ms   1.98s    91.59%
    Req/Sec   145.23     47.91   350.00     72.93%
  Latency Distribution
     50%  286.03ms
     75%  354.65ms
     90%  474.46ms
     99%    1.09s 
  34558 requests in 1.00m, 1.14GB read
  Socket errors: connect 754, read 0, write 0, timeout 504
  Non-2xx or 3xx responses: 392
Requests/sec:    575.48
Transfer/sec:     19.36MB

`

Ran it a fourth time and the results were pretty much identical to the third run.

What's super perplexing is that when I went back to chrome and loaded it manually, it showed it took 5.13 seconds to load in the network tab.

Am I configuring something wrong?  Thanks!  :-)

## Love Up?

oh yeah, up rocks!!!  ironing out a few kinks, but definitely digging it.

**Comment by davidjnelson** [comment]
for now I turned on cloudwatch events that call the lambda 5 times per stage.

**Comment by tj** [comment]
Hmm does `up stack` output any errors at the bottom? I really need to improve the error reporting for `apply` if there's an issue.

Make sure the user/role for the `up` cli has access to `events:*` like in https://up.docs.apex.sh/#aws_credentials.iam_policy_for_up_cli. I contemplated providing a managed policy, I'm not sure people would trust some centralized policy but I'll think about that unless you have any suggestions too that would be awesome, it's definitely annoying

**Comment by lukeed** [comment]
I'd be down for managed policy, or have a file included in the repo here (constant, easily accessible) that tracks the recommended/necessary policies, rather than hunting it down from the Up docs & hoping it's up-to-date.

**Comment by tj** [comment]
Yeah managed might be a nice option at least, for side-projects it's not a huge concern, but I imagine most companies would prefer to manage and audit their own. I think I remember AWS having some kind of "do you accept these policy changes?" type of feature though

**Comment by davidjnelson** [comment]
I don't remember seeing any errors with `up stack plan` or `up stack apply`.

Here's my current `up stack plan -v` output:

`

     5ms     DEBU up version 0.5.2-pro
     0s      DEBU 1 regions from config
     0s      DEBU track "Plan Stack" map[plan:pro os:darwin arch:amd64 version:0.5.2-pro ci:false]
     0s      DEBU event stack.plan map[region:us-east-1]
     2ms     DEBU fetching aliases
     0s      DEBU fetching production alias
     0s      DEBU fetching development alias
     816ms   DEBU fetching staging alias
     2ms     DEBU fetched staging alias (14)
     111ms   DEBU development has no alias, defaulting to staging
     185ms   DEBU fetched development alias (14)
     0s      DEBU fetched production alias (15)
     1.032s  DEBU fetching existing certs
     857ms   DEBU fetching hosted zones
     985ms   DEBU deleting changeset
     2.534s  DEBU creating changeset
     164ms   DEBU describing changeset
     755ms   DEBU waiting for completion
     551ms   DEBU describing changeset
     754ms   DEBU waiting for completion
     589ms   DEBU describing changeset
     751ms   DEBU waiting for completion
     298ms   DEBU describing changeset
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGateway4XXErrorSumPeriod300Threshold50",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGateway4XXErrorSumPeriod300Threshold50",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGateway5XXErrorSumPeriod60Threshold1",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGateway5XXErrorSumPeriod60Threshold1",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGatewayCountSumPeriod60Threshold100",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGatewayCountSumPeriod60Threshold100",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGatewayLatencyAveragePeriod300Threshold1000",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertAWSApiGatewayLatencyAveragePeriod300Threshold1000",
    ResourceType: "AWS::CloudWatch::Alarm"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertActionEmailBackend",
    ResourceType: "AWS::SNS::Topic"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertActionEmailBackend",
    ResourceType: "AWS::SNS::Topic"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertActionEmailBackendSubscription",
    ResourceType: "AWS::SNS::Subscription"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "AlertActionEmailBackendSubscription",
    ResourceType: "AWS::SNS::Subscription"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainProduction",
    PhysicalResourceId: "prod-up.<mydomain>.com",
    ResourceType: "AWS::ApiGateway::DomainName"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainProduction",
    PhysicalResourceId: "prod-up.<mydomain>.com",
    ResourceType: "AWS::ApiGateway::DomainName"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainProductionPathMapping",
    PhysicalResourceId: "<resourceid>",
    ResourceType: "AWS::ApiGateway::BasePathMapping"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainProductionPathMapping",
    PhysicalResourceId: "<resourceid>",
    ResourceType: "AWS::ApiGateway::BasePathMapping"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainStaging",
    PhysicalResourceId: "staging-up.<mydomain>.com",
    ResourceType: "AWS::ApiGateway::DomainName"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainStaging",
    PhysicalResourceId: "staging-up.<mydomain>.com",
    ResourceType: "AWS::ApiGateway::DomainName"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainStagingPathMapping",
    PhysicalResourceId: "<resourceid>",
    ResourceType: "AWS::ApiGateway::BasePathMapping"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "ApiDomainStagingPathMapping",
    PhysicalResourceId: "<resourceid>",
    ResourceType: "AWS::ApiGateway::BasePathMapping"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "DnsZone<mydomain>ComRecordProdUp<mydomain>Com",
    PhysicalResourceId: "prod-up.<mydomain>.com",
    ResourceType: "AWS::Route53::RecordSet"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "DnsZone<mydomain>ComRecordProdUp<mydomain>Com",
    PhysicalResourceId: "prod-up.<mydomain>.com",
    ResourceType: "AWS::Route53::RecordSet"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "DnsZone<mydomain>ComRecordStagingUp<mydomain>Com",
    PhysicalResourceId: "staging-up.<mydomain>.com",
    ResourceType: "AWS::Route53::RecordSet"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Remove",
    LogicalResourceId: "DnsZone<mydomain>ComRecordStagingUp<mydomain>Com",
    PhysicalResourceId: "staging-up.<mydomain>.com",
    ResourceType: "AWS::Route53::RecordSet"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingEvent",
    ResourceType: "AWS::Events::Rule"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingEvent",
    ResourceType: "AWS::Events::Rule"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunction",
    ResourceType: "AWS::Lambda::Function"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunction",
    ResourceType: "AWS::Lambda::Function"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunctionPermission",
    ResourceType: "AWS::Lambda::Permission"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunctionPermission",
    ResourceType: "AWS::Lambda::Permission"
  },
  Type: "Resource"
}]
   ⠸ 0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunctionRole",
    ResourceType: "AWS::IAM::Role"
  },
  Type: "Resource"
     0s      DEBU event platform.stack.plan.change map[change:{
  ResourceChange: {
    Action: "Add",
    LogicalResourceId: "WarmingFunctionRole",
    ResourceType: "AWS::IAM::Role"
  },
  Type: "Resource"
}]
     0s      DEBU event platform.stack.plan map[]
   ⠸ 0s      DEBU event stack.plan.complete map[region:us-east-1 duration:10.389252224s]

`

I did add domains to staging and prod, but realized I didn't need them managed by up so removed them.  I wonder if this could be causing issues?

I'm using an IAM user I created with the permissions here: https://up.docs.apex.sh/#aws_credentials.iam_policy_for_up_cli

Let me check it to ensure it has events:* in case that is new.  Oh wow, the one I copied a few days ago looks different than the one there now.  Let me update it and try again.  Oh, that's weird, when I paste in the policy in the aws console in the raw json section aws changes it significantly.  It's removing events:* completely, but it does have:

`

{
            "Effect": "Allow",
            "Action": [
                "cloudwatch:*"
            ],
            "Resource": "*"
        },

`

which I would think would cover events.

When I preview in the aws console UI it says 'CloudWatch Events' is set to 'Full access
     All resources     None'.

Now the json in the policy looks right and contains events:*

Here's my `up stack apply -v` output:

`

4ms     DEBU up version 0.5.2-pro
     0s      DEBU 1 regions from config
   ⠋ 0s      DEBU track "Apply Stack" map[stage_count:3 os:darwin arch:amd64 ci:false plan:pro dns_zone_count:0 stage_domain_count:0 alerts     0s      DEBU track "Apply Stack" map[stage_count:3 os:darwin arch:amd64 ci:false plan:pro dns_zone_count:0 stage_domain_count:0 alerts_count:4 actions_count:1 version:0.5.2-pro]
     0s      DEBU event stack.apply map[region:us-east-1]
     1.574s  DEBU fetching existing certs
     819ms   DEBU event platform.stack.apply map[changes:16]
     22.151s DEBU event platform.stack.report map[total:14 complete:0]
     0s      DEBU event platform.stack.report.complete map[duration:22.150867766s total:14 complete:0]
     0s      DEBU event platform.stack.apply.complete map[changes:16 duration:22.969639321s]
   ⠴ 0s      DEBU event stack.apply.complete map[duration:24.544358008s region:<region>]

`

I do not see any new cloudwatch event rules in the aws console UI now though.  I'm not really sure how the active warming is implemented though, maybe it's done some other way.

Ok, now I'll shut off my 5 concurrency cloudwatch event warmers and throw wrk at it with `wrk -t 4 -c 1000 -d 1m --latency https://<domain>`

wrk looks pretty good:

`

  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   294.73ms  181.44ms   2.00s    91.97%
    Req/Sec   133.91     45.85   270.00     68.75%
  Latency Distribution
     50%  242.95ms
     75%  340.06ms
     90%  438.66ms
     99%    1.07s 
  28607 requests in 1.00m, 0.93GB read
  Socket errors: connect 754, read 0, write 0, timeout 998
  Non-2xx or 3xx responses: 749
Requests/sec:    475.98
Transfer/sec:     15.80MB

`

and I only count 8 cold starts in the logs.

I'll try again in a bit to make sure it wasn't my cloudwatch event rules I set up manually still warming things, and perhaps the wrk load I threw at it really not needing more than 5-10 concurrent lambdas.  It would be really nice if aws would expose the concurrent lambdas executing metric.

Is there any way to look in the aws ui console and see if active warming is enabled properly?

Thanks so much!

**Comment by davidjnelson** [comment]
Tried it again with `wrk -t 4 -c 1000 -d 1m --latency (end user url)` and got 16 invocations greater than 1500ms.  Also did a manual browser test and got a 4 second response from that before running wrk on it.

**Comment by tj** [comment]
Yep it's implemented via cloudwatch events and Lambda, so you should see a `<name>-warming` Lambda function and the scheduled event, after running `up stack apply` (I see the `AWS::Events::Rule` in the plan output there).

It'll never be perfect unfortunately since it's kind of a "best effort" at keeping them warm via concurrent requests, which can be a bit of a race since requests may finish quickly and even though you desired say `50` idle, you'll get maybe `40`. 

The only way I can think to improve that would be adding an `time.Sleep(time.Second)` to `/_ping` (endpoint used for warming, just responds with 200). I'll give that a try tomorrow morning and push a new release, should help quite a bit!

**Comment by tj** [comment]
Next release will have the 1s timeout so that concurrency is a bit more accurate

**Comment by davidjnelson** [comment]
@tj awesome!!  that sounds like a really good tactic.  thanks!

**Comment by tj** [comment]
Most recent release has the 1s delay, it won't be perfect but should be more effective now!

**Comment by davidjnelson** [comment]
Awesome, thanks @tj !!  That sounds really great.  I'll upgrade and try it out along with changing my application name :-D
