### ISSUE TITLE
is monitoring working?

### ISSUE THREAD

**Issue by davidjnelson** [apex/up#592]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I am not seeing alarm emails.  I checked my spam folder.

## Steps to Reproduce

In my up.json I have:

`

"actions": [
    {
      "name": "email.backend",
      "type": "email",
      "emails": ["my-real@email.host"]
		}
	],
	"alerts": [
    {
      "metric": "http.count",
      "statistic": "sum",
      "threshold": 100,
      "action": "email.backend"
    },
    {
      "metric": "http.5xx",
      "statistic": "sum",
      "threshold": 1,
      "period": "1m",
      "action": "email.backend"
    },
    {
      "metric": "http.4xx",
      "statistic": "sum",
      "threshold": 50,
      "period": "5m",
      "action": "email.backend"
    },
    {
      "metric": "http.latency",
      "statistic": "avg",
      "threshold": 1000,
      "period": "5m",
      "action": "email.backend",
      "description": "Large traffic spike"
		}
	]

`

I've run `up stack plan -v` and `up stack apply -v`, as well as `up deploy staging -v` and `up deploy production -v`.

I am using cloudflare for dns with the cdn currently turned off.

I threw load at it for 10 minutes to see if I got alerts:

`wrk -d 5s -t 4 -c 1000 -d 10m --latency <myprodsiteurl>`

I did not get any alerts in my inbox or spam folder.

When I ran the tests in #591 I did get a single alert email:

`

Alert Resolved
The http requests count sum of <appname> is no longer greater than 100 in the past minute from <region>.

1 datapoint [15.0 (18/02/18 20:36:00)] was not greater than the threshold (100.0).

`

So it looks like ses is sending emails to some extent, and my email is receiving from ses to some extent.

Is my configuration right?  Thanks :-)

## Love Up?

ya!!!

**Comment by davidjnelson** [comment]
oh good thinking!  ya cloudflare and/or cloudfront could both be blocking suspected DoS for sure.

Let me try.

I hit it fairly hard for 10 minutes with `wrk -t 4 -c 1000 -d 10m --latency (result from up url production).

I'm still not seeing any alerts.  Maybe something is wonky with my config or it got in a weird state.

**Comment by tj** [comment]
Hmm from your `up stack plan` output in #591 it looks like they weren't added? There's a few `AWS::CloudWatch::Alarm` in there, maybe the `up stack apply` was rolled back? `up stack` should have those errors (if any) and say something like "status: Stack update rolled back"

**Comment by davidjnelson** [comment]
thanks @tj !  ya I'm not sure.  I think it would make sense to rename the project and do a fresh stack plan and stack apply.  that might do the trick.

**Comment by tj** [comment]
Any luck? :D

**Comment by davidjnelson** [comment]
Let me try it, thanks :-D  I'll upgrade and do every with with -v along with an app name change.

**Comment by davidjnelson** [comment]
oh, I'm actually wondering whether stack plan and stack apply work on all stages, or if the stage needs to be specified.

**Comment by tj** [comment]
Currently a single stack manages all of the stages

**Comment by davidjnelson** [comment]
oh ok dope that makes sense.  now that I'm reading the -v output in more detail I see it saying it's fetching aliases for development, staging, and production, nice.

**Comment by davidjnelson** [comment]
just to add detailed info here, when I change the app name and do up stack plan -v I see: Error: Cannot find application, make sure you deployed with `$ up`.  So that leads me to believe you need to deploy before configuring things like active warming and monitoring, (which I'm guessing is because) deploy is pushing changes to api gateway / lambda via cloudformation, and active warming and monitoring are pushing changes to cloudwatch via cloudformation, in separate operations.

**Comment by davidjnelson** [comment]
aha!  -v for the win!!!  at the end of 'up deploy production -v' I'm seeing `     Error: deploying: us-east-1: The following resource(s) failed to create: [Api, AlertActionEmailBackend, ApiFunctionAliasStaging, WarmingFunctionRole]. `

**Comment by davidjnelson** [comment]
I did `up upgrade` prior to this and it says I'm using `0.5.6 Pro` if that's helpful.

**Comment by tj** [comment]
ahhh shit maybe I missed some `DependsOn` directives, I'll try doing some fresh setup with alerts/warming too, removing those for the initial deploy may help, but I'll see if I can fix it for a fresh setup

**Comment by davidjnelson** [comment]
oh sweet, thank  you!!!  man, Up is really dope.  when alerts/warming are rocking on my setup, that will be amazing!  excited :-D  cold starts are the bane of api gateway / lambda, to the point I considered fargate back when I was using aws sam.  but fargate is a huge pain and also $180/mo to do networking in a scalable and secure way.  plus using auto scale up, auto scale down triggers isn't the beautiful, completely hands off architecture for scalability like api gateway / lambda.   so Up solving the cold starts is a total game changer.

there's a few things running right now that I have to wait to finish, but when they do I can delete my old stacks and re-create with -v.

**Comment by tj** [comment]
ok cool, pretty sure I can reproduce this with them being present for an initial `up`, somehow I missed QA-ing that, I must have been adding them to initialized apps. Should have that fixed tonight!

**Comment by davidjnelson** [comment]
oh sick, thanks!!!

**Comment by tj** [comment]
weird it seems fine for me without any `DependsOn`, I can do a `up stack delete` and `up` for a fresh install of this and it's ok:

<details>
<pre><code>
{
  "name": "up-example",
  "profile": "up-tobi",
  "type": "static",
  "lambda": {
    "memory": 512,
    "warm": true,
    "warm_count": 50,
    "warm_rate": "5m"
  },
  "stages": {
    "production": {
      "domain": "up-example.com"
    },
    "staging": {
      "domain": "stage.up-example.com"
    },
    "feature": {
      "domain": "a.up-example.com"
    },
    "beta": {
      "domain": "beta.up-example.com"
    }
  },
  "actions": [
    {
      "name": "email.backend",
      "type": "email",
      "emails": ["tj@apex.sh"]
    }
  ],
  "alerts": [
    {
      "metric": "http.count",
      "statistic": "sum",
      "threshold": 100,
      "action": "email.backend"
    },
    {
      "metric": "http.5xx",
      "statistic": "sum",
      "threshold": 1,
      "period": "1m",
      "action": "email.backend"
    },
    {
      "metric": "http.4xx",
      "statistic": "sum",
      "threshold": 50,
      "period": "5m",
      "action": "email.backend"
    },
    {
      "metric": "http.latency",
      "statistic": "avg",
      "threshold": 1000,
      "period": "5m",
      "action": "email.backend"
    },
    {
      "namespace": "AWS/ApiGateway",
      "metric": "Count",
      "statistic": "sum",
      "threshold": 500,
      "action": "email.backend",
      "description": "Note how you can use AWS namespaces and metrics directly if necessary."
    }
  ]
}
</code></pre>
</details>

Releasing a small change which should make `up stack delete` handle partial deletes a bit better, which should only happen if resources were altered manually in the console though

**Comment by davidjnelson** [comment]
oh sweet, thanks.  ya I did have a few manual changes, like some cloud watch events I setup for warming temporarily, and api gateway domains, maybe a few other little things.

I noticed the error in cloudformation in the aws console was: "not authorized to perform: SNS:CreateTopic", so looks like I need to add that policy to my IAM role.  I'm deleting my stacks and re-creating after I add that, think it will fix it.  Thanks :-)

**Comment by davidjnelson** [comment]
that seemed to do the trick.  I added the sns permissions and did a new deployment with a new app id, and now I see warming events in cloudwatch, as well as alerts in cloudwatch, and I got a few alerting emails.  I'll open a PR in the readme for that, I think those are needed.

**Comment by tj** [comment]
sweet, added the missing `sns:*` to the policy, I swear I had it but I mighttttt have merge-failed it

**Comment by davidjnelson** [comment]
awesome, thanks @tj !  I tried to do a PR but what I see here https://github.com/apex/apex/blob/master/docs/aws-credentials.md looks different than what I see on the site.
