### ISSUE TITLE
Using raw JSON for $UP_CONFIG is problematic on TravisCI

### ISSUE THREAD

**Issue by dominicbarnes** [apex/up#593]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I'm trying to configure Up Pro for use on Travis CI, but adding `$UP_CONFIG` using `travis encrypt` is proving very challenging because it [encrypts the key/value pair and then executes it in bash](https://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols). This makes the JSON-encoding very tricky and I've not yet found a way to escape the string in a way that actually works.

It would be much easier if `$UP_CONFIG` could be encoded in something much simpler like base64. If possible, it would be nice if only the `token` needed to be provided, instead of the full JSON of `~/.up/config.json`.

**Comment by kaihendry** [comment]
`travis env set UP_CONFIG "$(cat ~/.up/config.json | tr -d '\n')"`
Worked for me. :grimacing:

**Comment by kaihendry** [comment]
I think it is by default if you omit `-P` with TravisCI. :sweat_smile:

**Comment by dominicbarnes** [comment]
@kaihendry I don't think this is for the free version of TravisCI, I get prompted with this: 

> not logged in, please run travis login --org

**Comment by tj** [comment]
closed by 62505a721f1cbc0da54af15e972e7809ec41932c

**Comment by dominicbarnes** [comment]
Thanks @tj !
