### ISSUE TITLE
Documentation setup improvement - run "up" to create "up.json"

### ISSUE THREAD

**Issue by approots** [apex/up#596]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

There is no mention of running `up` to create the `up.json` file. Perhaps an additional page after "01-installation.md", named "02-setup.md". Additionally, in "02-aws-credentials.md" there is a partial `up.json` sample showing an aws profile but this is confusing since that `up.json` file is incomplete and will cause `up` to fail. Could that just be an inline example `"profile": "myapp"` instead of the full json sample, or alternatively a working sample?

```json
{
  "name": "myapp",
  "profile": "my_aws_profile_name",
  "regions": [
    "us-west-2"
  ]
}
```

**Comment by tj** [comment]
oops yeah you're right, some of that is left over from when the `name` was optional. Thanks!
