### ISSUE TITLE
custom stage proxy.command not overriding

### ISSUE THREAD

**Issue by skabbes** [apex/up#597]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

We starting to move our entire infrastructure to up, but need a QA environment.  To implement this, I'm using a custom domain mapping.

## Steps to Reproduce

Describe the steps required to reproduce the issue if applicable.

```json
/// up.json
{
  "name": "goapi",
  "runtime": "golang",
  "regions": ["us-west-2"],
  "lambda": {
    "memory": 1024,
    "role": "arn:aws:iam::XXXXXXXX:role/api_lambda_function"
  },
  "hooks": {
    "build": "./build.sh",
    "clean": "./clean.sh"
  },
  "proxy": {
    "timeout": 25
  },
  "stages": {
    "qa": {
      "proxy": {
        "command": "COMPANY_ENV=qa ./goapi -api -configDir ./config"
      },
      "domain": "go.XXXQA.com"
    },
    "production": {
      "proxy": {
        "command": "COMPANY_ENV=prod ./goapi -api -configDir ./config"
      },
      "domain": "go.XXXXX.com"
    }
  }
}

```

```
> up logs -f 'stage=qa'
/// snip
  07:11:52pm ERRO sh: ./server: No such file or directory - stage: qa version: 534
/// snip
```

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by skabbes** [comment]
@tj low priority since I can work around with a custom proxy.command that reads up_stage

Just an FYI.

**Comment by tj** [comment]
Confirmed, I think I know what the issue might be.
