### ISSUE TITLE
up stack plan fails if run before up 

### ISSUE THREAD

**Issue by savaki** [apex/up#598]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [X ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

in a new project, if I define the up.json file and immediately run `up stack plan`, I get the following error

```
fetching alias versions: fetching staging alias: ResourceNotFoundException: Cannot find alias arn ...
```

## Steps to Reproduce

1. create up.json file
2. run `up stack plan`
3. boom

**Comment by tj** [comment]
changed the error message for this from the AWS default, but `up` sets up the initial stack, `up stack plan` is just for future changes, I'll try and make that more clear in the docs too
