### ISSUE TITLE
up format does not appear to work for upgrades

### ISSUE THREAD

**Issue by dominicbarnes** [apex/up#600]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I'm deploying with up via Travis CI. I noticed that in my case, `up upgrade` shows the progress bar which generates a lot of noisy output. ([source](https://travis-ci.org/dominicbarnes/pokemongo-tools/builds/345110579))

From what I can gather, `CI=true` being present should use the "plain" formatter, but that doesn't appear to be the case. I tried running `up upgrade --format="plain"` locally to see what it _should_ look like, but I got the same human-friendly color output. (I even tried locally with `CI=true` for good measure)

It looks the formatter is not working as intended. Also, if I use `up upgrade --verbose`, the output looks pretty clumsy with the debug logs falling all over the progress bar. (maybe related?)

## Steps to Reproduce

I'm using pro, so I'm able to reproduce via:

```sh
# force the OSS version to be installed
curl -sf https://up.apex.sh/install | sh

# upgrade to the PRO version (still shows colored progress bar)
CI=true up upgrade --format="plain"
```

**Comment by tj** [comment]
Upgrade's output use a different mechanism so I'll have to special-case that one, might be best to even just `up upgrade > /dev/null` for now to toss that stdout

**Comment by dominicbarnes** [comment]
@tj sounds good, I'll use `/dev/null` for now.

**Comment by tj** [comment]
b5e19c53475d332b1d0ed68f4c787701aefa2e59
