### ISSUE TITLE
Getting Alias not found error with ResourceNotFoundException

### ISSUE THREAD

**Issue by nzee** [apex/up#606]
## Prerequisites

* [ yes ] I am running the latest version. (`up upgrade`)
* [ yes] I searched to see if the issue already exists.
* [ yes] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ no] Are you an Up Pro subscriber?

## Description
I am trying the basic hello world but getting below error while trying to deploy using 'up' command.

Error: deploying: deploying: us-west-2: creating function alias: ResourceNotFoundException: Alias not found: arn:aws:lambda:us-west-2:225205180191:function:sample-up:staging
	status code: 404, request id: a48bdcaa-1d62-11e8-b51a-5bcb22badca5

## Steps to Reproduce

up

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
I remember we talked about this in Slack, closing here for now but definitely re-open if you hit this again!
