### ISSUE TITLE
Robots.txt middleware

### ISSUE THREAD

**Issue by tj** [apex/up#610]
Typically you'd want this for staging:

```
User-agent: *
Disallow: /
```

We could have some way to configure this per-stage, though for production it's easy enough to just define create the file

Maybe non-production should _always_ respond with this? That's my vote, I can't imagine when you'd want indexing of a non-prod site.

[![](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Leave%20it%20as%20an%20app-level%20concern)](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Leave%20it%20as%20an%20app-level%20concern/vote)
[![](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Add%20middleware%20to%20define%20it%20per-stage)](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Add%20middleware%20to%20define%20it%20per-stage/vote)
[![](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Just%20add%20it%20as%20a%20default)](https://api.gh-polls.com/poll/01C7W0KBMX4645W84T6AHNHMGF/Just%20add%20it%20as%20a%20default/vote)

**Comment by Siyfion** [comment]
Personally, I like the idea of middleware handling it per-stage. I don’t think adding it by default for all staging deploys is necessarily an awful idea, so long as it’s super simple to turn back off. But I’d prefer off by default, easy toggle in `up.json`

**Comment by kaihendry** [comment]
if os.Getenv("UP_STAGE") != "production" {
		w.Header().Set("X-Robots-Tag", "none")
	}

Is [how I did as an app-level thing](https://github.com/kaihendry/goserverless.sg/blob/master/main.go#L55) (hopefully correctly!), but I voted for it to be the default.

**Comment by tj** [comment]
ahhh interesting! I didn't know x-robots-tag was a thing. Default should be pretty harmless at least
