### ISSUE TITLE
README not accessible?

### ISSUE THREAD

**Issue by jeznag** [apex/up#611]
The README looks really nice but having key text (e.g. the feature list) encoded in an image seems suboptimal from an accessibility perspective. The alt text reads "Open source edition features" which completely leaves out all the details for the features. I'd suggest you improve the alt text at the very least. Personally I'd suggest just using plain text for the README. If you want to use nice fonts, save it for a website where you can use CSS.

**Comment by tj** [comment]
noted :D not sure how many people look at GH on mobile really, but maybe I'll change that

**Comment by tj** [comment]
closing for now but I'll switch to plain-text once I have a proper landing page (should be soon)
