### ISSUE TITLE
Complexy URLs don't get proxied correctly to express API.

### ISSUE THREAD

**Issue by igorescobar** [apex/up#612]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I believe the proxy can't "forward" correctly URLs like this:
`https://myservice.com/path/https://path-tofile/img.jpg?oh=aa18cf01bc973a137fe2e479d8610318&oe=5B0C8D86`

The url gets proxied correctly to the express API but the querystring in that case isn't proxied correctly. I know the URL is not "standard" but it works nicely locally.

Here is the evidence:
```
  10:37:54pm INFO START RequestId: 02f7bcc3-218f-11e8-9bfe-835238ec582a Version: 22
  10:37:54pm INFO request - id: 02f6f8ef-218f-11e8-a77a-557101541a8c ip: 141.101.98.46 method: GET path: /cover/200x200/https://scontent.flis8-2.fna.fbcdn.net/v/t1.0-9/27540853_1717020448320186_454891504930665949_n.jpg stage: staging version: 22
  10:37:55pm WARN response - duration: 403ms id: 02f6f8ef-218f-11e8-a77a-557101541a8c ip: 141.101.98.46 method: GET path: /cover/200x200/https://scontent.flis8-2.fna.fbcdn.net/v/t1.0-9/27540853_1717020448320186_454891504930665949_n.jpg size: 80 B stage: staging status: 400 version: 22
  10:37:55pm INFO END RequestId: 02f7bcc3-218f-11e8-9bfe-835238ec582a
  10:37:55pm INFO REPORT RequestId: 02f7bcc3-218f-11e8-9bfe-835238ec582a	Duration: 455.34 ms	Billed Duration: 500 ms 	Memory Size: 320 MB	Max Memory Used: 54 MB
```
The querystring of the image is missing. I thought it would be something wrongly implemented on my side but locally it works fine but when I push de code using `up deploy` the querystring wasn't proxied to the express api.

## Steps to Reproduce

Regular express API, simulate a URL like the one above and you will see the problem.

**Comment by tj** [comment]
Hmm maybe try encoding the `?` as %3F — by default the `?...` would be part of `myservice.com` and not passed as the path, although you could "stitch" the two back together on the server-side

**Comment by igorescobar** [comment]
The problem is that I don't have control over it. It's up to the client solve the problem and would be great the they did have to worry about this.

**Comment by igorescobar** [comment]
@tj  I appreciate your time but turns out that it wasn't a problem with up nor AWS stack. It was a problem with how I was configuring my CACHE preferences on Cloudflare. I turned back the "standard" option on and it started to function properly.
