### ISSUE TITLE
Unable to deploy on production with owned domain

### ISSUE THREAD

**Issue by markelog** [apex/up#618]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description
With config
```json
{
  "name": "eclectica",
  "type": "static",
  "static": {
    "dir": "public"
  },
  "error_pages": {
    "dir": "public"
  },
  "regions": ["eu-west-1"]
}

```

After adding

```json
...
"stages": {
    "production": {
      "domain": "eclectica.sh"
    }
  }
...
```
to the config and doing

```bash
$ up stack plan
Add api domain
    id: ApiDomainProduction

  Add api mapping
    id: ApiDomainProductionPathMapping

  Add dns record
    id: DnsZoneEclecticaShRecordEclecticaSh
```
Then 
```bash
$ up stack apply
```

Then 
```bash
$ up stack

...

Events

     ApiDomainProduction: Unable to associate certificate arn:aws:acm:us-east-1:421859188480:certificate/18535ea1-9c07-4d31-8d55-47b18a3235e7 with CloudFront. This error may prevent the domain name eclectica.sh from being used in API Gateway for up to 40 minutes. Please ensure the certificate domain name matches the requested domain name, and that this user has permission to call cloudfront:UpdateDistribution on '*' resources.
```

Then if I do
```bash
$ up stack delete

     Really destroy stack "eclectica"? Yes
```
And without modifying the config
```bash
$ up

     build: 221 files, 20 MB (1.5s)
     deploy: version 6 (28.983s)
     stack: complete (9.107s)


     Error: deploying: eu-west-1: The following resource(s) failed to create: [ApiLambdaPermissionProduction, ApiDomainProduction, ApiLambdaPermissionStaging].
```

**Comment by tj** [comment]
I keep forgetting what this vague `Unable to associate certificate` error is, I think it's because of the cert exists but was never verified. Might have to visit https://us-east-1.console.aws.amazon.com/acm and manually re-send the verification email (or delete it and `up` again).

I think that's the cascading issue there, but if that fails please post the errors at the bottom of `up stack` and I can try to figure out what's going on there!

**Comment by markelog** [comment]
Yeah, you are right about the cascading thing. However, the reason why, is a bit more tricky.
From https://up.docs.apex.sh/ –

> By default domains purchased with Up have privacy protection enabled, hiding your contact information from WHOIS.

On the same page however –

> AWS requires email verification to prove you own the domain. AWS sends an email to the 3 contact addresses listed in WHOIS when you registered the domain, and to the following 5 common system 

> addresses for your domain:
administrator@your_domain_name
hostmaster@your_domain_name
postmaster@your_domain_name
webmaster@your_domain_name
admin@your_domain_name

(I did purchase the domain through the `up` btw)

Which means, I cannot verify the domain without changing the whois information or specifying dns `mx` entries and setting up my email server?

Is that the intention, or am I missing something?

**Comment by markelog** [comment]
Sounds good, should I close this issue? Since you already have #430?

btw, do you have any like simple enough issues for the contribution?

**Comment by tj** [comment]
Yep let's close this one for now, I'll try and get that in this week :D.

Issues in general? Or for that specific feature?

**Comment by markelog** [comment]
> Issues in general? Or for that specific feature?

Maybe something like contributing friendly situation? Small time bugs or something like that?

**Comment by tj** [comment]
Marked a few as "good first issue" which shouldn't be too complicated. The only major-ish UX thing I can think of right now is better error reporting for `up stack apply`'s errors, that part needs a bit of love still but it's tricky with AWS' limitations
