### ISSUE TITLE
feature suggestion: api keys

### ISSUE THREAD

**Issue by thewillhuang** [apex/up#625]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

not an issue, but a suggestion, what about api keys that you can set via env or up.json

**Comment by thewillhuang** [comment]
woops just saw this https://github.com/apex/up/issues/625

**Comment by chanlito** [comment]
Where?🤔

**Comment by kaihendry** [comment]
Perhaps referring to https://github.com/apex/up/issues/105#issuecomment-380694848
