### ISSUE TITLE
Swapping the JS shim for a native Go binary

### ISSUE THREAD

**Issue by jpillora** [apex/up#626]
Apologies if this has been asked before. From what I can see, [Up still uses the Node 6.x runtime](https://github.com/apex/up/blob/a505a51296df871d5fdd104f495fcd702ef78831/platform/lambda/lambda.go#L831), which then [runs a Go binary](https://github.com/apex/up/blob/master/internal/shim/index.js#L43). Have you looked into the performance impact of removing the JS shim and directly running a native Lambda Go binary instead?

**Comment by hhsnopek** [comment]
Hey @jpillora checkout #450 and #543

**Comment by tj** [comment]
Ah yeah it basically had no real-world impact, and only made the Node side of things worse since the Go runtime has no Node 6.x, only 0.10.x I believe, otherwise yeah might as well be in Go but I think we're stuck with Node for now!

**Comment by jpillora** [comment]
> shave ~3mb off your deploy size

I like the sound of that! Though probably not worth the effort of maintaining 2 shims :(
