### ISSUE TITLE
Document domain certificates a little more thoroughly

### ISSUE THREAD

**Issue by courajs** [apex/up#632]
## Prerequisites
* [x] I searched to see if the issue already exists.
* [x] Are you an Up Pro subscriber?

## Description
In the [custom domains documentation](https://up.docs.apex.sh/#configuration.stages_custom_domains) it mentions creating a free SSL certificate. I was concerned about when/how/if it's automatically renewed, but had to dig through the github repo to find the answer. I'm not even 100% sure as I haven't transferred my domains to AWS yet.
I believe because it uses the AWS certificate manager, it can just be configured to automatically renew.

I understand it's a balance in the docs between too much and too little description. Maybe there could be separate docs pages for these little, but significant, details.

**Comment by tj** [comment]
agreed! Definitely let me know when anything is unclear, it's hard to always catch these since I'm familiar with AWS, appreciate it!
