### ISSUE TITLE
Using ACM cert from different region causes "SSL certificate problem: certificate has expired"

### ISSUE THREAD

**Issue by jsalonen** [apex/up#633]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [X] I inspected the verbose debug output with the `-v, --verbose` flag.
* [X] Are you an Up Pro subscriber?

## Description

"SSL certificate problem: certificate has expired" error in domains created with up.

## Steps to Reproduce

Use static type with domains in up.json:

```
{
  "name": "myfrontend",
  "type": "static",
  "static": {
  	"dir": "build"
  },
  "profile": "myprofile",
  "regions": [
    "eu-central-1"
  ],
  "hooks": {
    "build": "yarn build",
    "clean": "rm -Rf build"
  },
  "stages": {
    "staging": {
      "domain": "app-staging.example.com"
    },
    "production": {
      "domain": "app.example.com"
    }
  }
}
```

I'm using AWS Certificate Manager elsewhere and there is already Amazon Issued certificated in ACM assigned to *.example.com. There is a valid ARN for this, but its located in a different AWS region:

- The app is deployed to "eu-central-1"
- Valid ACM cert for this app is located in different region ("eu-west-1")
- Up attempts to use ACM cert from "us-east-1", which has a non-verified cert. To the best of my understanding this was a cert generated by up, which was never verified and because of this it stopped working after a while.

Workarounds / questions:

- Why does ACM resolve to "us-east-1"?
- Workaround 1: up should notify if trying to deploy with a cert that is not verifed
- Workaround 2: would it be possible to provide ARN of a valid ACM cert in up.json to avoid this issue? The cert is shared among several apps so it would make sense in my use case.

**Comment by tj** [comment]
Currently ACM has to be used in us-east-1 with API Gateway's "edge optimized" option. I don't know the technical reason, but it's the same with Lambda functions used for Lambda@edge, they need to live in us-east-1 as well. I'll make a note of that in the docs since it's a strange quirk.

For now if you either remove it or manually re-send verification from the AWS Console Up should grab it correctly

**Comment by jsalonen** [comment]
Thanks for the clarification. Makes perfect sense now, but it was difficult to understand why this happened.

Closing.
