### ISSUE TITLE
Local dependency empty in zip

### ISSUE THREAD

**Issue by atistler** [apex/up#634]
## Prerequisites

* [x ] I am running the latest version. (`up upgrade`)
* [ x] I searched to see if the issue already exists.
* [ x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I have a local dependency:
```
"utils": "file:../../lib/utils"
```

Running an `up build` will give me a zip file however the directory `node_modules/utils` is empty.  In my local node_modules, utils is a symlink.

**Comment by tj** [comment]
Closing as a dup of #628 — currently the symlinks must be still within the directory you deploy, but I'd like to tweak that to inline them!
