### ISSUE TITLE
up start --stage <stage>

### ISSUE THREAD

**Issue by lenaten** [apex/up#639]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Please add option to start app with specific stage (currently only development).
My main use case is the ability to reproduce bugs in other stages by run the same app with different environment variables.
```
$ up start --stage production
```

**Comment by lenaten** [comment]
Thanks TJ

**Comment by tj** [comment]
no problem :D
