### ISSUE TITLE
invalid Cors response

### ISSUE THREAD

**Issue by ThatTomPerson** [apex/up#649]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber? 😢  no

## Description

can't seem to get cors working when `Access-Control-Request-Method: POST` is in the request 

## Steps to Reproduce
The same thing happens with `up start` and when it is deployed

given the program
```
package main

func main() {
  mux := http.NewServeMux()
  mux.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
    res.Write([]byte("OK"))
  })
  addr := ":" + os.Getenv("PORT")
  http.ListenAndServe(addr, corsMiddleware(mux))
}


func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodOptions {
			w.Header().Set("Access-Control-Allow-Origin", "*")
			w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
			w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, Authorization, X-GRPC-Web")
		} else {
			next.ServeHTTP(w, r)
		}
	})
}
```
it all works fine until the client send a `Access-Control-Request-Method: POST` header and then my program doesn't get hit and the response headers are
```
Vary: Accept-Encoding
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Date: Fri, 20 Apr 2018 03:45:49 GMT
Content-Length: 0
```

up.json
```
{
  "name": "booking",
  "profile": "default",
  "regions": ["ap-southeast-2"],
  "cors": { "enable": true }
}
```

I'm not sure what todo

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by ThatTomPerson** [comment]
Ah thanks

It is complaining about my `Content-Type` header isn't allowed

**Comment by tj** [comment]
np!
