### ISSUE TITLE
Alert email templates

### ISSUE THREAD

**Issue by tj** [apex/up#65]
AWS' default SNS subscription emails are really ugly and hard to digest. Ideally we show a nice inline SVG rendering of the alarm and make the problem more immediately obvious.

- Use S3 Lambda from apex bucket for Lambda func?
- [x] email alert action
- [x] add severity? maybe
- [ ] ability to mute alerts without running `up stack`? maybe
- [ ] add optional email template/body thing so people can inform the team
- [ ] support multiple emails
- [ ] triggered
- [ ] resolved
- [ ] inline image of the alarm's state

**Comment by kaihendry** [comment]
Please make these plain text by default..

**Comment by tj** [comment]
@kaihendry not opposed to it but how come?

**Comment by lukeed** [comment]
Probably because HTML emails are the least consistent / most broken aspect of web dev 😆 

I'd prefer HTML emails, but it 100% isn't going to appear correctly for all users.

**Comment by tj** [comment]
truth hahaha, plain text is better than broken HTML that's for sure, I'll keep them light enough that they should at least degrade in a reasonably non-ugly way if broken :D

**Comment by kaihendry** [comment]
Take prometheus's default for example: https://github.com/prometheus/alertmanager/issues/577#issue-194502072

IIRC it's still [HTML only](https://prometheus.io/docs/alerting/configuration/#email_config) and it's still screwed up.

**Comment by lukeed** [comment]
> I'll keep them light enough that they should at least degrade in a reasonably non-ugly way if broken

Famous last words. I've said that at least 3 times... Good luck!

**Comment by tj** [comment]
bahahah ok ok, you guys win :D plain text by default

**Comment by lukeed** [comment]
LOL, images are okay. No svg tho.

Plain text for alpha/first releases is great imo. Would circle around at a later date with the Apex styling brush.

**Comment by tj** [comment]
agreed, might as well leave that for later
