### ISSUE TITLE
`up deploys` says "today" for a deploy I did yesterday

### ISSUE THREAD

**Issue by courajs** [apex/up#658]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description
I deployed yesterday afternoon, then ran `up deploys` this morning. It says the last deploy was 4:03PM, this coming afternoon. Either you've got some advanced predictive AI in there, or there's a bug :)
Probably time zone issues, or maybe it just says today if it's <24hrs ago?
I think all my AWS resources are in the same time zone as me, EDT.

```
server.tv$ up deploys

     Stage      Version  Author       Size    Date

     * staging  80b46d9  Aaron Sikes  11 MB   Today at 04:03:21pm
       staging  5474468  Aaron Sikes  11 MB   May 9th 08:46:23pm
       staging  5474468  Aaron Sikes  11 MB   May 9th 08:43:43pm
       staging  c2d81e9  Aaron Sikes  10 MB   May 9th 08:25:52pm
       staging  a7cf4ed  Aaron Sikes  6.9 MB  Apr 4th 07:31:47pm
```

## Steps to Reproduce
Deploy and wait 12 hours?
¯\\_(ツ)_/¯

**Comment by tj** [comment]
deploys from the future! :D hahah yea I think I just do a 24 hour check right now, I'll get that fixed haha

**Comment by tj** [comment]
Next release will only have relative for the past since it's probably more useful to see exact times for correlation anyway
