### ISSUE TITLE
CORS headers are not added for 4xx and 5xx responses

### ISSUE THREAD

**Issue by huygn** [apex/up#661]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I'm doing jwt auth on my `up` app to return 401, but i've got this CORS error:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 401.
```

Checking Network tab the 401 response always return with only `content-type: text/html; charset=utf-8` header and nothing else.

up.json:
```
"cors": {
    "allowed_origins": ["*"],
    "allowed_methods": ["HEAD", "GET", "POST", "PUT", "PATCH", "DELETE"],
    "allowed_headers": ["*"],
    "max_age": 1,
    "debug": true
  },
```

debug logs:
```
[cors] 2018/05/14 16:44:14 Handler: Preflight request
[cors] 2018/05/14 16:44:14   Preflight response headers: map[Vary:[Accept-Encoding Origin Access-Control-Request-Method Access-Control-Request-Headers] Access-Control-Allow-Origin:[*] Access-Control-Allow-Methods:[GET] Access-Control-Allow-Headers:[Authorization]]
[cors] 2018/05/14 16:44:14 Handler: Actual request
[cors] 2018/05/14 16:44:14   Actual response added headers: map[Vary:[Accept-Encoding Origin] Access-Control-Allow-Origin:[*]]
```

Tried running my up app locally and it returns 401 correctly (with CORS headers).

**Comment by huygn** [comment]
Just figured out, it should be

```
"error_pages": {
    "disable": true
  }
```

Thanks again 🎉

**Comment by tj** [comment]
Just in case anyone hits this, setting `Accept` should also do the trick when enabled:

```js
const res = await fetch('https://myapp.com', {
  headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
  method: 'POST',
  body
})
```
