### ISSUE TITLE
Task timed out after.... should be an ERROR?

### ISSUE THREAD

**Issue by kaihendry** [apex/up#663]
Using `0.6.4-pro`

```
[hendry@t480s set]$ up logs 'id = "fb63a8b6-599d-11e8-a437-911ac44bc0b4"' -e
[hendry@t480s set]$ up logs | grep fb63a8b6-599d-11e8-a437-911ac44bc0b4
{"fields":null,"level":"info","timestamp":"2018-05-17T14:46:28+08:00","message":"REPORT RequestId: fb63a8b6-599d-11e8-a437-911ac44bc0b4\tDuration: 18018.26 ms\tBilled Duration: 18000 ms \tMemory Size: 512 MB\tMax Memory Used: 82 MB\t"}
{"fields":null,"level":"info","timestamp":"2018-05-17T14:46:28+08:00","message":"2018-05-17T06:46:28.161Z fb63a8b6-599d-11e8-a437-911ac44bc0b4 Task timed out after 18.02 seconds"}
```

Couldn't Up do a better job of showing the task timed out given a RequestId please? I was expecting to clearly see the error.

Also little puzzled why I didn't see the corresponding ` method=GET path=/` line. I do see a `request: id=fb630c38-599d-11e8-b5cf-fd3f412939bc ip=101.127.194.198 method=GET path=/` line, but fb630c38-599d-11e8-b5cf-fd3f412939bc != fb63a8b6-599d-11e8-a437-911ac44bc0b4

<img src=https://s.natalian.org/2018-05-17/1526542572_2548x1398.png>

Thank you

**Comment by tj** [comment]
Ahh yeah I've been meaning to improve that, currently the timeout is Lambda's timeout, so I don't have control over those logs, but we can add a timeout to the request itself in the proxy before Lambda times out

**Comment by tj** [comment]
closing for #338 but I'll prioritize that, we just have to "pad" the timeout a bit so Lambda doesn't do it before we do hahah, it's a little awkward
