### ISSUE TITLE
Move cloud database list to a "awesome list"

### ISSUE THREAD

**Issue by brillout** [apex/up#665]
I took the liberty of copying the list of cloud databases from https://github.com/apex/up/wiki#databases to https://github.com/reframejs/reframe/blob/master/docs/cloud-databases.md. I hope it's ok.

The better solution would be to have an awesome list though. I would then just link to the awesome list. I wouldn't have time to maintain it though. I already maintain awesome react components and awesome angular components.

Maybe someone is up for creating such "awesome cloud databases" list.

This is minor thing though and feel free to just close this ticket.

**Comment by tj** [comment]
not too worried about it! I don't think the wiki gets many views anyway :D

**Comment by tj** [comment]
closing for now, but if anyone finds cool lists we can link to those as well
