### ISSUE TITLE
Alert DSL

### ISSUE THREAD

**Issue by tj** [apex/up#67]
Love some opinions. I'm going to put a lot of effort into validating the config as best I can, so don't be afraid of a DSL being flimsy, that said currently you do:

```json
  {
    "enabled": true,
    "metric": "api.errors",
    "statistic": "sum",
    "threshold": 5,
    "action": "email.me"
  }
```

It might be nice to optionally do:

```
"email.me if api.errors sum > 5 in 1m",
"email.me if api.latency avg >= 1.5s in 5m"
```

where "email.me" is an action defined elsewhere

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMWFGDA9ZK02D1P553RNNZ78/I%20prefer%20JSON)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMWFGDA9ZK02D1P553RNNZ78/I%20prefer%20JSON/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMWFGDA9ZK02D1P553RNNZ78/I%20prefer%20DSL)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMWFGDA9ZK02D1P553RNNZ78/I%20prefer%20DSL/vote)

**Comment by kaihendry** [comment]
JSON of course. Perhaps also ship a schema so that VS code can check the edits are OK.

Just to compare your design against: https://prometheus.io/docs/alerting/rules/
