### ISSUE TITLE
Support more complex Git tags

### ISSUE THREAD

**Issue by tj** [apex/up#670]
Learna produces tags such as `@foo/bar-baz@0.5.0` which are not properly encoded in a way that AWS supports for Lambda aliases which have a restricted character set.

Or we should ignore in this case since the tag isn't directly related to any app version, just a package.

[EncodeAlias](https://github.com/apex/up/blob/master/internal/util/util.go#L457)

**Comment by loicplaire** [comment]
I am not sure about ignoring the tag. For example, in our usage of Lerna, the client UI is a package published to NPM and the graphql server is an actual app (the one deployed with up). Both are versioned with this tag format.  For example `@organisation/graphql-server@0.5.0` refers to the graphql server version. I guess what I am trying to say is that the package is the app.

If this tag is ignored, then I assume it would use the commit hash, wouldn't it? That would work for us but I guess it would be less intuitive than having the actual git tag.

**Comment by tj** [comment]
Ahhh ok cool if it is the app then splitting on the @ sounds like it should be ok then
