### ISSUE TITLE
VPC subnets setting should accept comma separated string

### ISSUE THREAD

**Issue by vietbui** [apex/up#679]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`) 0.6.8
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

It is great that up is now supporting VPC. However, datatype of subnets must be an array. Is it possible to make it accept comma separated string as well?

**Comment by tj** [comment]
I'd definitely prefer to keep one type, but let me know what your use-case is and I can think about it!

**Comment by vietbui** [comment]
Hi TJ,

We currently save comma separated list of subnets to parameter store and use that to drive VPC configuration for an API deployed using up. Currently we have to do this:

```
export NAT_SUBNET_1=`echo ${NAT_SUBNETS} | cut -d',' -f1`
export NAT_SUBNET_2=`echo ${NAT_SUBNETS} | cut -d',' -f2`
```

And template the `up.json` file with:

```
    "vpc": {
      "subnets": [
        "${NAT_SUBNET_1}",
        "${NAT_SUBNET_2}"
      ],
      ...
```

This works for now but not dynamic enough when there are more than 2 subnets available (e.g. US region).

It's just a nice to have feature that subnets accepts comma separated list directly.

Anyway thank you for your great work with up.

Cheers.

**Comment by tj** [comment]
Closing this one I think the JSON array is ok
