### ISSUE TITLE
Unable to up start java maven project

### ISSUE THREAD

**Issue by aronneagu** [apex/up#680]
## Prerequisites

* [x]  I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Running `up start` on a maven project will try to look into the top level directory for the jar instead, of the target directory, where the jar is normally created.

## Steps to Reproduce
```
git clone https://github.com/apex/up-examples
cd up-examples/oss/java-maven-springboot
up start
  Jun 15th 08:19:06am INFO starting app: PORT=49406 command=java -jar server.jar
  Jun 15th 08:19:06am INFO started app: pid=40719
  Jun 15th 08:19:06am INFO waiting for app to listen on PORT
  Jun 15th 08:19:06am ERRO Error: Unable to access jarfile server.jar
```

It's looking for server.jar in the top directory, but if I create the package with `mvn clean package`, that will create target/server.jar. I am aware I can run the command with `up start -c 'java -jar target/server.jar'`, or I can modify the up.json to add the command there. I wonder if this was intentional or a bug

## Love Up?

I am absolutely loving up! It blows AWS SAM and Serveless framework out of the water. I am very impressed with it and will be sigining up for Pro version after I end creating this ticket. I am loving the subscription model as well, pay one fixed price per month, independent of team members or projects used. Doesn't make me feel the author is greedy and doing this just for the money. Plus did I mention how awesome the tool is?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

**Comment by tj** [comment]
I'm not familiar with the Java ecosystem at all so that part was contributed, looks like we do a copy: 
https://github.com/apex/up/blob/master/config/runtimes.go#L115

So `up run build` first should do it as well. Still debating on whether or not auto-building on `up start` makes sense for all cases

**Comment by aronneagu** [comment]
That is useful, then I just need to ensure that I run `up run build` before `up start`. Thanks for the info
