### ISSUE TITLE
Allow creating env variables shared across multiple projects

### ISSUE THREAD

**Issue by aronneagu** [apex/up#683]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I would like to request a new feature.
I've noticed that env variables are being pushed to EC2 SSM Parameter store (which by the way is an amazing idea), and follow the naming convention `/up/<project>/<stage>/<ENV_VARIABLE>`. I wonder if it would be easy to add `/up/<stage>/<ENV_VARIABLE>` that would be shared across all projects.

I would image the order of precedence would be the following (first one has the lowest priority):
```
/up/all/<ENV_VARIABLE>
   ^
/up/<stage>/<ENV_VARIABLE>
   ^
/up/<project>/all/<ENV_VARIABLE>
   ^
/up/<project>/<stage>/<ENV_VARIABLE>
```

## Steps to Reproduce

None. Feature request

## Love Up?

Loving it.

Would appreciate if this would be considered for a future release. Thank you

**Comment by aronneagu** [comment]
I've given this some more thought, and there is a potential downside. If multiple functions would be sharing some env variables, for example api keys to connect to a 3rd party app, then it would make sense to put those several lambda functions into one. It would "force" good programming practice, as env variables would "dictate" in a sense the scope of an application/function(s). I don't have that much experience with lambda functions / server-less so I am open to be corrected.

I've just started using apex-up a week ago and we already built one functionality at my workplace, so I have yet to encounter a situation where env variables need to be shared across multiple functions, but will keep an eye on that.

This would definitely be an opt-in.

**Comment by tj** [comment]
On #535 I mentioned a latency issue as well that I didn't think about until going to implement it haha. Probably best to avoid it for now at least. I think personally I'd still prefer to update each app, even if it's a bit of work, at least then you can slowly migrate to a new database etc, bit more control.
