### ISSUE TITLE
401 Unauthorized error running installation script

### ISSUE THREAD

**Issue by sunkibaek** [apex/up#684]
## Prerequisites

n/a

## Description

```bash
$ curl -sf https://up.apex.sh/install | sh
apex/up: checking GitHub for latest version
curl: (22) The requested URL returned error: 401 Unauthorized
```

## Steps to Reproduce

When I try to install the command line tool with above command it returns 401 error.

**Comment by tj** [comment]
It's GitHub API rate limiting :'( — you might need to define the `GITHUB_TOKEN` env variable, GH allows 5000 requests per hour that way

**Comment by sunkibaek** [comment]
Oh, I see. That might be worth a mention in readme.

Thanks for the help!
