### ISSUE TITLE
[Feature Request]: Ability to define up config inside package.json

### ISSUE THREAD

**Issue by chanlito** [apex/up#686]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

This is not the end of the world or anything but I have mostly of my config inside package.json, it'd be nice to have up config there too instead of a dedicated `up.json`. 😄

**Comment by tj** [comment]
fewer files is definitely nice buttttt I'm not sure it's worth having language-specific changes like that haha :D

**Comment by chanlito** [comment]
😂 Yeah I'm just gonna close this, tsconfig and tslint json can't be defined in package.json either.
