### ISSUE TITLE
Non-retry crash recovery

### ISSUE THREAD

**Issue by courajs** [apex/up#688]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] Are you an Up Pro subscriber?

## Description

When using retries, the up proxy will detect a crash and restart the server. However, when retries are disabled, a crashed server is never restarted. This results in a lambda instance serving 502 responses until traffic lowers enough for the instance to be shut down/collected by AWS.

I think ideally these two would be usable independently.

https://github.com/apex/up/blob/5f16b7f99d6c5bd23289e8bf1927a5cce32e3475/http/relay/relay.go#L178

## Steps to Reproduce
https://github.com/courajs/up-crash-example

1. Make an app that crashes
1. Disable retries with `"proxy": {"retry": false}` in `up.json`
1. Make http requests to the proxy, you will get consistent 502

**Comment by tj** [comment]
Thanks for the report, I'll take a look I agree they're separate cases.

**Comment by tj** [comment]
Need to polish it up and QA but should have this fix out tomorrow, I was meaning to remove retries anyway it ended up just causing more confusion overall I think.

**Comment by tj** [comment]
921e818
