### ISSUE TITLE
VPC configuration not working inside stage

### ISSUE THREAD

**Issue by spidie** [apex/up#689]
Hi there, was so happy to see recently that we now have VPC support for Apex Up in the configuration rather than having to do the manual workaround. Thankyou to whoever did that!

Currently it works for me if I do something like this.
```
{
  "name": "api",
  "lambda": {
    "memory": 512,
    "vpc": {
      "subnets": [
        "subnet-aaaaaaa",
        "subnet-bbbbbbb",
        "subnet-ccccccc",
      ],
      "security_groups": [
        "sg-xxxxxxx"
      ]
    }
  }
}
```
but if I want to put it inside a particular stage so that I can have different VPCs for staging and production for instance - it reverts back to the no VPC behaviour.  
```
{
  "name": "api",
  "lambda": {
    "memory": 512,
  },
  "stages": {
    "staging": {
      "lambda": {
        "vpc": {
          "subnets": [
            "subnet-aaaaaaa",
            "subnet-bbbbbbb",
            "subnet-ccccccc",
          ],
          "security_groups": [
            "sg-xxxxxxx"
          ]
        }
      }
    }
  }
}
```
Had a look at up config and it is definitely putting it into the config - there is nothing in the verbose output for either case that refers to setting up VPC - so I suspect the VPC part of the deployment is just not logged.

Any help much appreciated. Happy to dig a bit more if anyone can give me some pointers.

**Comment by tj** [comment]
ahhh you're right! There's no stage-level overrides at the moment, but I don't see a reason why not, I'll try to get that in soon

**Comment by spidie** [comment]
Awesome - thanks @tj - I haven't deployed to prod yet - so not stopping me doing work at the moment. Is there something that can go in the verbose logging for VPC setup too - that would be useful for debugging. I couldn't see anything in there.

**Comment by tj** [comment]
@spidie which logging did you have in mind there? The flow logs?

**Comment by spidie** [comment]
Just in the verbose logging where I can see it creating the lambdas. I was being a good citizen following the bug submission guidelines (this was my first) and couldn't see any references to VPC in my log output.

I was expecting to see something in your "DEBU track "Deploy"" lines at the end relating to subnets and security groups. No big deal just thought it might be useful for future debugging.

**Comment by tj** [comment]
Good point haha yeah I should probably output all of the function config, I'll open an issue
