### ISSUE TITLE
Error: deleting function iam role: deleting policy: NoSuchEntity

### ISSUE THREAD

**Issue by atistler** [apex/up#693]
## Prerequisites

* [ ] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Version: 0.6.6

Error: deleting function iam role: deleting policy: NoSuchEntity: The user with name <FUNCTION_NAME> cannot be found.
	status code: 404, request id: d138e7***************

## Steps to Reproduce

Deploy function as usual, then: `up stack delete -f --format=plain`

**Comment by tj** [comment]
hmm which `up version`?

I have a NoSuchEntity check to ignore those errors, I haven't had those myself when deleting

```go
if err := p.deleteRole(region); err != nil && !util.IsNotFound(err) {
		return errors.Wrap(err, "deleting function iam role")
	}
```

**Comment by atistler** [comment]
Yes, my apologizes, this is fixed in current version.
