### ISSUE TITLE
Downtime with v0.7.2

### ISSUE THREAD

**Issue by igorescobar** [apex/up#694]
## Prerequisites

* [ ] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Just for context, my API was pretty stable and we haven't had any sort of downtime for months. I recently upgrade from 0.6.8 to 0.7.2 and my API started to be unresponsive for no clear reason and the only we to fix it for re-deploying the API using the old version again.

I suspect it was some regression here:
`921e818 remove retries, refactor crash recovery, and add in-flight request timeouts.` released since v0.7.0.

If this is expected, let me know how I can upgrade without experiencing bad gateway errors on my API.

## Steps to Reproduce

I'm not sure how to reproduce it because I didn't have much time to dig (production problem). I thought it would be helpful to let you know.

**Comment by tj** [comment]
hmm interesting, yeah that was a reasonably big change, it seems fine from the QA apps I use but I'll see if I can reproduce. You're just getting timeouts now?

**Comment by igorescobar** [comment]
@tj the major difference for me was that with the latest version the API became unresponsive for no clear reason. With the old version I was getting some timeouts once awhile but the API never became unresponsive.

**Comment by tj** [comment]
What do you mean by unresponsive? errors or just slower in general?

**Comment by tj** [comment]
I think I found the issue, I'll push a release today if I can get it fixed

**Comment by tj** [comment]
v0.7.3 should be ok now, thanks for the report!

**Comment by igorescobar** [comment]
Thanks @tj!
