### ISSUE TITLE
Too many database connections!

### ISSUE THREAD

**Issue by igorescobar** [apex/up#698]
Seems like to be able to share database connections between lambda invocations I need to setup a few things on the `context` lambda variable, for example: `context.callbackWaitsForEmptyEventLoop`.

As you can see explained on this article:
https://www.mongodb.com/blog/post/optimizing-aws-lambda-performance-with-mongodb-atlas-and-nodejs

Would be great to know how to achieve something like this and share state between invocations. 

The fact that you can't achieve something like this (AFAIK) makes you having too many open connections to your database and sometimes hitting `connection limits` and therefore resulting in falling requests.

Is there any solution without having to completely change our persistence layer to something like `DynamoDB` ?

**Comment by igorescobar** [comment]
Also:
https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html

```
Any declarations in your Lambda function code (outside the handler code) remains initialized, providing additional optimization when the function is invoked again. For example, if your Lambda function establishes a database connection, instead of reestablishing the connection, the original connection is used in subsequent invocations. We suggest adding logic in your code to check if a connection exists before creating one.
```

Food for though.

**Comment by tj** [comment]
I would imagine if you keep the connection open (outside of a route) it should be fine, I can't comment on the Mongo driver specifically.

Up is executing the apps via Go there's no way to expose `callbackWaitsForEmptyEventLoop` to the app since it's actually in a different process, Lambda couldn't track those events.

**Comment by tj** [comment]
Closing this one for now since I don't think there's anything actionable that Up can do at the moment

**Comment by berkaey** [comment]
Hey @tj, is your answer still relevant? Probably a lot of up users are need this, maybe an example helps? For example; our approach is like;

We are using `micro`, 
We have a abstract DB class (in this case we are connecting to MongoDB).
`db.js` looks like

```
var MONGO_CONNECTION;

class DB {
  constructor(config) {
    this.config = config;
    this.log = new Logger({ name: "DB" });
    this.connection = MONGO_CONNECTION;
  }

  async connect() {
    if (!this.connection) {
      try {
        this.connection = await MongoClient.connect(
          this.config.url,
          this.config.options
        );
        MONGO_CONNECTION = this.connection;
      } catch (err) {
        if (err instanceof MongoError) {
          throw this.error.db("exception:mongo-connection");
        }
      }
    }
    this.log.ok(`MongoDB connection is established.`);
    return this.connection;
  }

}
```
Is something like is enough to share connection, or ?
