### ISSUE TITLE
Cannot deploy to "development" stage

### ISSUE THREAD

**Issue by aronneagu** [apex/up#700]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

As per documentation there should be a development stage as well, (see https://up.docs.apex.sh/#configuration.stages), but I cannot seem to be able to deploy to it. I am expecting to see another alias called development in the lambda function.

## Steps to Reproduce

Ran `up deploy development` and got the following errr 
```
Error: "development" is invalid, must be one of:
• production
• staging
```

Running apex 0.7.3-pro

PS: I have tried adding "development" stage to up.json as
```
{
  "name": "test-function",
  "profile": "default",
  "regions": [
    "eu-west-1"
  ],
  "stages":{
    "development":{
    }
  }
}
```
and running up stack plan but that returned the error
```
Error: The submitted information didn't contain changes. Submit different information to create a change set.```

**Comment by tj** [comment]
"development" is just the name for running locally as `up start` now, I'd recommend using "staging", or you can create your own such as "beta" [here](https://up.docs.apex.sh/#configuration.stages)

**Comment by aronneagu** [comment]
That raises 2 more questions:
1. Does this mean that "development" is a reserved keyword? (because I cannot create a stage called like that)
2. When running `up start` is the keyword `development` used anywhere?

**Comment by tj** [comment]
Yep that's correct, "development" is reserved for local use, and it will populate UP_STAGE and NODE_ENV by default to "development", UP_STAGE can be used in build hooks etc as well

**Comment by aronneagu** [comment]
Thanks for the clarification, that makes more sense. Closing the ticket
