### ISSUE TITLE
Up pro times out my app when trying to use secret env

### ISSUE THREAD

**Issue by vespertilian** [apex/up#702]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I can deploy my app without secrets using up OSS. When upgrade to the pro version add a secret and deploy the app starts up and then times out after initialising secrets. When I redeploy by logging out of up pro it works again. 

I use all the things (VPC, Stages and Environment) not sure if that is causing the issue. 

Below is my up file:

```json
{
  "name": "api",
  "profile": "api",
  "regions": ["ap-southeast-2"],
  "cors": {
    "enable": true
  },
  "hooks": {
    "build": [
      "mkdir -p build",
      "yarn run build",
      "cp -f package.json build",
      "cp -fr dist build",
      "cp -fr src/data build/dist/src/data",
      "cd build && npm install --prod",
      "cd build && npm install grpc@1.8.4 --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc"
    ],
    "clean": ["rm -fr build", "rm -fr dist"]
  },
  "lambda": {
    "runtime": "nodejs8.10",
    "vpc": {
      "subnets": ["subnet-d8", "subnet-19", "subnet-7c"],
      "security_groups": ["sg-81"]
    }
  },
  "proxy": {
    "command": "node ./build/dist/src/index.js"
  },
  "stages": {
    "production": {
      "domain": "api.com"
    },
    "staging": {
      "domain": "staging-api.com"
    }
  },
  "environment": {
    "HOST": "10.2.50.1"
  }
}

```

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
The first thing I'd double check is that all of those subnets are private, Lambda apparently doesn't work in public subnets. Most of the AWS APIs are over the internet, so you'll need a NAT when used in a VPC as well.

**Comment by vespertilian** [comment]
@tj 

Thanks for the quick reply. 

Yes these subnets are private-ish, which has so far been by design. They have an internet gateway but no NAT. I don't want to add a NAT if I can help it, as I am cheap :grin: and don't want to pay $33 ish for each availability zone. This all works with the OSS version so it just the secret env vars that seem to be the issue.

You are right however that a lot of the AWS services are over the internet. Just recently I ran into this problem with AWS SES. My solution via a friends suggestion was to use AWS SNS which supports private link, and has some other advantages. So I post my email to an SNS topic then I have a function (deployed with apex) that is not inside a VPC that subscribes to the SNS topic and dispatches the email. 

Private link SNS: https://docs.aws.amazon.com/vpc/latest/userguide/endpoint-service.html

What services do you use for the encrypted ENV vars? I was reading through related github issues but I am not sure I understand the full picture on how this works currently. If you are using the AWS KMS that does support private link: 

Private link KMS: https://aws.amazon.com/about-aws/whats-new/2018/01/aws-key-management-service-now-supports-aws-privatelink/

So maybe there is a way to make it work. 

This might be a bit of a moot point for me anyway as I am wanting to store a signing key for JWTs which might be close to the limit as mentioned here: https://github.com/apex/up/issues/537 so I am thinking I will just use the KMS directly. 

Ideas summary: 

- Would be great if the secret env solution supported private link, otherwise adding that secret env vars cannot be used inside a VPC without a NAT to the docs could be helpful for others :smiley:.
-  It would be convenient for me if Apex Up, supported this SNS jump pattern, as it gets you around the VPC issue. Maybe it could include plain lambda deploy functionality like Apex. Not a big deal it would just save me installing both of the tools when deploying.

**Comment by vespertilian** [comment]
So I got SSM working, it supports private link! I just needed to add an endpoint to the VPC. 

![ssm-endpoint](https://user-images.githubusercontent.com/441418/44704700-b1125e00-aadf-11e8-966c-96a1ded332e8.png)

Ug, VPC is a bit of a pain, it is secure though, and as long as the service you want to use supports private link its not so bad.

It might be worth mentioning this in the VPC section of the docs. 

> I was contemplating going with #547 to effectively "bake" the env vars in at deploy time, just storing them in SSM for cross-team access. I'll give that some more thought!

So I don't have a strong opinion here. At least now that SSM is fixed I can use the other pro features and stop using the OSS version. The only config var I currently want to store securely is a key for signing JWTs, but that may be too big for the parameter store and I might be better using the KMA. 

Thanks again for your quick response!

**Comment by tj** [comment]
Cool thanks! I didn't know they had support for more than S3 now haha :D I'll see if that's something I can bake in by default, if I don't change how the env vars work

**Comment by vespertilian** [comment]
So private link costs money ~$10 / month / az - I thought it was free (oops) . Not as much as Nat $44 / subnet / month which is effectively / az / month AP (Sydney). So it's still a useful option.

Quick question: Is it just the encrypted vars that use the SSM service? If so could you add an option to turn these off when using up pro? This is so I can save some money on private link, as I am not using the encrypted env vars at all. I still want to use the other Up Pro features.

**Comment by tj** [comment]
@vespertilian good question! It's not possible to disable them at the moment, but I think I may go ahead with #547 which will be a deploy-time instead of runtime thing. Hopefully will have time for that this weekend

**Comment by vespertilian** [comment]
@tj great! I look forward to it!

**Comment by tj** [comment]
Closing :D tonight or tomorrow I'll do a Pro release with the change, going to see if I can shrink the binary size first
