### ISSUE TITLE
Changing team owner

### ISSUE THREAD

**Issue by aronneagu** [apex/up#707]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I would like t change to team owner, the one returned by `up team`, under Owner. I have used my email address and I would like to change that to a distribution list. 

On that note, does the owner email address have any special "powers"? Does it really matter which email is listed under owner?

## Steps to Reproduce

No steps to reproduce as the feature is missing.

**Comment by tj** [comment]
Hey! Currently the owner is the only one who can change billing, that's about it. Could you email me at tj@apex.sh with the team, and new email you'd like and I'll get that changed :D

**Comment by aronneagu** [comment]
Sent an email. Thanks a lot

**Comment by tj** [comment]
Awesome no problem :D — resolved for now
