### ISSUE TITLE
Passing SNS records

### ISSUE THREAD

**Issue by jadbox** [apex/up#708]
'm trying to use Up on an SNS triggered function. I've added the triggers via the aws lambda interface, and the lambda function does seem to get called on a GET, but I don't get the information related to the SNS message/body. I basically just get an empty request/message from SNS. It would be desirable for Up to package "event.Records" in the proxy if it exists to the user's server.

https://docs.aws.amazon.com/lambda/latest/dg/with-sns-create-package.html
```
console.log('Loading function');
 
exports.handler = function(event, context, callback) {
// console.log('Received event:', JSON.stringify(event, null, 4));
 
    var message = event.Records[0].Sns.Message;
    console.log('Message received from SNS:', message); 
    callback(null, "Success");
};
```

**Comment by tj** [comment]
I have mixed feelings about trying to cross over into Lambda-land, I think vanilla Lambda is great for event processing, without HTTP in front. Personally at least I think a nicer option would be to do Apex 2.0 so that it matches Up as closely as possible and doesn't require Terraform for resources

**Comment by jadbox** [comment]
I think this makes sense (although annoying that this almost works with just Up). Closing this issue in favor of Apex issue. https://github.com/apex/apex/issues/903
