### ISSUE TITLE
Set env variables in shell using `eval $(up env --shell -s test)`

### ISSUE THREAD

**Issue by sanjaypojo** [apex/up#711]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I love the `env` feature in pro and we’re using it extensively as a team. There are cases where we’d like to access env variables stored in up, but without running up itself. Would be cool if there was a way to “set” the terminal env using an up command and then run a completely unrelated script.

Discussed on slack, but adding it here so it's easy to track.

**Comment by tj** [comment]
Done! I'll have a new Pro release out tonight. Curious to hear more about the use-case, I was thinking about this a few months ago but I didn't have a concrete use myself

**Comment by tj** [comment]
0.7.8-pro is good to go, now you can do:

```
$ eval "$(up env export)"
$ echo "name=$DB_NAME user=$DB_USER"
name=users user=sloth 
```

or with a non-"development" stage:

```
$ eval "$(up env export -s production)"
$ echo "name=$DB_NAME user=$DB_USER"
name=users user=sloth 
```
