### ISSUE TITLE
up deploys throws an error when you have undeployed stages

### ISSUE THREAD

**Issue by sanjaypojo** [apex/up#716]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description
If you create a new stage and haven't deployed it yet, and then run `up deploys`, it throws an error that looks like this:
```
$ up deploys

     Error: fetching current versions: fetching test alias: ResourceNotFoundException: Cannot find alias arn: arn:aws:lambda:us-east-1:xxxxx:function:xxxxx
	status code: 404, request id: 8549eec4-xxxxx-b8d2-c7e3193035a3
```

## Steps to Reproduce
To reproduce, add a new stage to up.json and then run `up deploys`

## Fix
Delete stages from up.json and things work fine

**Comment by tj** [comment]
Sorry for the delay there! Just moved to the UK haha. Next release will have this fix, thanks for the report!
