### ISSUE TITLE
Access to original request URL

### ISSUE THREAD

**Issue by Checksum** [apex/up#717]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I'm trying to access the original request URL in my Go server. If the function is at `https://function.execute-api.ap-southeast-2.amazonaws.com/staging/blah`, I want to get `https://function.execute-api.ap-southeast-2.amazonaws.com`.

I don't have a custom domain setup, and none of the following seem to work:

`req.RequestURI`
`r.URL`
`r.Header.*`

Is there a way to do this?

**Comment by tj** [comment]
Might have to rely on the `Host` header field for in `r.Header`, `r.URL` is likely just the path most of the time

**Comment by Checksum** [comment]
Thanks, I found a work around.
