### ISSUE TITLE
Spelling error in the CLI

### ISSUE THREAD

**Issue by wamoyo** [apex/up#718]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

It should say "**to** the staging environment"

![screenshot from 2018-10-21 10 43 11](https://user-images.githubusercontent.com/1170326/47268386-4cdbab80-d51e-11e8-81a8-b65eed0ffce4.png)

## Steps to Reproduce

`up help deploy` in the terminal. I'm on Linux.

**Comment by tj** [comment]
thanks!
