### ISSUE TITLE
cors settings not being applied 

### ISSUE THREAD

**Issue by vespertilian** [apex/up#727]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

I do not think cors is being set. It was previously working for me. I am a subscriber to up pro but currently I am just using the base version. 

## Steps to Reproduce

I think this would be the quickest way you could verify my claim. 

Using this example
https://github.com/apex/up-examples/blob/master/oss/node-graphql/up.json

`up config` results in this:

```json
 "cors": {
    "allowed_origins": null,
    "allowed_methods": null,
    "allowed_headers": null,
    "exposed_headers": null,
    "allow_credentials": false,
    "max_int": 0,
    "debug": true
  },

```

Which does not match the defaults listed here https://up.docs.apex.sh/#configuration.cross_origin_resource_sharing

If there isn't a problem with the config, could you let me know where in AWS does cors get set? In the API Gateway? I want to go look at the settings myself to help me debug. 

Thanks!

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
Ahh those defaults in the output are a bit misleading, I didn't catch that but the Go middleware for CORS implements the defaults (instead of inside Up) so they don't appear there.

When you deploy with `debug: true` do you see any CORS related logs? They might help pin-point why it's not working for a request, may have to allow more header fields.

**Comment by vespertilian** [comment]
@tj Thanks for your quick reply. Sorry for my slow one. Debug true helped. You were right I think it was an authentication header change that was not part of the default set. 

For anyone who comes across this is what worked for me:

```json
  "cors": {
    "allowed_origins": [
      "https://staging.mydomain.com",
      "https://mydomain.com"
    ],
    "allowed_methods": [
      "HEAD",
      "GET",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "OPTIONS"
    ],
    "allowed_headers": ["*"],
    "allow_credentials": true
  },
```
