### ISSUE TITLE
Disable hooks

### ISSUE THREAD

**Issue by j** [apex/up#730]
Is it possible to disable hooks completely to not run any npm hooks?  My CI environment builds and manages cleanups, etc.

**Comment by tj** [comment]
At the moment we infer the build hook from package.json (https://github.com/apex/up/blob/master/config/runtimes.go#L191-L193), but I think you could use `"hooks": { "build": "" }` as a slight hack for now

**Comment by j** [comment]
@tj yep, that's what I ended up doing.  Made me sad. :P haha.  It'd be cool to just have apex package what it needs to and not run any hooks inside of the pckage.json.
