### ISSUE TITLE
Error: cannot find the API, looks like you haven't deployed

### ISSUE THREAD

**Issue by df1228** [apex/up#738]
## Prerequisites

* [ ✅] I am running the latest version. (`up upgrade`)
* [ ✅] I searched to see if the issue already exists.
* [ ✅] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ No ] Are you an Up Pro subscriber?

## Description

trying up-examples/oss/static-basic demo, up url got this error

## Steps to Reproduce

1. clone https://github.com/apex/up-examples/tree/master/oss/static-site
2. run `up`
3. run `up url`

**Comment by tj** [comment]
You may have to `up stack delete` and try `up` again, unfortunately AWS uses eventual consistency for some APIs, I still haven't found a good fix for those intermittent issues but it only happens on the first deploy

**Comment by tj** [comment]
closing for now, but I'll keep trying to find a fix, no reply from the AWS team yet really

**Comment by russelldavis** [comment]
Trying `up` for the first time, this just happened to me as well. Really bad first time experience. I'd suggest updating the error message to include the `up stack delete` suggestion (or even better, do it automatically in the code when this failure happens on first deploy).

**Comment by tj** [comment]
Yeah it's not great, seems like there's nothing I can do to fix it, AWS doesn't seem to realize how broken their stuff is
