### ISSUE TITLE
Up deploys removed ?

### ISSUE THREAD

**Issue by dfang** [apex/up#739]
## Prerequisites

* [ yes ] I am running the latest version. (`up upgrade`)
* [ yes ] I searched to see if the issue already exists.

## Description

> up version
0.7.7

> up deploys

     Error: "deploys" is invalid, must be one of:

  • production
  • staging

as well as `up rollback`, are these subcommands removed, as they did not in `up -h`.

## Steps to Reproduce

just run `up deploys`

**Comment by tj** [comment]
Those commands are only available with the Pro version, but if you're signed in (via `up team login`) then `up upgrade` will automatically grab the Pro version.

**Comment by dfang** [comment]
Thanks, if it's a feature for Pro version, the error message should be
better.

TJ Holowaychuk <notifications@github.com> 于2018年11月28日周三 下午10:50写道：
