### ISSUE TITLE
Up env sort variables when printing

### ISSUE THREAD

**Issue by bfelbo** [apex/up#750]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

We start having 20+ variables using `up env` and it can become hard to see if a variable is present in a certain stage. It would be great if the output list would be sorted as that would this much easier.

## Steps to Reproduce

Run `up env`.

**Comment by tj** [comment]
agreed! I thought I did already but I'll check that out

**Comment by tj** [comment]
`up upgrade` for 0.9.1-pro with this change 🎉
