### ISSUE TITLE
Increase ".proxy.timeout" to current Lambda execution timeout

### ISSUE THREAD

**Issue by openfinch** [apex/up#751]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

In the current release, the timeout value is capped to 25 seconds following from issue #264 and PR #273. 

Would it be possible to update this in the next release to cap this execution to 600 seconds *(less any required overhead)* to match with Lambda's execution timeout?

## Steps to Reproduce

N/A

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
ahhh unfortunately the API Gateway limit is 30 seconds, and we need a few seconds of a buffer to allow Up to handle the responses, instead of APIGW taking over and timing out for example

**Comment by tj** [comment]
darn! Thanks though :D — closing this one for now but hopefully they'll increase the timeout at some point

**Comment by t1bb4r** [comment]
This would be useful for me as I call the lambda function directly some times (cloudwatch).
