### ISSUE TITLE
Streaming file uploads silently failing

### ISSUE THREAD

**Issue by sioked** [apex/up#753]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag. (I don't think it's relevant)
* [X] Are you an Up Pro subscriber?

## Description

I'm trying to upload a file to a node.js API (using multipart requests), then take that upload and stream it direct into the AWS S3 SDK to push the file into an S3 bucket. The files that I'm trying to upload are like 300kb in size, and when I run this locally it works. For some reason, when I try to deploy the same code via Up, the request hangs when I try to stream the file to S3 until the request times out. I tried increasing the timeout to 25s to see if i can get any errors or anything, but it just waits until that 25s is up and the request times out.

I know there's a limitation on returning a stream from a lambda, but I could not find any limitations on using streams inside of a lambda, and I'm not getting any error messaging to indicate what the problem might be.

Are you aware of any possible issues with using streams on Node.JS via Up?

## Steps to Reproduce

The basics of the code look like this:

```typescript
export async function uploadStream(stream: Stream, filename: string, contentType?: string) {
  const params = {
    Body: stream,
    Bucket: BUCKET_NAME,
    ContentType: contentType || '',
    Key: filename,
  }
  return s3.upload(params).promise();
}

export async function handleRequest(filePromise: IUpload) {
  const file = await filePromise;
  const key = `files/${
    file.filename
  }`;
  const beforeUpload = Date.now();
  console.log('Before uploading to S3');
  await uploadStream(file.createReadStream(), key, file.mimetype);
  console.log(`Upload to s3 took ${Date.now() - beforeUpload}ms`);
  updatedStimulus.imageKey = key;
}```

I'm using graphql-upload to get the uploaded file, but I also tried creating a stream by downloading a file using axios and using the stream to upload to s3. Both situations failed for me. And I've got no errors in my log to figure out why!

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
Hmm does it seem to reach "Before uploading to s3"? I wonder if there's a missing stream event handler preventing any errors from showing, and then it's timing out, but the `up logs` should output an error indicating a timeout

It might not be possible for your app but I've found uploading directly from the client (browser too) with pre-signed S3 urls really helpful for offloading work and improving latency https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

**Comment by sioked** [comment]
I figured it out!

I was deploying into a VPC and my VPC did not allow access to the S3 bucket I was trying to save to, so it was hanging at the network layer when trying to either write to S3 or access any external resources.

I'm rebuilding my stack and leaving out the vpc for now since I don't want to pay extra for a NAT gateway for external resources. Thanks for the response!

**Comment by tj** [comment]
ah nice! Glad you figured it out!
