### ISSUE TITLE
Override project vpc to "no vpc" in function.json

### ISSUE THREAD

**Issue by sean256** [apex/up#754]
## Description

I need to be able to override project.json `vpc` settings to "NO VPC"

## Steps to Reproduce

Set `vpc` settings in project.json
In function.json I have tried:

- `"vpc": null`
- `"vpc": {}`
- `"vpc": false`

In all cases the function deploys using the VPC settings from project.json

Maybe this is related to https://github.com/apex/up/issues/705 ?

**Comment by tj** [comment]
function.json? Sounds more like https://github.com/apex/apex — but if you meant Up, I'm not sure what good solution is yet for that, some people manually added it in the console so it would be a breaking change.

You may have to visit the Lambda function in the AWS Console and manually remove the VPC for now, subsequent deploys won't add it back if the config is removed from up.json .

**Comment by tj** [comment]
closing since it sounds like a dup of #705 but let me know if removing it in the console doesn't work

**Comment by sean256** [comment]
@tj you are correct I meant to post this in apex
