### ISSUE TITLE
Support deployment to Stockholm Region (eu-north-1)

### ISSUE THREAD

**Issue by nettum** [apex/up#755]
As far as I can see this relatively new region support lambda and the same functionality as other regions. 
Could it be added to available regions? 

See  https://aws.amazon.com/blogs/aws/now-open-aws-europe-stockholm-region/ & https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

Thanks!

**Comment by tj** [comment]
missed that! will do

**Comment by poacher2k** [comment]
This does not work using v0.8.1, and I'm getting the following instead:
`initializing: reading config: validating: .regions: "eu-north-1" is invalid [..]`

**Comment by tj** [comment]
ahh you're right, my bad, I will do a OSS release soon, Pro should have it already

**Comment by Skull0ne** [comment]
Do you have any update for that request?

Thanks
