### ISSUE TITLE
Is it possible to run Nuxt/Next?

### ISSUE THREAD

**Issue by nahtnam** [apex/up#756]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I was wondering if it is possible to run a nuxt or next server with up? If so, how?

## Steps to Reproduce

N/A

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
I'm not familiar with Nuxt but here's a Next example https://github.com/apex/up-examples/tree/master/oss/node-next — pretty much any Node application should work.

**Comment by nahtnam** [comment]
Thank you! Quick question though, does this support SSR? There doesn't seem to be much up related configuration so I'm not really sure what is happening. Does up run `npm run build` and then `npm start`?

**Comment by tj** [comment]
Yep! By default Up looks at the package.json scripts, however you can define custom hooks https://up.docs.apex.sh/#configuration.hook_scripts

**Comment by nahtnam** [comment]
Great, I'll give it a shot, thanks!
