### ISSUE TITLE
Faster logging

### ISSUE THREAD

**Issue by tj** [apex/up#758]
👍  if you find the logging annoyingly slow. I can improve the search speed, but the tailing time is limited by cloudwatch logs at the moment.

- [ ] new implementation
  - [ ]  write it
  - [ ] integration
  - [ ] remove `fields` namespacing
- [ ] remove old grammar
- [ ] parse Lambda logs
- [ ] rewrite examples
- [ ] rewrite documentation
- [ ] QA

**Comment by tj** [comment]
not sure if it's worth it, sometimes cloudwatch seems reasonably, sometimes very slow, not really sure why

**Comment by louisrli** [comment]
Not sure what happened to this or if you have any recommendations, I'm on the latest release and `up logs staging -S5m` is showing no results after 15+ minutes (our staging has very little traffic etc although our prod has a good amount of traffic). Is there anything I can do on my side to improve this process?

**Comment by tj** [comment]
@louisrli unfortunately that's just the speed of CloudWatch Logs, I'm not sure why it's so slow, it's hard to imagine how it could take so long. Long-term it might be nice to change it to use CloudWatch Insights instead
