### ISSUE TITLE
Tags not marked as releases? up upgrade stuck at 0.8.1

### ISSUE THREAD

**Issue by adriangoransson** [apex/up#760]
## Prerequisites

* [ ] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Not sure if this is intentional, but I couldn't find anything about it in the issue tracker. `0.8.1` is the [latest release](https://github.com/apex/up/releases) even though newer tags exist.

`eu-north-1` is not recognized as a valid region in the current version. :(

## Steps to Reproduce

    up upgrade -v
    ⠹ 1.304s  DEBU up version 0.8.1 (os: darwin, arch: amd64)
        No updates available, you're good :)

    up version
    0.8.1

**Comment by tj** [comment]
0.8.1 is the latest for the OSS version, I messed up those tags—removed! Up Pro has had new features though which is why they don't align at the moment

**Comment by adriangoransson** [comment]
I see. I'll have to build from source then I guess. Thanks anyway, for a great tool!
