### ISSUE TITLE
Fix negation of nested directories in .upignore

### ISSUE THREAD

**Issue by tj** [apex/up#762]
The following won't work at the moment because `src/` is matched by `*`, preventing further traversal.

```
*
!src/generated/**
```

Most people may not notice this since root-level is fine:

```
*
!dist/**
```

**Comment by tj** [comment]
shit, actually I think this is the same behaviour as Git, but I can't say it's intuitive. I had to use this in Git:

```
*
!src
!src/generated
!src/generated/**
!package.json
```

**Comment by tj** [comment]
closing, I'll make a note in the documentation. https://stackoverflow.com/questions/5241644/using-gitignore-to-ignore-everything-but-specific-directories mentions the same thing haha. TIL

**Comment by Siyfion** [comment]
Ah perfect! What whacky syntax though, definitely think a note in the docs would be good!
