### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by danikarik** [apex/up#764]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Could not login after clicking confirmation link.

## Steps to Reproduce

I'm trying to login to get Pro subscription. After running `up team login`, I receive confirmation email. Sign in page shows that I'm successfully logged in, but terminal waits for confirmation and fails with:
```
Error: login: requesting: Post https://teams.apex.sh/login: read tcp 192.168.0.106:52060->13.32.56.33:443: read: operation timed out
```

**Comment by tj** [comment]
Very strange! Mind trying again? I just double checked with my account, seems ok and it looks like you can reach the API, so I don't think it's a firewall issue

**Comment by danikarik** [comment]
@tj works, when I use VPN. Maybe ISP problems.
