### ISSUE TITLE
Some folder inside node_modules disappeared on lambda server

### ISSUE THREAD

**Issue by timqian** [apex/up#765]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

Some folder disappeared after `up`

on my local machine
![Screen Shot 2019-04-24 at 11 04 22 AM](https://user-images.githubusercontent.com/5512552/56629695-ccd6ff80-6680-11e9-82a3-389b8c30ceec.png)

downloaded from AWS lambda
![Screen Shot 2019-04-24 at 11 03 56 AM](https://user-images.githubusercontent.com/5512552/56629686-c5175b00-6680-11e9-864f-14229443802a.png)

the dist folder is required

Does anyone meet this before?

**Comment by timqian** [comment]
Find the cause, the reason is I ignored `dist` in `.upignore`.
Did not realize `.upignore` ignores folders in node_modules too

**Comment by tj** [comment]
I think `/dist` would work for root-only, maybe try that and `up build --size` to see if the others are still in node_modules
