### ISSUE TITLE
How to turn off some/all logging messages to CloudWatch (e.g. "started app")

### ISSUE THREAD

**Issue by bfelbo** [apex/up#770]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] Are you an Up Pro subscriber?

## Description

Up logs a few messages to CloudWatch. This increases our logging output, thereby making it more cumbersome to handle and analyze our CloudWatch logs.

This is particularly the case for the logging message `set variable`, which is printed for every env variable that up sets. We have quite a few env variables, and would therefore like to turn these messages off.

**Comment by tj** [comment]
I have `{ logs: { disable: true }}` but I think I missed wrapping the env variable parts with that, I'll add it in next release!

**Comment by bfelbo** [comment]
How about having 3 levels (OFF, INFO, DEBUG) similar to how it’s often done for verbosity? 

The other log messages are useful. For now it’s only the end variable that’s spammy, and that I’d classify as DEBUG. I could also imagine that you might want to add more DEBUG log messages in the future.

**Comment by tj** [comment]
v1.3.0-pro will be uploaded in about 30m

**Comment by aitchkhan** [comment]
@tj, this does not seem to work with the community version.
