### ISSUE TITLE
Deploying to us-west-2, stack attempted to register certs in us-east-1.

### ISSUE THREAD

**Issue by trace-andreason** [apex/up#772]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [ ] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I was running into issues setting up a domain name from an external registrar, but eventually got everything sorted out. I was deploying to us-west-2, but the certificates were registered in us-east-1. I was running into issue #430 and got the certs created in us-west-2 using DNS verification, but I was still having issues because the certs were still pending approval in us-east-1.

## Steps to Reproduce

I don't know if this is reproducible, but here is what I did:

my up.json looked like this, where apexup is the standard IAM profile in the documentation:
```
{
  "name": "appname",
  "profile": "apexup",
  "regions": ["us-west-2"],
  "stages": {
    "production": {
      "domain": "example.com"
    }
  }
}
```

I ran `up stack plan`, and stalled and confirming my domain. Of course I didn't receive any emails due to not having email set up on the domain. I killed the command and ran `up stack plan` again with no issues. It added an api domain, api mapping and dns record for my domain. I ran `up stack apply` with no issues. Then I got the following error message when calling `up stack`:

ApiDomainProduction: Unable to associate certificate arn:aws:acm:us-east-1:385116958023:certificate/607218f5-6daf-47f8-982e-d4fc327f135b with CloudFront.

**Comment by tj** [comment]
The certs are always created in us-east-1 when using API Gateway's "edge" endpoints, it's just some strange requirement, the regional endpoints are created in a specific region

**Comment by trace-andreason** [comment]
Understood. I thought this was missing from the documentation, but I see that it's in there. Thanks!
