### ISSUE TITLE
Error: selecting handler | waiting for listening state

### ISSUE THREAD

**Issue by builtbyproxy** [apex/up#779]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [X] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description
[apollo-server](https://www.apollographql.com/docs/apollo-server/) is consistently throwing an error similar to: 
```
Error: selecting handler: waiting for http://127.0.0.1:50865 to be in listening state: timed out after 17s
```

When I run apex locally with `up start` I get this output in my log: 
![image](https://user-images.githubusercontent.com/16897508/64072761-c2381100-ccd7-11e9-8fd9-f20400033844.png)

This is with the `up.json` as:
```
{
    "name": "up-test",
    "profile": "Lachlan",
    "regions": [
        "ap-southeast-2"
    ],
    "proxy": {
        "command": "node app.js",
        "timeout": 25,
        "listen_timeout": 17
    }
}
```

I am running the code found here: 
https://gist.github.com/builtbyproxy/545b295a34038420e5367291de2d6116

Please note with the above code. It has **two** versions of code. My production code using [nexus](https://github.com/prisma/nexus). Along with my test code using [apollo-server's](https://www.apollographql.com/docs/apollo-server/getting-started/) default code. 

Both work fine running `node app.js`. Neither work running `up start`.
A final note. If I run up start it works fine, but once it times out it doesn't work. This causes my server to time out when i deploy using `up` and never work at all.

## Steps to Reproduce

Describe the steps required to reproduce the issue if applicable.

* `mkdir apollo-problem && cd apollo-problem && npm init`
* spam enter
* `npm i graphql apollo-server`
* `touch up.json`
* add to the up.json
```
echo '{
    "name": "up-test",
    "profile": "Lachlan",
    "regions": [
        "ap-southeast-2"
    ],
    "proxy": {
        "command": "node app.js",
        "timeout": 25,
        "listen_timeout": 17
    }
}' > up.json
```
* get app.js: 
```
curl -O https://gist.githubusercontent.com/builtbyproxy/545b295a34038420e5367291de2d6116/raw/f199de5a9860947f7c5a2c295abbfa942d1ec8a8/app.js app.js
```
* `up start -v`
* get error in 17 seconds

## Edit: 
As of the 2nd of september, I will be away for two weeks until the 18th of september, thankyou for any help however I wont be able to respond until then! 

A big thankyou once again!

**Comment by tj** [comment]
That error is a sign that the application isn't binding to the __PORT__ variable provided by Up, make sure to `const { PORT } = process.env` and use that variable when listening

**Comment by builtbyproxy** [comment]
Problem solved! Thanks a lot Tj, I was listening to port in some attempts but wasnt pulling it from `process.env`.
Seems to be going great, thanks again
