### ISSUE TITLE
Stage management

### ISSUE THREAD

**Issue by tj** [apex/up#78]
Curious what people's ideals are regarding stage/environment management. I tend to just use branches, but if you have a preference let me know! 

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/up.STAGE.json%20overriding%20up.json)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/up.STAGE.json%20overriding%20up.json/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/up.STAGE.json%20inheriting%20from%20up.json)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/up.STAGE.json%20inheriting%20from%20up.json/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/Add%20nested%20stage-related%20config%20in%20up.json)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/Add%20nested%20stage-related%20config%20in%20up.json/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/Just%20use%20GIT%20branches)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDVEWY90YDG7AM11WHC6CG0/Just%20use%20GIT%20branches/vote)

Pros of branches:

- Simple to implement, do basically nothing :D

Cons of branches:

- Merge conflicts
- No overview of config for all stages

**Comment by olivoil** [comment]
Voted for up.STAGE.json overriding, similar to how `apex` does it. It makes it easier to merge `staging` into `production` without conflicts and see what changed in the configuration since the last merge in `production`

**Comment by tj** [comment]
Closing, I think `{ "stages": { "STAGE": {} }` has kind of naturally won, primarily because it should be relatively rare to override a large portion of the properties, I think just overriding specifics in there will make more sense having used it for a while now
