### ISSUE TITLE
Change default runtime to nodejs10.x

### ISSUE THREAD

**Issue by tj** [apex/up#784]
8.x is end-of-life now (seems often holy haha) 

- [ ] QA and merge https://github.com/apex/up/pull/778
- [x] change default 
- [ ] adjust docs

**Comment by Prinzhorn** [comment]
- [ ] (PRO) Change warming runtime as well

**Comment by tj** [comment]
ahh you're right thanks! AWS doesn't terminate support for the older versions so it should be fine, but wouldn't hurt to update them (I still have side projects running on 6.x)

**Comment by tj** [comment]
Bad news for Python folk, looks like AWS completely removed the Python binaries in the nodejs10.x runtime, supporting Python would require a Python-specific shim now

**Comment by Prinzhorn** [comment]
Thank you very much.

> AWS doesn't terminate support for the older versions so it should be fine, they just don't allow updates, but wouldn't hurt to update them (I still have side projects running on 6.x)

I see. I have projects running in customer's AWS accounts and they're the ones getting the EOL e-mails. That's why I'm concerned about having everything upgraded.

**Comment by tj** [comment]
Yeah the way they word it makes it sound scary than it is haha, it'd be pretty terrible if they just stopped existing Lambdas, especially at the rate Node EOL's these.
