### ISSUE TITLE
[Feature] completely separate stages

### ISSUE THREAD

**Issue by Prinzhorn** [apex/up#785]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Essentially we need this

```json
{
  "stages": {
    "staging": {
      "lambda": {
        "runtime": "nodejs10.x"
      }
    },
    "production": {
      "lambda": {
        "runtime": "nodejs8.10"
      }
    }
  }
}

```

Due to EOL of node 8 I upgraded several up deployments. `nodejs10.x` is the first runtime that runs on Amazon Linux 2.

![Selection_535](https://user-images.githubusercontent.com/679144/67278899-3a49d880-f4ca-11e9-9bd7-63c2cbb82748.png)

This broke a deployment, because we had binaries that were compiled for Amazon Linux 1.

Now here's the feature request: Currently it's not possible to test a different runtime on staging while keeping production running as-is. It seems "lambda.runtime" is ignored inside the stages, at least the Version on the Lambda Dashboard doesn't change. This kind of makes sense because as far as I understand there's a Go proxy doing the "/production/" and "/staging/" routing inside the same runtime.

Assuming other runtimes (Python, Ruby, Java, Go, .NET) will eventually have versions running Amazon Linux 2 it would be really nice to be able to test in staging before changing production.

Edit: for anyone interested, this is related https://github.com/alixaxel/chrome-aws-lambda/issues/37

**Comment by tj** [comment]
Agreed! I'll get that in the next release

**Comment by Prinzhorn** [comment]
Nice, thanks!

**Comment by Prinzhorn** [comment]
@tj did this make it into `1.5.0-pro`? The commit is tagged v1.5.0 but the History.md doesn't mention it. I just added 

```json
"stages": {
  "staging": {
    "lambda": {
      "runtime": "nodejs10.x"
    }
  }
}
```

To an existing project. After running `up` I still see "Runtime: nodejs8.10" on the web dashboard for the latest version aliased "staging".

**Comment by tj** [comment]
Hmm should be in there I think, I'll double check

**Comment by tj** [comment]
Found it, I was saving a reference to the `runtime` before applying overrides. I'll start releasing `1.5.1`

**Comment by Prinzhorn** [comment]
It's working now, thanks!

**Comment by tj** [comment]
Awesome, sorry about that!
