### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by tj** [apex/up#79]
Forgot to add gzip / brotli.

- [ ] add middleware
- [ ] add tests
- [ ] ignore if origin has already compressed

**Comment by angleman** [comment]
Was brotli support included with this? I'm seeing content gzipped but not brotli compressed on Chrome which is sending `accept-encoding: gzip, deflate, br`.

**Comment by tj** [comment]
I couldn't find a decent brotli implementation which exceeded the gzip performance, so it seemed like it wasn't worth adding (at the time)
