### ISSUE TITLE
The exact same server works on staging but not on production

### ISSUE THREAD

**Issue by keyserfaty** [apex/up#793]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description
Deploying a node.js server with `up staging` and `up production`. Staging works fine, production doesn't. Its a graphql server. I'm getting this when accessing `/production/graphql`: `Bad Request • Please try your request again or contact support.`.
The deploy is been done correctly. The only weird thing I see is `x-cache: Error from cloudfront` on the prod request.

## Steps to Reproduce

``` js
// app.js

require('dotenv').config()

require('./firebase')

const util = require('util')
const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')

const { request } = require('graphql-request')

const { server } = require('./server')

const envUrl = process.env.ENV_URL
const envPort = process.env.PORT
const graphqlRoute = `${envUrl}:${envPort}${server.graphqlPath}`

const app = express()

app.use(bodyParser.json())

server.applyMiddleware({ app })

app.listen({ port: envPort }, () =>
  console.log(`🚀 Server ready at ${graphqlRoute}`),
)


```

``` js
// server.js

const { ApolloServer } = require('apollo-server-express')

const { importSchema } = require('graphql-import')
const { applyMiddleware } = require('graphql-middleware')
const { makeExecutableSchema } = require('graphql-tools')

const { resolvers } = require('./resolvers')
const { permissions } = require('./permissions')

const { getUser } = require('../modules/users/models')
const db = require('../db/connection')

const typeDefs = importSchema('server/schema.graphql')

const schema = applyMiddleware(
  makeExecutableSchema({
    typeDefs,
    resolvers,
  }),
  permissions,
)

const server = new ApolloServer({
  schema,
  tracing: process.env.UP_STAGE === 'development',
  context: async ({ req }) => {
    const token = req.headers.authorization || ''
    const user = await getUser({ token })

    return { user, db }
  },
})

module.exports = {
  server
}

```

## Love Up?

Please consider signing up for Up Pro (https://up.docs.apex.sh/#guides.subscribing_to_up_pro) or donating via https://opencollective.com/apex-up/donate.

## Slack

Join us on Slack https://chat.apex.sh/

**Comment by tj** [comment]
Hmm I haven't seen that yet, especially if the same app works fine in staging that seems odd.

If it's not a hassle the first thing to try would maybe be re-deploying the app with a new `up.json` "name" field, you can `up stack delete` the old one, but renaming will ensure that every resource is fresh (AWS has some caching internally).

I'll see if I can find more info about this error!

**Comment by tj** [comment]
Also maybe deploy with:

```json
{
  "error_pages": {
    "disable": true
  }
}
```

Just to ensure that's not getting in the way.

**Comment by tj** [comment]
No luck finding anything which stands out so far. It's possible to enable API Gateway logging, which might provide some more insight into what is failing at that level, but it's awkward to view them. You have to:

- visit `/apigateway` in the console
- click `Stages` in the left menu
- view the `Logs/Tracing` tab
- enable the `Enable CloudWatch Log` checkbox

After that it'll start logging to a CloudWatch logs group (/cloudwatch in the console). AWS likes to make this as painful as possible haha.. but I would try the renaming first just in case it was an AWS bug.

**Comment by keyserfaty** [comment]
Hey @tj , thanks a lot. Disabling the error page I was able to see the error I was getting from my Graphql server. Turns out the graphql playground is disabled in production and that's why I was getting that error. Sorry for the noise and thanks for your help :)

**Comment by tj** [comment]
ahhh darn! Thanks for letting me know, error pages are definitely causing too much trouble to be worth it haha, might just remove it entirely
