### ISSUE TITLE
GitHub Actions - Pro Login - Password? 

### ISSUE THREAD

**Issue by chrismalek** [apex/up#797]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [X] I inspected the verbose debug output with the `-v, --verbose` flag.
* [X] Are you an Up Pro subscriber?

## Description

I am trying to setup a github action to deploy on push. I am a pro subscriber and it seems when `up team login` is entered it sends an email. Is there a way to pass a password? The login works but I have to respond to the email. I want to make it automated. I can't find anything in the docs. 

Here is the script I am trying to run in the github action.

```sh
curl -sf https://up.apex.sh/install | BINDIR=. sh
./up team login --email $UPEmail --team $UPEmail
./up upgrade
./up production
```

**Comment by tj** [comment]
Ahh yep! For running in CI you can use `up team ci` which gives you an auth token you can set as an environment variable `UP_CONFIG`. Then all you should need is:

```
curl -sf https://up.apex.sh/install | BINDIR=. sh
./up upgrade
./up production
```

Here's the full guide: https://apex.sh/docs/up/guides/#deploying_applications_from_continuous_integration

**Comment by chrismalek** [comment]
Sorry I thought I read all the docs in that section.  Somehow I missed that.   Thanks for pointing out I am blind!  :-)
