### ISSUE TITLE
Support new regions on AWS

### ISSUE THREAD

**Issue by timqian** [apex/up#804]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## AWS introduced 3 more regions recently

```
ap-east-1
ap-northeast-2
ap-northeast-3
```

## Ref:
https://docs.aws.amazon.com/general/latest/gr/rande.html

## Current state

When I try `ap-eas-1`

```
     Error: initializing: reading config: validating: .regions: "ap-east-1" is invalid, must be one of:

  • us-east-2
  • us-east-1
  • us-west-1
  • us-west-2
  • ap-south-1
  • ap-northeast-2
  • ap-southeast-1
  • ap-southeast-2
  • ap-northeast-1
  • ca-central-1
  • eu-central-1
  • eu-west-1
  • eu-west-2
  • eu-west-3
  • eu-north-1
  • sa-east-1

```

**Comment by tj** [comment]
Ah nice! I missed those, I'll get those in soon
