### ISSUE TITLE
up command not recognized in zshell

### ISSUE THREAD

**Issue by dschinkel** [apex/up#807]
After installing up, the command is not recognized if I using zsh.  How do I get that working?

**Comment by tj** [comment]
Hmm what error do you get? Just `command not found`? It could be an issue with where it's installed, or your `$PATH`. It should install to /usr/local/bin by default

**Comment by dschinkel** [comment]
yea I messed up and used the custom directory and it did not install into `/usr/local/bin`.  I misunderstood the use for CI but now I get it.

thanks!
