### ISSUE TITLE
Cancelled Pro subscription, still being billed.

### ISSUE THREAD

**Issue by siegesmund** [apex/up#810]
Hi, 
I've deleted my stack and cancelled my subscription several months ago, but I continue to be charged each month. `up team status `shows that I have no active subscription and yet I was billed as recently as May 29? `up team unsubscribe` also indicates that I'm not subscribed to Pro.

**Comment by tj** [comment]
Hello, it could be because you weren't signed in to the team with the subscription.  Can you email me at tj@apex.sh with an invoice number? I'll take a look in Stripe and cancel/refund.

Thanks!
