### ISSUE TITLE
apex/apex documentation broken?

### ISSUE THREAD

**Issue by arjitj2** [apex/up#813]
Hi, 

We still use apex/apex in many of our projects, though it looks like the documentation (http://apex.run/) has been taken down now?

Is there a mirror of this documentation elsewhere? I understand the project is no longer supported, but at least the existing documentation being available would help us a lot!

Even if it was just a PDF download or something, so you don't have to keep the website up.

**Comment by tj** [comment]
The docs are still here https://github.com/apex/apex/tree/master/docs but it just seems like a waste of money to keep the domain up
