### ISSUE TITLE
Trouble with deploing zip archives with terraform

### ISSUE THREAD

**Issue by LarsMoran** [apex/up#817]
Hello! I'm new to apex up and got trouble. I'm working with terraform to deploy all my resources to AWS and i need to create zip archives to deploy it on s3 and then on lambda. So, trouble is in 'main' file, that created, when i run 'up build' in all cases. This file blocks deploing to AWS with error: "zip achive must be non-empty'. When i delete main file from zip, deploing is fine without errors. So, what can i do with this issue? I have about 100 lambda funcs and  cannot delete it mannualy

**Comment by tj** [comment]
Hmm I'm not sure I understand the scenario, you use Up to build and then Terraform to deploy? By default Up will [build](https://github.com/apex/up/blob/master/config/runtimes.go#L80) your program as `./server`, and Up itself injects `./main` (the Up proxy) before deploying so it becomes part of the zip.

The `./main` is cmd/up-proxy, and it's stored in the `up` binary, so I guess if you wanted to avoid using `up` for deployments you would have to do your own build and copy it to `./main`. This is where that happens https://github.com/apex/up/blob/cafa45273ba0949244219265f23803c47fda6947/platform/lambda/lambda.go#L907-L919

**Comment by LarsMoran** [comment]
That issue depends only on project requirements. We used another apex app for build zip, but it became out of date. So we need another solution, but also we need to save our terraform scripts for deploying. TY for answer, i will try to use your advice
