### ISSUE TITLE
Up re-uses an URL despite being run on a different repo, what gives?

### ISSUE THREAD

**Issue by RickCogley** [apex/up#823]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

Up re-used a URL despite being run on a different repository, albeit with the same files. 

## Steps to Reproduce

1. Had a repository with node server code in a subfolder, say, myrepo1/showcase/index.js (myrepo1 is a git repo)
2. Put up.json in myrepo root and configured (not mapped to a custom domain)
3. Ran up and up production and it created the usual URL ending in /staging and /production
4. Had trouble getting it to work so I decided to make git repo myrepo2/ and put the content of showcase in the root of that along with up.json to test if it was a path issue. I did NOT delete the initial stack that was made for myrepo1. 
5. Installed the stack via up and up production, and noticed the URL was the same. 

Shouldn't the URL be different, for a different repo? 
What determines whether it's installed newly or not?

**Comment by tj** [comment]
Hmm does your up.json have the same `name` property? At the moment the `name` and your AWS credentials is what would influence the URL, you can only have one app of the same `name` in a particular AWS account

**Comment by RickCogley** [comment]
ooof, yep, that'll be it. Same app name! 
Thanks for the explanation.
