### ISSUE TITLE
Secret management

### ISSUE THREAD

**Issue by tj** [apex/up#90]
- [ ] determine stage, pass `UP_STAGE`
- [ ] validate against the "reserved" env varsalready in lambda
- [x] use / for ssm it has built-in support
- [x] add reference to `environment`
- [x] decide on scoped or not
- [x] list with modification time / user
- [x] add
- [x] remove
- [x] cmd aliases (not sure if kingpin supports `ls` / `list` etc)
- [ ] add examples to `up help` 
- [x] load/validate `.environment` references on boot
- [ ] document (deploy required, precedence etc)
- [ ] update cmd docs
- potentially periodically check for changes and re-spawn the server (low priority for now)

---

Old discussion:

Lambda env vars are immutable and shipped along side the function, this is nice in the sense that you can simply roll back to the previous, and there's no "global" state, so you can test replacing a database with a subset of functions etc.

The downside to this is that it's awkward to manage config-wise. Currently `environment: {}` is supported for plain-text env vars, but it would be easy to just roll our own in KMS which get loaded and injected. 

Tough call as to which is more correct, but I generally think having magical global config is a malpractice. What happens when you roll back? What happens when you delete an "unused" var to find out an old func still uses? What happens when your teammember switches it on the fly and takes down your app? What happens when you want to deploy a canary with different env vars?

Any thoughts would be great!

It might make sense to have some syntax like `@DB_ADDR` to reference an env var, the you could use direnv or whatever means you prefer to set those. Avoids all the CRUD commands, still giving you a reasonable overview of what the app expects.

```json
{
  "environment": {
    "APP_FEATURE_1": "1",
    "APP_FEATURE_2": "0",
    "DB_ADDR": "@DB_ADDR"
  }
}
```

---

- Heroku: `heroku config:set FOO=bar`
- Convox:  `.env` file and `FOO=bar convox...` if FOO is declared in the environment
- Convox: `convox env set FOO=bar` as well
- Firebase: `firebase  functions:config:set foo=bar`

**Comment by tj** [comment]
I'll probably leave rollbacks for post-alpha but I'll make it the same as apex(1), basically just swaps back to an older release, so it's much quicker than re-deploying and retains the old env vars etc.

Yeah some form of dotfile is definitely doable, I guess my concern there is that it's not clear what is required by the app. Maybe dev Tobi has DB=xxx and Jane has DB_ADDR=xxx, you'd only know at runtime which fails.

That's why I think the combo of some sort of syntax and .envrc https://direnv.net would be maybe preferable, we can error/warn if it's missing.

**Comment by tj** [comment]
Not super thrilled about mutable global state but that seems to be the norm, people will probably expect that as an option at least.

**Comment by gjohnson** [comment]
What if it followed dockers pattern of using file paths as the value in the environment variable? Could do something like FOO=ssm://my/secret or whatever pluggable prefix (s3, file, etc) is needed, the shim would just detect and swap it with the value. 

This way lambda environment variables play along being immutable and a higher level secret component like SSM can handle what it's good at.

**Comment by tj** [comment]
@gjohnson hmm possibru! I'd like to stay away from vars coming from all over the place, but definitely could swap the implementation out for something else entirely. Need to think on workflow a bit more

**Comment by komuW** [comment]
I've used AWS parameter store for storing secrets[1]. But I guess it's just an abstraction over KMS

1. https://aws.amazon.com/ec2/systems-manager/parameter-store/

**Comment by marklawlor** [comment]
@tj @gjohnson is referring to [Docker Swarm's management of secrets](https://docs.docker.com/engine/swarm/secrets/). 

Secrets are created via the Docker CLI and are saved within the swarm. When deploying a container within the swarm you specify a white-list of secrets. These secrets will then be available within the Docker container at `/run/secrets` as plain text files. 

A keystore & whitelist functionality could be replicated by UP by using a combination of SSM and KMS.

```
up secrets create <key> <value> // Saves to KMS
up secrets inspect <key>
up secrets ls
up secrets rm <key>

up config create <key> <value> // Saves to SSM (unencrypted)
up config inspect <key>
up config ls
up config rm <key>
```

```up.json
{
  "environment": {
    "hardcodedValue": "hello world",
    "dbSecret": "kms://<secretKey>", # or  "dbSecret": "secret://<secretKey>", for consistent naming
    "dbConfig":  "ssm://<configKey"  # or  "dbSecret": "config://<secretKey>", for consistent naming
   }
}
```

While docker doesn't use the protocol of the path to the secrets, UP can use it is distinguish between secrets and config

**Comment by tj** [comment]
@marklawlor ah I see. I guess it's the prefix part I'm not fond of, maybe I just haven't hit a use-case where you'd want more than a single "store" for the secrets.

**Comment by marklawlor** [comment]
I agree with encrypting everything, I believe its makes sense and one key store is simpler to manage than two disconnected stores.

People may argue against KMS as it is a paid service and SSM is free, but there is nothing stopping those people using SSM / S3 / Lambda envs / third party service in their own codebase.

**Comment by marklawlor** [comment]
An alternative solution is to adopt what the [Serverless Framework solution](https://github.com/serverless/serverless-secrets-plugin).  They encrypt a file locally that is uploaded as part of the ZIP. The encryption key is stored in KMS and during the lambda load, its contents are unencrypted and hoisted to process.env

**Comment by tj** [comment]
Curious about options on scoping. My WIP stuff is just global, which would be nice for sharing between apps, other options would be prefixing with `APP-foo` or `APP-STAGE-foo` to isolate further, or leave as global and delegate that decision to the user.

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Global%20scope)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Global%20scope/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Scope%20to%20the%20app)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Scope%20to%20the%20app/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Scope%20to%20the%20app%20and%20stage)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSA6627VSSKJ423NAKG7TP5J/Scope%20to%20the%20app%20and%20stage/vote)

**Comment by tj** [comment]
Oh actually, I already plan on having per-stage config such as:

```json
{
  "stages": {
    "production": {
      "domain": "example.com"
    },
    "staging": {
      "domain": "stage.example.com"
    }
  }
}
```

So you could do:

```
$ up secrets add db-prod something --desc "Production database address"
$ up secrets add db-stage something --desc "Staging database address"
```

```json
{
  "stages": {
    "production": {
      "domain": "example.com",
      "environment": {
        "MONGO_ADDR": "@db-prod"
      }
    },
    "staging": {
      "domain": "stage.example.com",
      "environment": {
        "MONGO_ADDR": "@db-stage"
      }
    }
  }
}
```

Does that sound reasonable? I still like the idea of specifying which are required, so Up can fail early if those are undefined.

**Comment by tj** [comment]
@agurtovoy taking the day off, but I should have it finished tomorrow, though it'll likely be in the Pro plan, which I still have to set up and add more features to before launching that

**Comment by agurtovoy** [comment]
@tj FWIW, I don't think you *have* to have more features to launch the Pro plan; you can just say that more features are coming. I'd argue that most of current `up` users are early adopters by nature who are already taking a risk by betting their productions on what is obviously work-in-progress. Users like that are usually happy to pay for the promise of what's to come as long as they trust the vendor and are getting *some* immediate benefit.

**Comment by tj** [comment]
@agurtovoy true! I'd definitely like to get it out early as possible, with at least a few key features. I'll make sure to price accordingly for now, all of you early adopters are helping a lot
