### ISSUE TITLE
Init command

### ISSUE THREAD

**Issue by tj** [apex/up#92]
Ask them what type of app, generate a tiny example for them to deploy

**Comment by lukeed** [comment]
While cool, I'm not sure that this is crucial for an alpha. Can just clone an `up-example`

**Comment by tj** [comment]
true true, I'll remove it from alpha

**Comment by hhsnopek** [comment]
maybe just init the `up.json` and ask fill in the blanks w/questions like `npm init`

**Comment by tj** [comment]
changed my mind for now
