### ISSUE TITLE
curl sub-command

### ISSUE THREAD

**Issue by tj** [apex/up#93]
probably not worth cluttering the command list, but as an avid curl user I'd love to just `up curl /foo` etc, basically just an alias with the url.

Maybe as a hidden command :D

**Comment by tj** [comment]
Kingpin doesn't really support this without `--` so meh for now.

**Comment by hhsnopek** [comment]
It'd be amazing to be able to do something like this:

```bash
$ up curl -F "file=@file.jpg" /upload
# curl -F "file=@file.jpg" https://foobar.execute-api.us-east-1.amazonaws.com/development/upload

$ up curl /uploads/1
# 200 success ...
```

**Comment by tj** [comment]
:D

Kingpin has the same issue I had with the other arg parser in Apex. I'll have to tweak my fork some more, for now it would have to be `up curl -- -F "file=@file" /upload` etc, but `curl \`up url\` ...` isn't too bad either

**Comment by hhsnopek** [comment]
I don't think then double dash `--` is that terrible of a trade off for now, but holding off is fine too
