### ISSUE TITLE
Formalized log query grammar

### ISSUE THREAD

**Issue by tj** [apex/up#97]
Regexp hack at the moment, UX can be improved if a parser is implemented.

Current syntax:

```
up logs '.status = 200 and .path = "/" and .latency >= 50'
```

Actual query imposed due nested `.fields`:

```
up logs '.fields.status = 200 and .fields.path = "/" and .fields.latency >= 50'
```

Ideal:

```
up logs 'status = 200 path = "/" latency >= 50'
```

**Comment by tj** [comment]
went a little overkill and added some new operators `IN` etc that CW Logs does not have

- `level = "info"` -> `{ $.level = "info" }`
- `message = "info"` -> `{ $.message = "info" }`
- `status = 0` -> `{ $.fields.status = 0 }`
- `status = 0.123` -> `{ $.fields.status = 0.123 }`
- `status = .123` -> `{ $.fields.status = .123 }`
- `status = 200` -> `{ $.fields.status = 200 }`
- `price = 1.95` -> `{ $.fields.price = 1.95 }`
- `price == 1.95` -> `{ $.fields.price = 1.95 }`
- `price > 1.95` -> `{ $.fields.price > 1.95 }`
- `price < 1.95` -> `{ $.fields.price < 1.95 }`
- `price >= 1.95` -> `{ $.fields.price >= 1.95 }`
- `price <= 1.95` -> `{ $.fields.price <= 1.95 }`
- `price != 1.95` -> `{ $.fields.price != 1.95 }`
- `!enabled` -> `{ !$.fields.enabled }`
- `!   enabled` -> `{ !$.fields.enabled }`
- `foo = 1 || bar = 2` -> `{ $.fields.foo = 1 || $.fields.bar = 2 }`
- `foo = 1 && bar = 2` -> `{ $.fields.foo = 1 && $.fields.bar = 2 }`
- `foo = 1 or bar = 2` -> `{ $.fields.foo = 1 || $.fields.bar = 2 }`
- `foo = 1 and bar = 2` -> `{ $.fields.foo = 1 && $.fields.bar = 2 }`
- `foo.bar.baz = 1` -> `{ $.fields.foo.bar.baz = 1 }`
- `level = "error" and (duration >= 500 or duration = 0)` -> `{ $.level = "error" && ($.fields.duration >= 500 || $.fields.duration = 0) }`
- `cart.total = 15.99` -> `{ $.fields.cart.total = 15.99 }`
- `user.name like "obi"` -> `{ $.fields.user.name = "*obi*" }`
- `user in ("Tobi")` -> `{ $.fields.user = "Tobi" }`
- `pet.age in (1, 2, 3)` -> `{ $.fields.pet.age = 1 || $.fields.pet.age = 2 || $.fields.pet.age = 3 }`
- `user in ("Tobi", "Loki", "Jane")` -> `{ $.fields.user = "Tobi" || $.fields.user = "Loki" || $.fields.user = "Jane" }`
- `user.name in ("Tobi", "Loki", "Jane")` -> `{ $.fields.user.name = "Tobi" || $.fields.user.name = "Loki" || $.fields.user.name = "Jane" }`
- `not user.admin` -> `{ !($.fields.user.admin) }`
- `not user.role in ("Admin", "Moderator")` -> `{ !($.fields.user.role = "Admin" || $.fields.user.role = "Moderator") }`
- `user.role not in ("Admin", "Moderator")` -> `{ !($.fields.user.role = "Admin" || $.fields.user.role = "Moderator") }`

**Comment by lukeed** [comment]
That's awesome

**Comment by tj** [comment]
just realized I should remove the `up logs -error` flag, move it to the grammar as `up logs error`, then you can just do `up logs error or fatal` instead of `up logs 'level in ("error", "fatal")'`

**Comment by lukeed** [comment]
Very cool, 💯 for that~

**Comment by tj** [comment]
added implicit `and`:

```
'method in ("GET", "POST", "PUT") and ip = "207.194.*" and status = 200 and duration >= 50
```

to

```
method in ("GET", "POST", "PUT") ip = "207.194.*" status = 200 duration >= 50
```
